import { createContext, useContext, useState, useEffect } from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// TRANSLATIONS
// Every key used with t('key') must appear in ALL language objects below.
// ─────────────────────────────────────────────────────────────────────────────
const translations = {
  en: {
    // Nav
    nav_find: 'Find Helpers',
    nav_how: 'How It Works',
    nav_signin: 'Sign In',
    nav_notifications: 'Notifications',
    nav_language: 'Language',
    nav_dark: 'Dark',
    nav_light: 'Light',
    nav_dashboard: 'My Dashboard',
    nav_signout: 'Sign Out',
    nav_mark_all_read: 'Mark all read',
    nav_view_all: 'View all notifications →',

    // Notifications
    notif_1_title: 'Booking Accepted! 🎉',
    notif_1_body: 'Rajesh Kumar accepted your plumbing request.',
    notif_2_title: 'Payment Successful ✅',
    notif_2_body: '₹500 paid securely via escrow for AC repair.',
    notif_3_title: 'Worker Arriving Soon 🚗',
    notif_3_body: 'Sunita Sharma is 10 minutes away. Get ready!',
    notif_4_title: 'Job Completed 🛠️',
    notif_4_body: 'Kitchen sink repair marked as complete.',
    notif_5_title: 'Rate Your Experience ⭐',
    notif_5_body: 'How was Ajay Patel? Leave a review and help others.',

    // Landing hero
    hero_badge: '🏠 Trusted by 50,000+ Homeowners',
    hero_title_1: 'Your Neighbourhood',
    hero_title_2: 'Fix-It Heroes',
    hero_title_3: 'Are One Tap Away',
    hero_sub: 'Book verified plumbers, electricians, painters & more in your area. Fair prices. Secure payments. Instant booking.',
    hero_search_placeholder: 'What needs fixing? e.g. AC not cooling, leaking tap...',
    hero_search_btn: 'Find My Hero 🔍',
    hero_or: 'or browse by category',
    hero_stat_1: '50K+ Homeowners',
    hero_stat_2: '2,000+ Heroes',
    hero_stat_3: '4.9★ Rating',

    landing_cat_badge: "Browse Categories",
    landing_cat_browse: "Browse",
    landing_hiw_badge: "How It Works",
    landing_top_badge: "Top Rated",
    landing_top_explore: "Explore All",
    landing_jobs_badge: "Recently Completed Jobs",
    landing_test_badge: "Testimonials",
    landing_why_badge: "Why Choose HelperHub",
    landing_quick_popular: "Popular:",
    landing_card_master: "Master Professional",
    landing_card_reviews: "reviews",
    landing_card_all_set: "All Set!",
    landing_card_done: "Booking Completed",

    // Categories
    categories_title: 'What do you need fixed today?',
    categories_sub: 'Pick a category and we\'ll find verified heroes near you.',
    cat_plumber: 'Plumber',
    cat_electrician: 'Electrician',
    cat_carpenter: 'Carpenter',
    cat_ac: 'AC Technician',
    cat_painter: 'Painter',
    cat_cleaner: 'Cleaner',
    cat_mechanic: 'Mechanic',
    cat_gardener: 'Gardener',

    // How it works
    how_title: '⭐ How HelperHub Works',
    how_sub: 'From search to done in 5 simple steps',
    how_step1_title: 'Search Service 🔍',
    how_step1_desc: 'Type your repair need or browse verified local helpers by category & location.',
    how_step2_title: 'Book Professional 🤝',
    how_step2_desc: 'Select a top-rated hero, pick your date & time, and send an instant hire request.',
    how_step3_title: 'Pay Securely 🔒',
    how_step3_desc: 'Once accepted, funds are held safely in Stripe Escrow until the work is done.',
    how_step4_title: 'Job Completed 🛠️',
    how_step4_desc: 'Hero finishes the work at your doorstep. Both sides confirm job completion.',
    how_step5_title: 'Rate Experience ⭐',
    how_step5_desc: 'Payment is released to the hero, and you leave a star review to help neighbors!',

    // Top professionals
    top_title: '⭐ Top Rated Professionals Near You',
    top_sub: 'Verified, background-checked heroes with 4.8+ ratings',
    top_view_all: 'View All Helpers →',

    // Recent jobs
    recent_title: '⚡ Recently Completed Jobs',
    recent_sub: 'Real work, real results — happening right now in your city',

    // Testimonials
    testimonials_title: '❤️ What Homeowners Say',
    testimonials_sub: 'Real stories from your neighbors who love HelperHub',

    // Why us
    why_title: '🌟 Why Choose HelperHub?',
    why_sub: 'We\'re not just another booking app — we\'re your neighbours\' trusted helper network.',
    why_1_title: 'Verified Professionals',
    why_1_desc: 'Every helper is Aadhaar-verified and police-checked before they join our platform.',
    why_2_title: 'Secure Escrow Payment',
    why_2_desc: 'Money held safely in escrow, released only after you confirm job is done.',
    why_3_title: 'AI Price Estimation',
    why_3_desc: 'Know the fair price before booking. No surprise charges ever.',
    why_4_title: 'Emergency Booking',
    why_4_desc: 'Burst pipe at midnight? Our heroes are on-call 24/7 for emergencies.',
    why_calc_title: '🤖 AI Price Calculator',
    why_calc_sub: 'Instant fair estimate before you book',
    why_calc_category: 'Service',
    why_calc_hours: 'Hours needed',
    why_calc_estimate: 'Estimated cost',
    why_calc_note: 'Platform fee ₹50 added at checkout',

    // App download
    app_badge: '📱 Coming Soon',
    app_title: 'HelperHub in Your Pocket',
    app_sub: 'Book helpers, track jobs, and pay securely — all from your phone. iOS & Android apps launching soon!',
    app_ios: '🍎 App Store',
    app_android: '🤖 Google Play',

    // CTA
    cta_hire_title: 'Ready to find your fix-it hero?',
    cta_hire_sub: 'Join 50,000+ homeowners who trust HelperHub for every home repair.',
    cta_hire_btn: 'Hire a Hero Now 🚀',
    cta_work_title: 'Are you a skilled professional?',
    cta_work_sub: 'Join as a helper and start earning with your skills today!',
    cta_work_btn: 'Join as Helper ⚡',

    // Auth Page
    auth_welcome: 'Welcome Back! 👋',
    auth_join: 'Join HelperHub Today! 🎉',
    auth_create_free: 'Create your free account in seconds',
    auth_sign_in_to: 'Sign in to access your dashboard',
    auth_tab_signin: 'Sign In',
    auth_tab_create: 'Create Account',
    auth_joining_as: 'I am joining as...',
    auth_role_hire: 'I Need Help 🏠',
    auth_role_hire_desc: 'Hire friendly local heroes for home repairs',
    auth_role_work: 'I Want to Work 🛠️',
    auth_role_work_desc: 'List your skills and get hired by neighbors',
    auth_full_name: 'Full Name',
    auth_email: 'Email Address',
    auth_password: 'Password',
    auth_create_btn: 'Create Account 🎉',
    auth_signin_btn: 'Sign In 🚀',
    auth_loading: 'Please wait...',
    auth_demo: 'Demo Accounts:',

    // OTP
    otp_title: 'Verify Your Email',
    otp_sent: 'We sent a 6-digit verification code to',
    otp_verify_btn: "Verify & You're All Set! 🎉",
    otp_verifying: 'Verifying...',
    otp_back: 'Back',

    // Browse helpers
    browse_location: '📍 Delhi',
    browse_search: 'Search plumber, electrician, painter...',
    browse_filters: 'Filters',
    browse_results: 'helpers found nearby',
    browse_no_results: 'No helpers found. Try adjusting your filters.',
    browse_filter_price: 'Max Price',
    browse_filter_distance: 'Distance',
    browse_filter_rating: 'Min Rating',
    browse_filter_experience: 'Min Experience',
    browse_filter_language: 'Language',
    browse_filter_verified: 'Verified Only',
    browse_filter_today: 'Available Today',
    browse_filter_emergency: 'Emergency SOS',
    browse_filter_reset: 'Reset',
    browse_book: 'Book Now ⚡',
    browse_cat_all: 'All',

    // Booking flow
    book_step_date: 'Date',
    book_step_time: 'Time Slot',
    book_step_details: 'Job Details',
    book_step_review: 'Review',
    book_step_payment: 'Payment',
    book_choose_date: 'Choose a Date',
    book_choose_time: 'Pick a Time Slot',
    book_slots_for: 'Showing slots for',
    book_booked: 'Booked',
    book_job_title: 'Job Title',
    book_job_desc: 'Problem Description',
    book_address: 'Full Address',
    book_upload: 'Upload Photos of the Issue (Optional)',
    book_upload_hint: 'Drag & drop or click to upload',
    book_review_heading: 'Review Your Booking',
    book_hero: 'Hero',
    book_service: 'Service',
    book_date: 'Date',
    book_time: 'Time',
    book_job: 'Job',
    book_address_label: 'Address',
    book_service_fee: 'Service Fee',
    book_platform_fee: 'Platform Fee',
    book_total: 'Total',
    book_escrow: 'Your payment is held safely in escrow and released to the helper only after you confirm the work is done.',
    book_pay_secure: 'Secure Payment',
    book_card_number: 'Card Number',
    book_expiry: 'Expiry',
    book_cvv: 'CVV',
    book_name_card: 'Name on Card',
    book_ssl: '256-bit SSL encrypted · Powered by Stripe',
    book_pay_btn: 'Pay',
    book_securely: '🔒',
    book_continue: 'Continue',
    book_back: 'Back',
    book_cancel: 'Cancel',
    book_processing: 'Processing...',
    book_confirmed_title: 'Booking Confirmed! 🎉',
    book_confirmed_sub: 'Your fix-it hero is on the way!',
    book_view_status: 'View Job Status →',
    book_close: 'Close',

    // Footer
    footer_tagline: 'Your friendly neighbourhood service platform. Connecting skilled heroes with homeowners who need them — fast, safe, and fair.',
    footer_services: 'Services',
    footer_company: 'Company',
    footer_legal: 'Legal',
    footer_about: 'About Us',
    footer_careers: 'Careers',
    footer_blog: 'Blog',
    footer_press: 'Press',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_refund: 'Refund Policy',
    footer_rights: 'All rights reserved.',

    // Dashboard common
    dash_welcome: 'Welcome back',
    dash_active_jobs: 'Active Jobs',
    dash_total_spent: 'Total Spent',
    dash_total_earned: 'Total Earned',
    dash_rating: 'Rating',
    dash_completed: 'Completed',
    dash_pending: 'Pending',
    dash_accepted: 'Accepted',

    // General
    general_loading: 'Loading...',
    general_see_all: 'See All',
    general_close: 'Close',
    general_save: 'Save',
    general_cancel: 'Cancel',
    general_confirm: 'Confirm',
    general_hrs: 'hrs',
    general_per_hr: '/hr',
    general_jobs: 'jobs',
    general_yrs: 'yrs',
    general_today: 'Today',
    general_tomorrow: 'Tomorrow',
  },

  // ─── HINDI ────────────────────────────────────────────────────────────────
  hi: {
    nav_find: 'हेल्पर खोजें',
    nav_how: 'कैसे काम करता है',
    nav_signin: 'साइन इन',
    nav_notifications: 'सूचनाएं',
    nav_language: 'भाषा',
    nav_dark: 'डार्क',
    nav_light: 'लाइट',
    nav_dashboard: 'मेरा डैशबोर्ड',
    nav_signout: 'साइन आउट',
    nav_mark_all_read: 'सभी पढ़े',
    nav_view_all: 'सभी सूचनाएं देखें →',
    notif_1_title: 'बुकिंग स्वीकार! 🎉',
    notif_1_body: 'राजेश कुमार ने आपकी प्लंबिंग अनुरोध स्वीकार की।',
    notif_2_title: 'भुगतान सफल ✅',
    notif_2_body: '₹500 एसी मरम्मत के लिए एस्क्रो से भुगतान हुआ।',
    notif_3_title: 'वर्कर आ रहा है 🚗',
    notif_3_body: 'सुनीता शर्मा 10 मिनट दूर है। तैयार रहें!',
    notif_4_title: 'काम पूरा हुआ 🛠️',
    notif_4_body: 'किचन सिंक मरम्मत पूर्ण चिह्नित।',
    notif_5_title: 'अनुभव रेट करें ⭐',
    notif_5_body: 'अजय पटेल कैसे थे? रिव्यू दें।',
    hero_badge: '🏠 50,000+ घर मालिकों द्वारा भरोसेमंद',
    hero_title_1: 'आपके मोहल्ले के',
    hero_title_2: 'फिक्स-इट हीरो',
    hero_title_3: 'एक टैप दूर हैं',
    hero_sub: 'प्लंबर, इलेक्ट्रीशियन, पेंटर और अधिक को बुक करें। उचित मूल्य। सुरक्षित भुगतान। तत्काल बुकिंग।',
    hero_search_placeholder: 'क्या ठीक करवाना है? जैसे AC ठंडा नहीं, नल टपक रहा...',
    hero_search_btn: 'हीरो खोजें 🔍',
    hero_or: 'या श्रेणी से ब्राउज़ करें',
    hero_stat_1: '50K+ घर मालिक',
    hero_stat_2: '2,000+ हीरो',
    hero_stat_3: '4.9★ रेटिंग',
    categories_title: 'आज क्या ठीक करवाना है?',
    categories_sub: 'श्रेणी चुनें और हम पास के हीरो खोजेंगे।',
    cat_plumber: 'प्लंबर',
    cat_electrician: 'इलेक्ट्रीशियन',
    cat_carpenter: 'बढ़ई',
    cat_ac: 'AC तकनीशियन',
    cat_painter: 'पेंटर',
    cat_cleaner: 'सफाई वाला',
    cat_mechanic: 'मैकेनिक',
    cat_gardener: 'माली',
    how_title: '⭐ HelperHub कैसे काम करता है',
    how_sub: '5 आसान चरणों में सेवा पूरी',
    how_step1_title: 'सेवा खोजें 🔍',
    how_step1_desc: 'अपनी जरूरत टाइप करें या श्रेणी से हेल्पर खोजें।',
    how_step2_title: 'प्रोफेशनल बुक करें 🤝',
    how_step2_desc: 'टॉप-रेटेड हीरो चुनें, तारीख और समय तय करें।',
    how_step3_title: 'सुरक्षित भुगतान 🔒',
    how_step3_desc: 'पैसे एस्क्रो में सुरक्षित रहते हैं जब तक काम पूरा न हो।',
    how_step4_title: 'काम पूरा 🛠️',
    how_step4_desc: 'हीरो घर आकर काम पूरा करता है।',
    how_step5_title: 'अनुभव रेट करें ⭐',
    how_step5_desc: 'काम पूरा होने पर भुगतान जारी और रिव्यू दें।',
    top_title: '⭐ आपके पास के टॉप प्रोफेशनल',
    top_sub: 'सत्यापित, 4.8+ रेटिंग वाले हीरो',
    top_view_all: 'सभी हेल्पर देखें →',
    recent_title: '⚡ हाल ही में पूरे काम',
    recent_sub: 'असली काम, असली नतीजे — अभी आपके शहर में',
    testimonials_title: '❤️ घर मालिक क्या कहते हैं',
    testimonials_sub: 'पड़ोसियों की असली कहानियां',
    why_title: '🌟 HelperHub क्यों चुनें?',
    why_sub: 'हम सिर्फ बुकिंग ऐप नहीं — आपके पड़ोस का भरोसेमंद नेटवर्क हैं।',
    why_1_title: 'सत्यापित प्रोफेशनल',
    why_1_desc: 'हर हेल्पर आधार-सत्यापित और पुलिस-जांचा हुआ है।',
    why_2_title: 'सुरक्षित एस्क्रो भुगतान',
    why_2_desc: 'पैसे सुरक्षित एस्क्रो में, काम पूरा होने पर ही जारी।',
    why_3_title: 'AI मूल्य अनुमान',
    why_3_desc: 'बुकिंग से पहले उचित मूल्य जानें। कोई छिपा शुल्क नहीं।',
    why_4_title: 'आपातकालीन बुकिंग',
    why_4_desc: 'रात को पाइप फटा? हमारे हीरो 24/7 उपलब्ध हैं।',
    why_calc_title: '🤖 AI मूल्य कैलकुलेटर',
    why_calc_sub: 'बुकिंग से पहले तत्काल अनुमान',
    why_calc_category: 'सेवा',
    why_calc_hours: 'घंटे',
    why_calc_estimate: 'अनुमानित लागत',
    why_calc_note: 'चेकआउट पर ₹50 प्लेटफॉर्म शुल्क जुड़ेगा',
    app_badge: '📱 जल्द आ रहा है',
    app_title: 'HelperHub आपकी जेब में',
    app_sub: 'हेल्पर बुक करें, काम ट्रैक करें — फोन से। iOS और Android जल्द!',
    app_ios: '🍎 App Store',
    app_android: '🤖 Google Play',
    cta_hire_title: 'अपना फिक्स-इट हीरो खोजने के लिए तैयार?',
    cta_hire_sub: '50,000+ घर मालिक हर मरम्मत के लिए HelperHub पर भरोसा करते हैं।',
    cta_hire_btn: 'अभी हीरो बुक करें 🚀',
    cta_work_title: 'क्या आप कुशल पेशेवर हैं?',
    cta_work_sub: 'हेल्पर के रूप में जुड़ें और आज से कमाई शुरू करें!',
    cta_work_btn: 'हेल्पर के रूप में जुड़ें ⚡',
    auth_welcome: 'वापस स्वागत है! 👋',
    auth_join: 'आज HelperHub से जुड़ें! 🎉',
    auth_create_free: 'मुफ्त अकाउंट बनाएं',
    auth_sign_in_to: 'डैशबोर्ड एक्सेस करने के लिए साइन इन करें',
    auth_tab_signin: 'साइन इन',
    auth_tab_create: 'अकाउंट बनाएं',
    auth_joining_as: 'मैं किस रूप में जुड़ रहा हूं...',
    auth_role_hire: 'मुझे मदद चाहिए 🏠',
    auth_role_hire_desc: 'घर की मरम्मत के लिए हेल्पर बुक करें',
    auth_role_work: 'मैं काम करना चाहता हूं 🛠️',
    auth_role_work_desc: 'अपने कौशल से पड़ोसियों की मदद करें',
    auth_full_name: 'पूरा नाम',
    auth_email: 'ईमेल पता',
    auth_password: 'पासवर्ड',
    auth_create_btn: 'अकाउंट बनाएं 🎉',
    auth_signin_btn: 'साइन इन 🚀',
    auth_loading: 'कृपया प्रतीक्षा करें...',
    auth_demo: 'डेमो अकाउंट:',
    otp_title: 'ईमेल सत्यापित करें',
    otp_sent: '6-अंकीय कोड भेजा गया',
    otp_verify_btn: 'सत्यापित करें और शुरू करें! 🎉',
    otp_verifying: 'सत्यापित हो रहा है...',
    otp_back: 'वापस',
    browse_location: '📍 दिल्ली',
    browse_search: 'प्लंबर, इलेक्ट्रीशियन खोजें...',
    browse_filters: 'फ़िल्टर',
    browse_results: 'हेल्पर पास में मिले',
    browse_no_results: 'कोई हेल्पर नहीं मिला। फ़िल्टर बदलें।',
    browse_filter_price: 'अधिकतम मूल्य',
    browse_filter_distance: 'दूरी',
    browse_filter_rating: 'न्यूनतम रेटिंग',
    browse_filter_experience: 'न्यूनतम अनुभव',
    browse_filter_language: 'भाषा',
    browse_filter_verified: 'केवल सत्यापित',
    browse_filter_today: 'आज उपलब्ध',
    browse_filter_emergency: 'आपातकालीन SOS',
    browse_filter_reset: 'रीसेट',
    browse_book: 'अभी बुक करें ⚡',
    browse_cat_all: 'सभी',
    book_step_date: 'तारीख',
    book_step_time: 'समय',
    book_step_details: 'विवरण',
    book_step_review: 'समीक्षा',
    book_step_payment: 'भुगतान',
    book_choose_date: 'तारीख चुनें',
    book_choose_time: 'समय स्लॉट चुनें',
    book_slots_for: 'स्लॉट दिखाए जा रहे हैं',
    book_booked: 'बुक्ड',
    book_job_title: 'काम का नाम',
    book_job_desc: 'समस्या का विवरण',
    book_address: 'पूरा पता',
    book_upload: 'समस्या की फ़ोटो अपलोड करें (वैकल्पिक)',
    book_upload_hint: 'खींचें और छोड़ें या क्लिक करें',
    book_review_heading: 'बुकिंग की समीक्षा करें',
    book_hero: 'हीरो',
    book_service: 'सेवा',
    book_date: 'तारीख',
    book_time: 'समय',
    book_job: 'काम',
    book_address_label: 'पता',
    book_service_fee: 'सेवा शुल्क',
    book_platform_fee: 'प्लेटफॉर्म शुल्क',
    book_total: 'कुल',
    book_escrow: 'आपका भुगतान एस्क्रो में सुरक्षित है और काम पूरा होने पर ही जारी होगा।',
    book_pay_secure: 'सुरक्षित भुगतान',
    book_card_number: 'कार्ड नंबर',
    book_expiry: 'वैधता',
    book_cvv: 'CVV',
    book_name_card: 'कार्ड पर नाम',
    book_ssl: '256-बिट SSL एन्क्रिप्टेड · Stripe द्वारा',
    book_pay_btn: 'भुगतान करें',
    book_securely: '🔒',
    book_continue: 'जारी रखें',
    book_back: 'वापस',
    book_cancel: 'रद्द करें',
    book_processing: 'प्रोसेसिंग...',
    book_confirmed_title: 'बुकिंग पुष्टि! 🎉',
    book_confirmed_sub: 'आपका हीरो रास्ते में है!',
    book_view_status: 'काम की स्थिति देखें →',
    book_close: 'बंद करें',
    footer_tagline: 'आपका भरोसेमंद पड़ोस सेवा प्लेटफॉर्म।',
    footer_services: 'सेवाएं',
    footer_company: 'कंपनी',
    footer_legal: 'कानूनी',
    footer_about: 'हमारे बारे में',
    footer_careers: 'करियर',
    footer_blog: 'ब्लॉग',
    footer_press: 'प्रेस',
    footer_privacy: 'गोपनीयता नीति',
    footer_terms: 'सेवा की शर्तें',
    footer_refund: 'धनवापसी नीति',
    footer_rights: 'सर्वाधिकार सुरक्षित।',
    dash_welcome: 'वापस स्वागत',
    dash_active_jobs: 'सक्रिय काम',
    dash_total_spent: 'कुल खर्च',
    dash_total_earned: 'कुल कमाई',
    dash_rating: 'रेटिंग',
    dash_completed: 'पूर्ण',
    dash_pending: 'लंबित',
    dash_accepted: 'स्वीकृत',
    general_loading: 'लोड हो रहा है...',
    general_see_all: 'सभी देखें',
    general_close: 'बंद करें',
    general_save: 'सहेजें',
    general_cancel: 'रद्द करें',
    general_confirm: 'पुष्टि करें',
    general_hrs: 'घंटे',
    general_per_hr: '/घंटा',
    general_jobs: 'काम',
    general_yrs: 'साल',
    general_today: 'आज',
    general_tomorrow: 'कल',
  },

  // ─── MARATHI (short version — key strings) ────────────────────────────────
  mr: {
    nav_find: 'मदतनीस शोधा',
    nav_how: 'कसे काम करते',
    nav_signin: 'साइन इन',
    nav_notifications: 'सूचना',
    nav_language: 'भाषा',
    nav_dark: 'डार्क',
    nav_light: 'लाइट',
    nav_dashboard: 'माझा डॅशबोर्ड',
    nav_signout: 'साइन आउट',
    nav_mark_all_read: 'सर्व वाचले',
    nav_view_all: 'सर्व सूचना पाहा →',
    notif_1_title: 'बुकिंग स्वीकारली! 🎉', notif_1_body: 'राजेश कुमारने तुमची विनंती स्वीकारली.',
    notif_2_title: 'पेमेंट यशस्वी ✅', notif_2_body: '₹500 एस्क्रोद्वारे भरले.',
    notif_3_title: 'कामगार येत आहे 🚗', notif_3_body: 'सुनीता शर्मा 10 मिनिटांत येईल.',
    notif_4_title: 'काम पूर्ण 🛠️', notif_4_body: 'किचन सिंक दुरुस्ती पूर्ण.',
    notif_5_title: 'अनुभव रेट करा ⭐', notif_5_body: 'अजय पटेल कसे होते? रिव्यू द्या.',
    hero_badge: '🏠 50,000+ घरमालकांचा विश्वास',
    hero_title_1: 'तुमच्या परिसरातील',
    hero_title_2: 'फिक्स-इट हिरो',
    hero_title_3: 'एका टॅपवर आहेत',
    hero_sub: 'प्लंबर, इलेक्ट्रिशियन, पेंटर आणि अधिक बुक करा.',
    hero_search_placeholder: 'काय दुरुस्त करायचे? उदा. AC थंड नाही...',
    hero_search_btn: 'हिरो शोधा 🔍',
    hero_or: 'किंवा श्रेणीनुसार ब्राउझ करा',
    hero_stat_1: '50K+ घरमालक', hero_stat_2: '2,000+ हिरो', hero_stat_3: '4.9★ रेटिंग',
    categories_title: 'आज काय दुरुस्त करायचे?',
    categories_sub: 'श्रेणी निवडा आणि आम्ही जवळचे हिरो शोधू.',
    cat_plumber: 'प्लंबर', cat_electrician: 'इलेक्ट्रिशियन', cat_carpenter: 'सुतार',
    cat_ac: 'AC तंत्रज्ञ', cat_painter: 'रंगारी', cat_cleaner: 'स्वच्छता',
    cat_mechanic: 'मेकॅनिक', cat_gardener: 'माळी',
    how_title: '⭐ HelperHub कसे काम करते',
    how_sub: '5 सोप्या टप्प्यात सेवा',
    how_step1_title: 'सेवा शोधा 🔍', how_step1_desc: 'तुमची गरज टाइप करा.',
    how_step2_title: 'व्यावसायिक बुक करा 🤝', how_step2_desc: 'टॉप-रेटेड हिरो निवडा.',
    how_step3_title: 'सुरक्षित पेमेंट 🔒', how_step3_desc: 'पैसे एस्क्रोत सुरक्षित.',
    how_step4_title: 'काम पूर्ण 🛠️', how_step4_desc: 'हिरो घरी येऊन काम करतो.',
    how_step5_title: 'अनुभव रेट करा ⭐', how_step5_desc: 'रिव्यू द्या आणि पेमेंट मिळवा.',
    top_title: '⭐ तुमच्या जवळचे टॉप प्रोफेशनल', top_sub: 'सत्यापित, 4.8+ रेटिंग हिरो',
    top_view_all: 'सर्व मदतनीस पाहा →',
    recent_title: '⚡ नुकतेच पूर्ण झालेले काम', recent_sub: 'तुमच्या शहरात सुरू',
    testimonials_title: '❤️ घरमालक काय म्हणतात', testimonials_sub: 'शेजाऱ्यांच्या खऱ्या कथा',
    why_title: '🌟 HelperHub का निवडा?', why_sub: 'आम्ही फक्त बुकिंग ॲप नाही.',
    why_1_title: 'सत्यापित व्यावसायिक', why_1_desc: 'प्रत्येक मदतनीस आधार-सत्यापित.',
    why_2_title: 'सुरक्षित एस्क्रो पेमेंट', why_2_desc: 'काम पूर्ण झाल्यावरच पैसे जातात.',
    why_3_title: 'AI किंमत अंदाज', why_3_desc: 'बुकिंगपूर्वी किंमत जाणून घ्या.',
    why_4_title: 'आपत्कालीन बुकिंग', why_4_desc: '24/7 उपलब्ध हिरो.',
    why_calc_title: '🤖 AI किंमत कॅल्क्युलेटर', why_calc_sub: 'त्वरित अंदाज',
    why_calc_category: 'सेवा', why_calc_hours: 'तास', why_calc_estimate: 'अंदाजित खर्च',
    why_calc_note: 'चेकआउटवर ₹50 प्लॅटफॉर्म शुल्क',
    app_badge: '📱 लवकरच येणार', app_title: 'HelperHub तुमच्या खिशात',
    app_sub: 'फोनवरून मदतनीस बुक करा.', app_ios: '🍎 App Store', app_android: '🤖 Google Play',
    cta_hire_title: 'तुमचा फिक्स-इट हिरो शोधायला तयार?',
    cta_hire_sub: '50,000+ घरमालक HelperHub वर विश्वास ठेवतात.',
    cta_hire_btn: 'आता हिरो बुक करा 🚀',
    cta_work_title: 'तुम्ही कुशल व्यावसायिक आहात का?',
    cta_work_sub: 'मदतनीस म्हणून सामील व्हा आणि कमाई सुरू करा!',
    cta_work_btn: 'मदतनीस म्हणून सामील व्हा ⚡',
    auth_welcome: 'परत स्वागत! 👋', auth_join: 'आज HelperHub मध्ये सामील व्हा! 🎉',
    auth_create_free: 'मोफत खाते तयार करा', auth_sign_in_to: 'डॅशबोर्डसाठी साइन इन',
    auth_tab_signin: 'साइन इन', auth_tab_create: 'खाते तयार करा',
    auth_joining_as: 'मी म्हणून सामील होत आहे...',
    auth_role_hire: 'मला मदत हवी आहे 🏠', auth_role_hire_desc: 'घर दुरुस्तीसाठी मदतनीस बुक करा',
    auth_role_work: 'मला काम करायचे आहे 🛠️', auth_role_work_desc: 'तुमच्या कौशल्याने मदत करा',
    auth_full_name: 'पूर्ण नाव', auth_email: 'ईमेल पत्ता', auth_password: 'पासवर्ड',
    auth_create_btn: 'खाते तयार करा 🎉', auth_signin_btn: 'साइन इन 🚀',
    auth_loading: 'कृपया प्रतीक्षा करा...', auth_demo: 'डेमो खाती:',
    otp_title: 'ईमेल सत्यापित करा', otp_sent: '6-अंकी कोड पाठवला',
    otp_verify_btn: 'सत्यापित करा! 🎉', otp_verifying: 'सत्यापित होत आहे...', otp_back: 'मागे',
    browse_location: '📍 दिल्ली', browse_search: 'प्लंबर, इलेक्ट्रिशियन शोधा...',
    browse_filters: 'फिल्टर', browse_results: 'मदतनीस जवळ सापडले',
    browse_no_results: 'मदतनीस सापडले नाहीत.', browse_filter_price: 'कमाल किंमत',
    browse_filter_distance: 'अंतर', browse_filter_rating: 'किमान रेटिंग',
    browse_filter_experience: 'किमान अनुभव', browse_filter_language: 'भाषा',
    browse_filter_verified: 'फक्त सत्यापित', browse_filter_today: 'आज उपलब्ध',
    browse_filter_emergency: 'आपत्कालीन SOS', browse_filter_reset: 'रीसेट',
    browse_book: 'आता बुक करा ⚡', browse_cat_all: 'सर्व',
    book_step_date: 'तारीख', book_step_time: 'वेळ', book_step_details: 'तपशील',
    book_step_review: 'आढावा', book_step_payment: 'पेमेंट',
    book_choose_date: 'तारीख निवडा', book_choose_time: 'वेळ स्लॉट निवडा',
    book_slots_for: 'स्लॉट दाखवत आहे', book_booked: 'बुक्ड',
    book_job_title: 'कामाचे नाव', book_job_desc: 'समस्येचे वर्णन',
    book_address: 'पूर्ण पत्ता', book_upload: 'फोटो अपलोड करा (पर्यायी)',
    book_upload_hint: 'ड्रॅग करा किंवा क्लिक करा', book_review_heading: 'बुकिंगचा आढावा',
    book_hero: 'हिरो', book_service: 'सेवा', book_date: 'तारीख', book_time: 'वेळ',
    book_job: 'काम', book_address_label: 'पत्ता', book_service_fee: 'सेवा शुल्क',
    book_platform_fee: 'प्लॅटफॉर्म शुल्क', book_total: 'एकूण',
    book_escrow: 'तुमचे पेमेंट एस्क्रोत सुरक्षित आहे.',
    book_pay_secure: 'सुरक्षित पेमेंट', book_card_number: 'कार्ड नंबर',
    book_expiry: 'वैधता', book_cvv: 'CVV', book_name_card: 'कार्डवरील नाव',
    book_ssl: '256-बिट SSL · Stripe', book_pay_btn: 'पेमेंट करा', book_securely: '🔒',
    book_continue: 'पुढे', book_back: 'मागे', book_cancel: 'रद्द करा',
    book_processing: 'प्रक्रिया सुरू...', book_confirmed_title: 'बुकिंग पुष्टी! 🎉',
    book_confirmed_sub: 'तुमचा हिरो रस्त्यावर आहे!', book_view_status: 'स्थिती पाहा →',
    book_close: 'बंद करा',
    footer_tagline: 'तुमचा विश्वासू परिसर सेवा प्लॅटफॉर्म.',
    footer_services: 'सेवा', footer_company: 'कंपनी', footer_legal: 'कायदेशीर',
    footer_about: 'आमच्याबद्दल', footer_careers: 'करिअर', footer_blog: 'ब्लॉग',
    footer_press: 'प्रेस', footer_privacy: 'गोपनीयता धोरण',
    footer_terms: 'सेवा अटी', footer_refund: 'परतावा धोरण', footer_rights: 'सर्व हक्क राखीव.',
    dash_welcome: 'परत स्वागत', dash_active_jobs: 'सक्रिय काम', dash_total_spent: 'एकूण खर्च',
    dash_total_earned: 'एकूण कमाई', dash_rating: 'रेटिंग', dash_completed: 'पूर्ण',
    dash_pending: 'प्रलंबित', dash_accepted: 'स्वीकारले',
    general_loading: 'लोड होत आहे...', general_see_all: 'सर्व पाहा', general_close: 'बंद करा',
    general_save: 'जतन करा', general_cancel: 'रद्द करा', general_confirm: 'पुष्टी करा',
    general_hrs: 'तास', general_per_hr: '/तास', general_jobs: 'काम', general_yrs: 'वर्षे',
    general_today: 'आज', general_tomorrow: 'उद्या',
  },

  // ─── MALAYALAM ────────────────────────────────────────────────────────────
  ml: {
    nav_find: 'സഹായി കണ്ടെത്തുക', nav_how: 'എങ്ങനെ പ്രവർത്തിക്കുന്നു', nav_signin: 'സൈൻ ഇൻ',
    nav_notifications: 'അറിയിപ്പുകൾ', nav_language: 'ഭാഷ', nav_dark: 'ഡാർക്ക്', nav_light: 'ലൈറ്റ്',
    nav_dashboard: 'എന്റെ ഡാഷ്‌ബോർഡ്', nav_signout: 'സൈൻ ഔട്ട്',
    nav_mark_all_read: 'എല്ലാം വായിച്ചു', nav_view_all: 'എല്ലാ അറിയിപ്പുകളും →',
    notif_1_title: 'ബുക്കിംഗ് സ്വീകരിച്ചു! 🎉', notif_1_body: 'രാജേഷ് കുമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു.',
    notif_2_title: 'പേയ്‌മെന്റ് വിജയകരം ✅', notif_2_body: '₹500 എസ്‌ക്രോ വഴി നൽകി.',
    notif_3_title: 'തൊഴിലാളി വരുന്നു 🚗', notif_3_body: 'സുനിത ശർമ്മ 10 മിനിറ്റ് അകലെ.',
    notif_4_title: 'ജോലി പൂർത്തിയായി 🛠️', notif_4_body: 'അടുക്കള സിംക്ക് നന്നാക്കൽ പൂർത്തി.',
    notif_5_title: 'അനുഭവം റേറ്റ് ചെയ്യൂ ⭐', notif_5_body: 'അജയ് പട്ടേൽ എങ്ങനെയുണ്ടായിരുന്നു?',
    hero_badge: '🏠 50,000+ വീടുടമകൾ വിശ്വസിക്കുന്നു',
    hero_title_1: 'നിങ്ങളുടെ നാടിന്റെ',
    hero_title_2: 'ഫിക്സ്-ഇറ്റ് ഹീറോകൾ',
    hero_title_3: 'ഒരു ടാപ്പ് അകലെ',
    hero_sub: 'പ്ലംബർ, ഇലക്ട്രീഷ്യൻ, പെയിന്ററെ ബുക്ക് ചെയ്യൂ.',
    hero_search_placeholder: 'എന്ത് ശരിയാക്കണം?',
    hero_search_btn: 'ഹീറോ കണ്ടെത്തുക 🔍',
    hero_or: 'അല്ലെങ്കിൽ വിഭാഗം തിരഞ്ഞെടുക്കൂ',
    hero_stat_1: '50K+ വീടുടമകൾ', hero_stat_2: '2,000+ ഹീറോകൾ', hero_stat_3: '4.9★ റേറ്റിംഗ്',
    categories_title: 'ഇന്ന് എന്ത് ശരിയാക്കണം?',
    categories_sub: 'ഒരു വിഭാഗം തിരഞ്ഞെടുക്കൂ.',
    cat_plumber: 'പ്ലംബർ', cat_electrician: 'ഇലക്ട്രീഷ്യൻ', cat_carpenter: 'ആശാരി',
    cat_ac: 'AC ടെക്നീഷ്യൻ', cat_painter: 'പെയിന്റർ', cat_cleaner: 'ക്ലീനർ',
    cat_mechanic: 'മെക്കാനിക്', cat_gardener: 'ഗാർഡനർ',
    how_title: '⭐ HelperHub എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    how_sub: '5 ലളിതമായ ഘട്ടങ്ങൾ',
    how_step1_title: 'സേവനം തിരഞ്ഞെടുക്കൂ 🔍', how_step1_desc: 'നിങ്ങളുടെ ആവശ്യം ടൈപ്പ് ചെയ്യൂ.',
    how_step2_title: 'പ്രൊഫഷണലിനെ ബുക്ക് ചെയ്യൂ 🤝', how_step2_desc: 'ടോപ്-റേറ്റഡ് ഹീറോ തിരഞ്ഞെടുക്കൂ.',
    how_step3_title: 'സുരക്ഷിത പേയ്‌മെന്റ് 🔒', how_step3_desc: 'ജോലി തീരുന്നതുവരെ പണം എസ്‌ക്രോയിൽ.',
    how_step4_title: 'ജോലി പൂർത്തി 🛠️', how_step4_desc: 'ഹീറോ നിങ്ങളുടെ വീട്ടിൽ വന്ന് ജോലി ചെയ്യും.',
    how_step5_title: 'അനുഭവം റേറ്റ് ചെയ്യൂ ⭐', how_step5_desc: 'റിവ്യൂ ഇടൂ, പേയ്‌മെന്റ് ലഭിക്കൂ.',
    top_title: '⭐ നിങ്ങൾക്ക് അടുത്ത് ടോപ് പ്രൊഫഷണലുകൾ', top_sub: 'സത്യസന്ധർ, 4.8+ റേറ്റിംഗ്',
    top_view_all: 'എല്ലാ ഹെൽപ്പർമാരെയും കാണൂ →',
    recent_title: '⚡ ഇടയ്ക്കിടെ പൂർത്തിയായ ജോലികൾ', recent_sub: 'നിങ്ങളുടെ നഗരത്തിൽ',
    testimonials_title: '❤️ വീടുടമകൾ പറയുന്നത്', testimonials_sub: 'അയൽക്കാരുടെ യഥാർത്ഥ കഥകൾ',
    why_title: '🌟 HelperHub എന്തുകൊണ്ട്?', why_sub: 'ഞങ്ങൾ ഒരു ബുക്കിംഗ് ആപ്പ് മാത്രമല്ല.',
    why_1_title: 'സത്യസന്ധ പ്രൊഫഷണലുകൾ', why_1_desc: 'ആധാർ-പരിശോധിത.',
    why_2_title: 'സുരക്ഷിത പേയ്‌മെന്റ്', why_2_desc: 'ജോലി തീർന്നതിന് ശേഷം.',
    why_3_title: 'AI വില കണക്ക്', why_3_desc: 'ബുക്ക് ചെയ്യുന്നതിന് മുൻപ് വില അറിയൂ.',
    why_4_title: 'അടിയന്തര ബുക്കിംഗ്', why_4_desc: '24/7 ഹീറോകൾ ലഭ്യം.',
    why_calc_title: '🤖 AI വില കാൽക്കുലേറ്റർ', why_calc_sub: 'ഉടനടി കണക്ക്',
    why_calc_category: 'സേവനം', why_calc_hours: 'മണിക്കൂർ', why_calc_estimate: 'കണക്കിട്ട ചെലവ്',
    why_calc_note: 'ചെക്കൗട്ടിൽ ₹50 പ്ലാറ്റ്ഫോം ഫീ',
    app_badge: '📱 ഉടൻ വരുന്നു', app_title: 'HelperHub നിങ്ങളുടെ കൈകളിൽ',
    app_sub: 'ഫോണിൽ നിന്ന് ബുക്ക് ചെയ്യൂ.', app_ios: '🍎 App Store', app_android: '🤖 Google Play',
    cta_hire_title: 'ഹീറോ കണ്ടെത്താൻ തയ്യാറോ?',
    cta_hire_sub: '50,000+ വീടുടമകൾ HelperHub-ൽ വിശ്വസിക്കുന്നു.',
    cta_hire_btn: 'ഇപ്പോൾ ഹീറോ ബുക്ക് ചെയ്യൂ 🚀',
    cta_work_title: 'നിങ്ങൾ ഒരു നൈപുണ്യ വ്യക്തിയാണോ?',
    cta_work_sub: 'ഹെൽപ്പർ ആയി ചേർന്ന് ഇന്ന് മുതൽ സമ്പാദിക്കൂ!',
    cta_work_btn: 'ഹെൽപ്പർ ആയി ചേരൂ ⚡',
    auth_welcome: 'തിരിച്ചു സ്വാഗതം! 👋', auth_join: 'HelperHub-ൽ ചേരൂ! 🎉',
    auth_create_free: 'സൗജന്യ അക്കൗണ്ട് ഉണ്ടാക്കൂ', auth_sign_in_to: 'ഡാഷ്‌ബോർഡ് ആക്‌സസ് ചെയ്യൂ',
    auth_tab_signin: 'സൈൻ ഇൻ', auth_tab_create: 'അക്കൗണ്ട് ഉണ്ടാക്കൂ',
    auth_joining_as: 'ഞാൻ ചേരുന്നത്...', auth_role_hire: 'എനിക്ക് സഹായം വേണം 🏠',
    auth_role_hire_desc: 'വീട് നന്നാക്കാൻ ഹെൽപ്പർ ബുക്ക് ചെയ്യൂ',
    auth_role_work: 'ഞാൻ ജോലി ചെയ്യും 🛠️', auth_role_work_desc: 'കഴിവ് ഉപയോഗിച്ച് സഹായിക്കൂ',
    auth_full_name: 'മുഴുവൻ പേര്', auth_email: 'ഇ-മെയിൽ', auth_password: 'പാസ്‌വേഡ്',
    auth_create_btn: 'അക്കൗണ്ട് ഉണ്ടാക്കൂ 🎉', auth_signin_btn: 'സൈൻ ഇൻ 🚀',
    auth_loading: 'കാത്തിരിക്കൂ...', auth_demo: 'ഡെമോ അക്കൗണ്ട്:',
    otp_title: 'ഇ-മെയിൽ സ്ഥിരീകരിക്കൂ', otp_sent: '6 അക്ക കോഡ് അയച്ചു',
    otp_verify_btn: 'സ്ഥിരീകരിക്കൂ! 🎉', otp_verifying: 'സ്ഥിരീകരിക്കുന്നു...', otp_back: 'പോകൂ',
    browse_location: '📍 ഡൽഹി', browse_search: 'പ്ലംബർ, ഇലക്ട്രീഷ്യൻ...',
    browse_filters: 'ഫിൽട്ടർ', browse_results: 'ഹെൽപ്പർ കണ്ടെത്തി',
    browse_no_results: 'ഹെൽപ്പർ കണ്ടെത്തിയില്ല.', browse_filter_price: 'പരമാവധി വില',
    browse_filter_distance: 'ദൂരം', browse_filter_rating: 'കുറഞ്ഞ റേറ്റിംഗ്',
    browse_filter_experience: 'കുറഞ്ഞ അനുഭവം', browse_filter_language: 'ഭാഷ',
    browse_filter_verified: 'സ്ഥിരീകരിച്ചവർ', browse_filter_today: 'ഇന്ന് ലഭ്യം',
    browse_filter_emergency: 'അടിയന്തര SOS', browse_filter_reset: 'റീസെറ്റ്',
    browse_book: 'ഇപ്പോൾ ബുക്ക് ⚡', browse_cat_all: 'എല്ലാം',
    book_step_date: 'തീയതി', book_step_time: 'സമയം', book_step_details: 'വിവരം',
    book_step_review: 'അവലോകനം', book_step_payment: 'പേയ്‌മെന്റ്',
    book_choose_date: 'തീയതി തിരഞ്ഞെടുക്കൂ', book_choose_time: 'സമയ സ്ലോട്ട് തിരഞ്ഞെടുക്കൂ',
    book_slots_for: 'സ്ലോട്ട് കാണിക്കുന്നു', book_booked: 'ബുക്ക്ഡ്',
    book_job_title: 'ജോലി പേര്', book_job_desc: 'പ്രശ്നം വിവരിക്കൂ',
    book_address: 'പൂർണ്ണ വിലാസം', book_upload: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യൂ (ഐച്ഛികം)',
    book_upload_hint: 'ഡ്രാഗ് ചെയ്യൂ അല്ലെങ്കിൽ ക്ലിക്ക് ചെയ്യൂ',
    book_review_heading: 'ബുക്കിംഗ് അവലോകനം',
    book_hero: 'ഹീറോ', book_service: 'സേവനം', book_date: 'തീയതി', book_time: 'സമയം',
    book_job: 'ജോലി', book_address_label: 'വിലാസം', book_service_fee: 'സേവന ഫീ',
    book_platform_fee: 'പ്ലാറ്റ്ഫോം ഫീ', book_total: 'ആകെ',
    book_escrow: 'പണം എസ്‌ക്രോയിൽ സുരക്ഷിതം.',
    book_pay_secure: 'സുരക്ഷിത പേയ്‌മെന്റ്', book_card_number: 'കാർഡ് നമ്പർ',
    book_expiry: 'കാലഹരണം', book_cvv: 'CVV', book_name_card: 'കാർഡിലെ പേര്',
    book_ssl: '256-ബിറ്റ് SSL · Stripe', book_pay_btn: 'പണം നൽകൂ', book_securely: '🔒',
    book_continue: 'തുടരൂ', book_back: 'പോകൂ', book_cancel: 'റദ്ദ് ചെയ്യൂ',
    book_processing: 'പ്രോസസ്സ് ചെയ്യുന്നു...', book_confirmed_title: 'ബുക്കിംഗ് സ്ഥിരീകരിച്ചു! 🎉',
    book_confirmed_sub: 'ഹീറോ വഴിയിൽ!', book_view_status: 'സ്ഥിതി കാണൂ →',
    book_close: 'അടയ്ക്കൂ',
    footer_tagline: 'വിശ്വസ്ത അയൽ സേവന പ്ലാറ്റ്ഫോം.',
    footer_services: 'സേവനങ്ങൾ', footer_company: 'കമ്പനി', footer_legal: 'നിയമം',
    footer_about: 'ഞങ്ങളെ കുറിച്ച്', footer_careers: 'ജോലി', footer_blog: 'ബ്ലോഗ്',
    footer_press: 'പ്രസ്', footer_privacy: 'സ്വകാര്യത നയം',
    footer_terms: 'ഉപയോഗ നിബന്ധനകൾ', footer_refund: 'റീഫണ്ട് നയം',
    footer_rights: 'എല്ലാ അവകാശങ്ങളും.',
    dash_welcome: 'തിരിച്ചു സ്വാഗതം', dash_active_jobs: 'സജീവ ജോലികൾ',
    dash_total_spent: 'ആകെ ചെലവ്', dash_total_earned: 'ആകെ സമ്പാദ്യം',
    dash_rating: 'റേറ്റിംഗ്', dash_completed: 'പൂർത്തി', dash_pending: 'കാത്തിരിക്കൂ',
    dash_accepted: 'സ്വീകരിച്ചു',
    general_loading: 'ലോഡ് ചെയ്യുന്നു...', general_see_all: 'എല്ലാം കാണൂ',
    general_close: 'അടയ്ക്കൂ', general_save: 'സേവ്', general_cancel: 'റദ്ദ്',
    general_confirm: 'സ്ഥിരീകരിക്കൂ', general_hrs: 'മണിക്കൂർ', general_per_hr: '/മണിക്കൂർ',
    general_jobs: 'ജോലികൾ', general_yrs: 'വർഷം', general_today: 'ഇന്ന്', general_tomorrow: 'നാളെ',
  },

  // ─── TELUGU ───────────────────────────────────────────────────────────────
  te: {
    nav_find: 'సహాయకుడిని కనుగొనండి', nav_how: 'ఎలా పని చేస్తుంది', nav_signin: 'సైన్ ఇన్',
    nav_notifications: 'నోటిఫికేషన్లు', nav_language: 'భాష', nav_dark: 'డార్క్', nav_light: 'లైట్',
    nav_dashboard: 'నా డాష్‌బోర్డ్', nav_signout: 'సైన్ అవుట్',
    nav_mark_all_read: 'అన్నీ చదివాను', nav_view_all: 'అన్ని నోటిఫికేషన్లు →',
    notif_1_title: 'బుకింగ్ అంగీకరించారు! 🎉', notif_1_body: 'రాజేశ్ కుమార్ మీ అభ్యర్థనను అంగీకరించారు.',
    notif_2_title: 'పేమెంట్ విజయవంతమైంది ✅', notif_2_body: '₹500 ఎస్క్రో ద్వారా చెల్లించారు.',
    notif_3_title: 'కార్మికుడు వస్తున్నారు 🚗', notif_3_body: 'సునీత శర్మ 10 నిమిషాల్లో వస్తారు.',
    notif_4_title: 'పని పూర్తయింది 🛠️', notif_4_body: 'కిచెన్ సింక్ రిపేర్ పూర్తి.',
    notif_5_title: 'అనుభవాన్ని రేట్ చేయండి ⭐', notif_5_body: 'అజయ్ పటేల్ ఎలా ఉన్నారు?',
    hero_badge: '🏠 50,000+ ఇల్లు యజమానులు నమ్ముతున్నారు',
    hero_title_1: 'మీ పరిసరాల', hero_title_2: 'ఫిక్స్-ఇట్ హీరోలు', hero_title_3: 'ఒక్క టాప్‌లో',
    hero_sub: 'ప్లంబర్, ఎలక్ట్రీషియన్, పెయింటర్ మరియు మరిన్నింటిని బుక్ చేయండి.',
    hero_search_placeholder: 'ఏమి రిపేర్ చేయాలి?',
    hero_search_btn: 'హీరోను కనుగొనండి 🔍',
    hero_or: 'లేదా వర్గం ద్వారా బ్రౌజ్ చేయండి',
    hero_stat_1: '50K+ ఇల్లు యజమానులు', hero_stat_2: '2,000+ హీరోలు', hero_stat_3: '4.9★ రేటింగ్',
    categories_title: 'ఈ రోజు ఏమి రిపేర్ చేయాలి?', categories_sub: 'వర్గం ఎంచుకోండి.',
    cat_plumber: 'ప్లంబర్', cat_electrician: 'ఎలక్ట్రీషియన్', cat_carpenter: 'వడ్రంగి',
    cat_ac: 'AC టెక్నీషియన్', cat_painter: 'పెయింటర్', cat_cleaner: 'క్లీనర్',
    cat_mechanic: 'మెకానిక్', cat_gardener: 'తోటమాలి',
    how_title: '⭐ HelperHub ఎలా పని చేస్తుంది', how_sub: '5 సులభమైన దశలు',
    how_step1_title: 'సేవ వెతకండి 🔍', how_step1_desc: 'మీ అవసరాన్ని టైప్ చేయండి.',
    how_step2_title: 'నిపుణుడిని బుక్ చేయండి 🤝', how_step2_desc: 'టాప్-రేటెడ్ హీరోని ఎంచుకోండి.',
    how_step3_title: 'సురక్షిత పేమెంట్ 🔒', how_step3_desc: 'పని పూర్తయ్యే వరకు నగదు ఎస్క్రోలో.',
    how_step4_title: 'పని పూర్తి 🛠️', how_step4_desc: 'హీరో మీ ఇంటికి వచ్చి పని చేస్తారు.',
    how_step5_title: 'అనుభవాన్ని రేట్ చేయండి ⭐', how_step5_desc: 'రివ్యూ ఇవ్వండి, పేమెంట్ పంపండి.',
    top_title: '⭐ మీ దగ్గరి టాప్ నిపుణులు', top_sub: 'ధృవీకరించబడిన, 4.8+ రేటింగ్',
    top_view_all: 'అందరు సహాయకులను చూడండి →',
    recent_title: '⚡ ఇటీవల పూర్తయిన పనులు', recent_sub: 'మీ నగరంలో జరిగేది',
    testimonials_title: '❤️ ఇల్లు యజమానులు ఏమి చెప్తున్నారు', testimonials_sub: 'పొరుగువారి నిజమైన కథలు',
    why_title: '🌟 HelperHub ఎందుకు ఎంచుకోవాలి?', why_sub: 'మేము కేవలం బుకింగ్ యాప్ కాదు.',
    why_1_title: 'ధృవీకరించబడిన నిపుణులు', why_1_desc: 'ఆధార్ ధృవీకరించబడింది.',
    why_2_title: 'సురక్షిత ఎస్క్రో పేమెంట్', why_2_desc: 'పని తర్వాత మాత్రమే పేమెంట్.',
    why_3_title: 'AI ధర అంచనా', why_3_desc: 'బుక్ చేయడానికి ముందు ధర తెలుసుకోండి.',
    why_4_title: 'అత్యవసర బుకింగ్', why_4_desc: '24/7 అందుబాటులో ఉన్న హీరోలు.',
    why_calc_title: '🤖 AI ధర కాలిక్యులేటర్', why_calc_sub: 'తక్షణ అంచనా',
    why_calc_category: 'సేవ', why_calc_hours: 'గంటలు', why_calc_estimate: 'అంచనా వ్యయం',
    why_calc_note: 'చెకవుట్‌లో ₹50 ప్లాట్‌ఫారం రుసుము',
    app_badge: '📱 త్వరలో రానుంది', app_title: 'HelperHub మీ జేబులో',
    app_sub: 'ఫోన్ నుండి హెల్పర్ బుక్ చేయండి.', app_ios: '🍎 App Store', app_android: '🤖 Google Play',
    cta_hire_title: 'మీ ఫిక్స్-ఇట్ హీరోని కనుగొనడానికి సిద్ధంగా ఉన్నారా?',
    cta_hire_sub: '50,000+ ఇల్లు యజమానులు HelperHub ని నమ్ముతున్నారు.',
    cta_hire_btn: 'ఇప్పుడే హీరోని బుక్ చేయండి 🚀',
    cta_work_title: 'మీరు నైపుణ్యం గల నిపుణుడా?', cta_work_sub: 'హెల్పర్‌గా చేరండి!',
    cta_work_btn: 'హెల్పర్‌గా చేరండి ⚡',
    auth_welcome: 'తిరిగి స్వాగతం! 👋', auth_join: 'HelperHub లో చేరండి! 🎉',
    auth_create_free: 'ఉచిత ఖాతా సృష్టించండి', auth_sign_in_to: 'డాష్‌బోర్డ్ యాక్సెస్',
    auth_tab_signin: 'సైన్ ఇన్', auth_tab_create: 'ఖాతా సృష్టించండి',
    auth_joining_as: 'నేను చేరుతున్నాను...', auth_role_hire: 'నాకు సహాయం కావాలి 🏠',
    auth_role_hire_desc: 'ఇంటి మరమ్మతులకు హెల్పర్ బుక్ చేయండి',
    auth_role_work: 'నేను పని చేస్తాను 🛠️', auth_role_work_desc: 'మీ నైపుణ్యంతో సహాయపడండి',
    auth_full_name: 'పూర్తి పేరు', auth_email: 'ఇమెయిల్', auth_password: 'పాస్‌వర్డ్',
    auth_create_btn: 'ఖాతా సృష్టించండి 🎉', auth_signin_btn: 'సైన్ ఇన్ 🚀',
    auth_loading: 'దయచేసి వేచి ఉండండి...', auth_demo: 'డెమో ఖాతాలు:',
    otp_title: 'ఇమెయిల్ ధృవీకరించండి', otp_sent: '6 అంకెల కోడ్ పంపబడింది',
    otp_verify_btn: 'ధృవీకరించండి! 🎉', otp_verifying: 'ధృవీకరిస్తున్నారు...', otp_back: 'వెనుకకు',
    browse_location: '📍 ఢిల్లీ', browse_search: 'ప్లంబర్, ఎలక్ట్రీషియన్...',
    browse_filters: 'ఫిల్టర్లు', browse_results: 'హెల్పర్లు దొరికారు',
    browse_no_results: 'హెల్పర్లు కనుగొనబడలేదు.', browse_filter_price: 'గరిష్ఠ ధర',
    browse_filter_distance: 'దూరం', browse_filter_rating: 'కనీస రేటింగ్',
    browse_filter_experience: 'కనీస అనుభవం', browse_filter_language: 'భాష',
    browse_filter_verified: 'ధృవీకరించిన మాత్రమే', browse_filter_today: 'ఇవాళ అందుబాటులో',
    browse_filter_emergency: 'అత్యవసర SOS', browse_filter_reset: 'రీసెట్',
    browse_book: 'ఇప్పుడే బుక్ ⚡', browse_cat_all: 'అన్నీ',
    book_step_date: 'తేదీ', book_step_time: 'సమయం', book_step_details: 'వివరాలు',
    book_step_review: 'సమీక్ష', book_step_payment: 'పేమెంట్',
    book_choose_date: 'తేదీ ఎంచుకోండి', book_choose_time: 'సమయ స్లాట్ ఎంచుకోండి',
    book_slots_for: 'స్లాట్లు చూపిస్తోంది', book_booked: 'బుక్డ్',
    book_job_title: 'పని పేరు', book_job_desc: 'సమస్య వివరణ',
    book_address: 'పూర్తి చిరునామా', book_upload: 'ఫోటోలు అప్‌లోడ్ చేయండి (ఐచ్ఛికం)',
    book_upload_hint: 'లాగి వదలండి లేదా క్లిక్ చేయండి',
    book_review_heading: 'బుకింగ్ సమీక్ష',
    book_hero: 'హీరో', book_service: 'సేవ', book_date: 'తేదీ', book_time: 'సమయం',
    book_job: 'పని', book_address_label: 'చిరునామా', book_service_fee: 'సేవ రుసుము',
    book_platform_fee: 'ప్లాట్‌ఫారం రుసుము', book_total: 'మొత్తం',
    book_escrow: 'మీ పేమెంట్ ఎస్క్రోలో సురక్షితంగా ఉంది.',
    book_pay_secure: 'సురక్షిత పేమెంట్', book_card_number: 'కార్డ్ నంబర్',
    book_expiry: 'గడువు', book_cvv: 'CVV', book_name_card: 'కార్డ్‌పై పేరు',
    book_ssl: '256-బిట్ SSL · Stripe', book_pay_btn: 'పేమెంట్ చేయండి', book_securely: '🔒',
    book_continue: 'కొనసాగించండి', book_back: 'వెనుకకు', book_cancel: 'రద్దు చేయండి',
    book_processing: 'ప్రాసెస్ అవుతోంది...', book_confirmed_title: 'బుకింగ్ నిర్ధారించబడింది! 🎉',
    book_confirmed_sub: 'మీ హీరో దారిలో ఉన్నారు!', book_view_status: 'స్థితి చూడండి →',
    book_close: 'మూయండి',
    footer_tagline: 'విశ్వసనీయ పరిసర సేవా వేదిక.',
    footer_services: 'సేవలు', footer_company: 'కంపెనీ', footer_legal: 'చట్టపరమైన',
    footer_about: 'మా గురించి', footer_careers: 'ఉద్యోగాలు', footer_blog: 'బ్లాగ్',
    footer_press: 'ప్రెస్', footer_privacy: 'గోప్యతా విధానం',
    footer_terms: 'సేవా నిబంధనలు', footer_refund: 'రీఫండ్ విధానం',
    footer_rights: 'అన్ని హక్కులు.',
    dash_welcome: 'తిరిగి స్వాగతం', dash_active_jobs: 'యాక్టివ్ పనులు',
    dash_total_spent: 'మొత్తం ఖర్చు', dash_total_earned: 'మొత్తం ఆదాయం',
    dash_rating: 'రేటింగ్', dash_completed: 'పూర్తి', dash_pending: 'పెండింగ్',
    dash_accepted: 'అంగీకరించారు',
    general_loading: 'లోడ్ అవుతోంది...', general_see_all: 'అన్నీ చూడండి',
    general_close: 'మూయండి', general_save: 'సేవ్', general_cancel: 'రద్దు',
    general_confirm: 'నిర్ధారించండి', general_hrs: 'గంటలు', general_per_hr: '/గంట',
    general_jobs: 'పనులు', general_yrs: 'సంవత్సరాలు', general_today: 'ఈ రోజు', general_tomorrow: 'రేపు',
  },

  // ─── TAMIL ────────────────────────────────────────────────────────────────
  ta: {
    nav_find: 'உதவியாளரை கண்டுபிடி', nav_how: 'எப்படி செயல்படுகிறது', nav_signin: 'உள்நுழை',
    nav_notifications: 'அறிவிப்புகள்', nav_language: 'மொழி', nav_dark: 'இருண்டது', nav_light: 'வெளிச்சம்',
    nav_dashboard: 'என் டாஷ்போர்டு', nav_signout: 'வெளியேறு',
    nav_mark_all_read: 'அனைத்தும் படித்தது', nav_view_all: 'அனைத்து அறிவிப்புகளும் →',
    notif_1_title: 'முன்பதிவு ஏற்கப்பட்டது! 🎉', notif_1_body: 'ராஜேஷ் குமார் உங்கள் கோரிக்கையை ஏற்றுக்கொண்டார்.',
    notif_2_title: 'பணம் செலுத்தப்பட்டது ✅', notif_2_body: '₹500 எஸ்க்ரோ மூலம் செலுத்தப்பட்டது.',
    notif_3_title: 'தொழிலாளர் வருகிறார் 🚗', notif_3_body: 'சுனீதா சர்மா 10 நிமிடங்களில் வருவார்.',
    notif_4_title: 'வேலை முடிந்தது 🛠️', notif_4_body: 'சமையலறை தொட்டி பழுதுபார்ப்பு முடிந்தது.',
    notif_5_title: 'அனுபவத்தை மதிப்பீடு செய்யுங்கள் ⭐', notif_5_body: 'அஜய் பட்டேல் எப்படி இருந்தார்?',
    hero_badge: '🏠 50,000+ வீட்டு உரிமையாளர்கள் நம்புகிறார்கள்',
    hero_title_1: 'உங்கள் அக்கம்பக்கத்தின்', hero_title_2: 'ஃபிக்ஸ்-இட் ஹீரோக்கள்',
    hero_title_3: 'ஒரே தட்டில்', hero_sub: 'பிளம்பர், எலக்ட்ரீஷியன், பெயிண்டர் முன்பதிவு செய்யுங்கள்.',
    hero_search_placeholder: 'என்ன சரிசெய்ய வேண்டும்?',
    hero_search_btn: 'ஹீரோவை கண்டுபிடி 🔍',
    hero_or: 'அல்லது வகையைத் தேர்ந்தெடுங்கள்',
    hero_stat_1: '50K+ வீட்டு உரிமையாளர்கள்', hero_stat_2: '2,000+ ஹீரோக்கள்', hero_stat_3: '4.9★ மதிப்பீடு',
    categories_title: 'இன்று என்ன சரிசெய்ய வேண்டும்?', categories_sub: 'ஒரு வகையைத் தேர்ந்தெடுங்கள்.',
    cat_plumber: 'பிளம்பர்', cat_electrician: 'எலக்ட்ரீஷியன்', cat_carpenter: 'தச்சர்',
    cat_ac: 'AC தொழில்நுட்பவியலாளர்', cat_painter: 'பெயிண்டர்', cat_cleaner: 'சுத்தம் செய்பவர்',
    cat_mechanic: 'மெக்கானிக்', cat_gardener: 'தோட்டக்காரர்',
    how_title: '⭐ HelperHub எப்படி செயல்படுகிறது', how_sub: '5 எளிய படிகளில்',
    how_step1_title: 'சேவையை தேடு 🔍', how_step1_desc: 'உங்கள் தேவையை தட்டச்சு செய்யுங்கள்.',
    how_step2_title: 'நிபுணரை முன்பதிவு செய்யுங்கள் 🤝', how_step2_desc: 'சிறந்த ஹீரோவை தேர்ந்தெடுங்கள்.',
    how_step3_title: 'பாதுகாப்பான பணம் 🔒', how_step3_desc: 'வேலை முடியும் வரை பணம் எஸ்க்ரோவில்.',
    how_step4_title: 'வேலை முடிந்தது 🛠️', how_step4_desc: 'ஹீரோ உங்கள் வீட்டில் வேலை செய்வார்.',
    how_step5_title: 'அனுபவத்தை மதிப்பீடு செய்யுங்கள் ⭐', how_step5_desc: 'மதிப்பாய்வு கொடுங்கள்.',
    top_title: '⭐ உங்களுக்கு அருகில் சிறந்த நிபுணர்கள்', top_sub: 'சரிபார்க்கப்பட்டவர்கள், 4.8+',
    top_view_all: 'அனைத்து உதவியாளர்களையும் காண →',
    recent_title: '⚡ சமீபத்தில் முடிந்த வேலைகள்', recent_sub: 'உங்கள் நகரில் நடக்கிறது',
    testimonials_title: '❤️ வீட்டு உரிமையாளர்கள் என்ன சொல்கிறார்கள்', testimonials_sub: 'உண்மையான கதைகள்',
    why_title: '🌟 HelperHub ஏன் தேர்வு செய்யலாம்?', why_sub: 'நாங்கள் வெறும் முன்பதிவு ஆப்பல்ல.',
    why_1_title: 'சரிபார்க்கப்பட்ட நிபுணர்கள்', why_1_desc: 'ஆதார் சரிபார்க்கப்பட்டவர்கள்.',
    why_2_title: 'பாதுகாப்பான எஸ்க்ரோ', why_2_desc: 'வேலை முடிந்த பிறகு மட்டுமே பணம்.',
    why_3_title: 'AI விலை கணிப்பு', why_3_desc: 'முன்பதிவுக்கு முன்பே விலை தெரியும்.',
    why_4_title: 'அவசர முன்பதிவு', why_4_desc: '24/7 கிடைக்கும் ஹீரோக்கள்.',
    why_calc_title: '🤖 AI விலை கால்குலேட்டர்', why_calc_sub: 'உடனடி கணிப்பு',
    why_calc_category: 'சேவை', why_calc_hours: 'மணி நேரம்', why_calc_estimate: 'மதிப்பிட்ட செலவு',
    why_calc_note: 'செக்அவுட்டில் ₹50 தளக் கட்டணம்',
    app_badge: '📱 விரைவில் வருகிறது', app_title: 'HelperHub உங்கள் பாக்கெட்டில்',
    app_sub: 'தொலைபேசியில் உதவியாளரை முன்பதிவு செய்யுங்கள்.', app_ios: '🍎 App Store', app_android: '🤖 Google Play',
    cta_hire_title: 'உங்கள் ஹீரோவை கண்டுபிடிக்க தயாரா?',
    cta_hire_sub: '50,000+ வீட்டு உரிமையாளர்கள் HelperHub-ஐ நம்புகிறார்கள்.',
    cta_hire_btn: 'இப்போதே ஹீரோவை முன்பதிவு செய்யுங்கள் 🚀',
    cta_work_title: 'நீங்கள் திறமையான நிபுணரா?', cta_work_sub: 'உதவியாளராக சேருங்கள்!',
    cta_work_btn: 'உதவியாளராக சேரு ⚡',
    auth_welcome: 'மீண்டும் வரவேற்கிறோம்! 👋', auth_join: 'HelperHub-ல் சேருங்கள்! 🎉',
    auth_create_free: 'இலவச கணக்கை உருவாக்குங்கள்', auth_sign_in_to: 'டாஷ்போர்டு அணுகல்',
    auth_tab_signin: 'உள்நுழை', auth_tab_create: 'கணக்கை உருவாக்கு',
    auth_joining_as: 'நான் சேருகிறேன்...', auth_role_hire: 'எனக்கு உதவி வேண்டும் 🏠',
    auth_role_hire_desc: 'வீட்டு பழுதுபார்ப்புக்கு உதவியாளரை முன்பதிவு செய்யுங்கள்',
    auth_role_work: 'நான் வேலை செய்வேன் 🛠️', auth_role_work_desc: 'உங்கள் திறமையால் உதவுங்கள்',
    auth_full_name: 'முழு பெயர்', auth_email: 'மின்னஞ்சல்', auth_password: 'கடவுச்சொல்',
    auth_create_btn: 'கணக்கை உருவாக்கு 🎉', auth_signin_btn: 'உள்நுழை 🚀',
    auth_loading: 'காத்திருங்கள்...', auth_demo: 'டெமோ கணக்குகள்:',
    otp_title: 'மின்னஞ்சலை சரிபார்க்கவும்', otp_sent: '6 இலக்க குறியீடு அனுப்பப்பட்டது',
    otp_verify_btn: 'சரிபார்க்கவும்! 🎉', otp_verifying: 'சரிபார்க்கிறது...', otp_back: 'பின்செல்',
    browse_location: '📍 டெல்லி', browse_search: 'பிளம்பர், எலக்ட்ரீஷியன்...',
    browse_filters: 'வடிப்பான்கள்', browse_results: 'உதவியாளர்கள் கண்டுபிடிக்கப்பட்டனர்',
    browse_no_results: 'உதவியாளர்கள் கிடைக்கவில்லை.', browse_filter_price: 'அதிகபட்ச விலை',
    browse_filter_distance: 'தூரம்', browse_filter_rating: 'குறைந்த மதிப்பீடு',
    browse_filter_experience: 'குறைந்த அனுபவம்', browse_filter_language: 'மொழி',
    browse_filter_verified: 'சரிபார்க்கப்பட்டவர்கள் மட்டும்', browse_filter_today: 'இன்று கிடைக்கும்',
    browse_filter_emergency: 'அவசர SOS', browse_filter_reset: 'மீட்டமை',
    browse_book: 'இப்போதே முன்பதிவு ⚡', browse_cat_all: 'அனைத்தும்',
    book_step_date: 'தேதி', book_step_time: 'நேரம்', book_step_details: 'விவரங்கள்',
    book_step_review: 'மதிப்பாய்வு', book_step_payment: 'பணம்',
    book_choose_date: 'தேதியை தேர்ந்தெடுக்கவும்', book_choose_time: 'நேர ஸ்லாட் தேர்ந்தெடுக்கவும்',
    book_slots_for: 'ஸ்லாட்கள் காட்டுகிறது', book_booked: 'முன்பதிவு செய்யப்பட்டது',
    book_job_title: 'வேலை பெயர்', book_job_desc: 'பிரச்சனையை விவரிக்கவும்',
    book_address: 'முழு முகவரி', book_upload: 'புகைப்படங்களை பதிவேற்றவும் (விருப்பமானது)',
    book_upload_hint: 'இழுத்து விடவும் அல்லது கிளிக் செய்யவும்',
    book_review_heading: 'முன்பதிவை மதிப்பாய்வு செய்யுங்கள்',
    book_hero: 'ஹீரோ', book_service: 'சேவை', book_date: 'தேதி', book_time: 'நேரம்',
    book_job: 'வேலை', book_address_label: 'முகவரி', book_service_fee: 'சேவை கட்டணம்',
    book_platform_fee: 'தள கட்டணம்', book_total: 'மொத்தம்',
    book_escrow: 'உங்கள் பணம் எஸ்க்ரோவில் பாதுகாப்பாக உள்ளது.',
    book_pay_secure: 'பாதுகாப்பான பணம்', book_card_number: 'அட்டை எண்',
    book_expiry: 'காலாவதி', book_cvv: 'CVV', book_name_card: 'அட்டையில் பெயர்',
    book_ssl: '256-bit SSL · Stripe', book_pay_btn: 'பணம் செலுத்துங்கள்', book_securely: '🔒',
    book_continue: 'தொடரவும்', book_back: 'பின்செல்', book_cancel: 'ரத்துசெய்',
    book_processing: 'செயலாக்கப்படுகிறது...', book_confirmed_title: 'முன்பதிவு உறுதியானது! 🎉',
    book_confirmed_sub: 'உங்கள் ஹீரோ வழியில்!', book_view_status: 'நிலையை பார் →',
    book_close: 'மூடு',
    footer_tagline: 'நம்பகமான அக்கம்பக்க சேவை தளம்.',
    footer_services: 'சேவைகள்', footer_company: 'நிறுவனம்', footer_legal: 'சட்டம்',
    footer_about: 'எங்களைப் பற்றி', footer_careers: 'வேலைகள்', footer_blog: 'வலைப்பதிவு',
    footer_press: 'பிரெஸ்', footer_privacy: 'தனியுரிமை கொள்கை',
    footer_terms: 'சேவை விதிமுறைகள்', footer_refund: 'திரும்பப்பெறும் கொள்கை',
    footer_rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்படுகின்றன.',
    dash_welcome: 'மீண்டும் வரவேற்கிறோம்', dash_active_jobs: 'செயலில் வேலைகள்',
    dash_total_spent: 'மொத்த செலவு', dash_total_earned: 'மொத்த வருமானம்',
    dash_rating: 'மதிப்பீடு', dash_completed: 'முடிந்தது', dash_pending: 'நிலுவை',
    dash_accepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    general_loading: 'ஏற்றுகிறது...', general_see_all: 'அனைத்தும் பார்',
    general_close: 'மூடு', general_save: 'சேமி', general_cancel: 'ரத்துசெய்',
    general_confirm: 'உறுதிப்படுத்து', general_hrs: 'மணி', general_per_hr: '/மணி',
    general_jobs: 'வேலைகள்', general_yrs: 'ஆண்டுகள்', general_today: 'இன்று', general_tomorrow: 'நாளை',
  },

  // ─── KANNADA ──────────────────────────────────────────────────────────────
  kn: {
    nav_find: 'ಸಹಾಯಕನನ್ನು ಹುಡುಕಿ', nav_how: 'ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ', nav_signin: 'ಸೈನ್ ಇನ್',
    nav_notifications: 'ಅಧಿಸೂಚನೆಗಳು', nav_language: 'ಭಾಷೆ', nav_dark: 'ಡಾರ್ಕ್', nav_light: 'ಲೈಟ್',
    nav_dashboard: 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', nav_signout: 'ಸೈನ್ ಔಟ್',
    nav_mark_all_read: 'ಎಲ್ಲವನ್ನೂ ಓದಿದೆ', nav_view_all: 'ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳು →',
    notif_1_title: 'ಬುಕಿಂಗ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ! 🎉', notif_1_body: 'ರಾಜೇಶ್ ಕುಮಾರ್ ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದ್ದಾರೆ.',
    notif_2_title: 'ಪಾವತಿ ಯಶಸ್ವಿ ✅', notif_2_body: '₹500 ಎಸ್ಕ್ರೋ ಮೂಲಕ ಪಾವತಿಸಲಾಗಿದೆ.',
    notif_3_title: 'ಕಾರ್ಮಿಕ ಬರುತ್ತಿದ್ದಾರೆ 🚗', notif_3_body: 'ಸುನೀತಾ ಶರ್ಮಾ 10 ನಿಮಿಷಗಳಲ್ಲಿ ಬರುತ್ತಾರೆ.',
    notif_4_title: 'ಕೆಲಸ ಪೂರ್ಣವಾಯಿತು 🛠️', notif_4_body: 'ಅಡಿಗೆ ಸಿಂಕ್ ರಿಪೇರಿ ಪೂರ್ಣ.',
    notif_5_title: 'ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ ⭐', notif_5_body: 'ಅಜಯ್ ಪಟೇಲ್ ಹೇಗಿದ್ದರು?',
    hero_badge: '🏠 50,000+ ಮನೆ ಮಾಲೀಕರು ನಂಬುತ್ತಾರೆ',
    hero_title_1: 'ನಿಮ್ಮ ನೆರೆಹೊರೆಯ', hero_title_2: 'ಫಿಕ್ಸ್-ಇಟ್ ಹೀರೋಗಳು',
    hero_title_3: 'ಒಂದು ಟ್ಯಾಪ್ ದೂರದಲ್ಲಿ', hero_sub: 'ಪ್ಲಂಬರ್, ಎಲೆಕ್ಟ್ರೀಷಿಯನ್, ಪೇಂಟರ್ ಬುಕ್ ಮಾಡಿ.',
    hero_search_placeholder: 'ಏನು ಸರಿಪಡಿಸಬೇಕು?',
    hero_search_btn: 'ಹೀರೋ ಹುಡುಕಿ 🔍',
    hero_or: 'ಅಥವಾ ವರ್ಗದ ಮೂಲಕ ಬ್ರೌಸ್ ಮಾಡಿ',
    hero_stat_1: '50K+ ಮನೆ ಮಾಲೀಕರು', hero_stat_2: '2,000+ ಹೀರೋಗಳು', hero_stat_3: '4.9★ ರೇಟಿಂಗ್',
    categories_title: 'ಇಂದು ಏನು ಸರಿಪಡಿಸಬೇಕು?', categories_sub: 'ಒಂದು ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ.',
    cat_plumber: 'ಪ್ಲಂಬರ್', cat_electrician: 'ಎಲೆಕ್ಟ್ರೀಷಿಯನ್', cat_carpenter: 'ಮರಗೆಲಸದವರು',
    cat_ac: 'AC ತಂತ್ರಜ್ಞ', cat_painter: 'ಪೇಂಟರ್', cat_cleaner: 'ಕ್ಲೀನರ್',
    cat_mechanic: 'ಮೆಕ್ಯಾನಿಕ್', cat_gardener: 'ತೋಟಗಾರ',
    how_title: '⭐ HelperHub ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ', how_sub: '5 ಸರಳ ಹಂತಗಳಲ್ಲಿ',
    how_step1_title: 'ಸೇವೆ ಹುಡುಕಿ 🔍', how_step1_desc: 'ನಿಮ್ಮ ಅಗತ್ಯ ಟೈಪ್ ಮಾಡಿ.',
    how_step2_title: 'ತಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಿ 🤝', how_step2_desc: 'ಟಾಪ್-ರೇಟೆಡ್ ಹೀರೋ ಆಯ್ಕೆಮಾಡಿ.',
    how_step3_title: 'ಸುರಕ್ಷಿತ ಪಾವತಿ 🔒', how_step3_desc: 'ಕೆಲಸ ಮುಗಿಯುವ ತನಕ ಹಣ ಎಸ್ಕ್ರೋದಲ್ಲಿ.',
    how_step4_title: 'ಕೆಲಸ ಮುಗಿಯಿತು 🛠️', how_step4_desc: 'ಹೀರೋ ನಿಮ್ಮ ಮನೆಗೆ ಬಂದು ಕೆಲಸ ಮಾಡುತ್ತಾರೆ.',
    how_step5_title: 'ಅನುಭವ ರೇಟ್ ಮಾಡಿ ⭐', how_step5_desc: 'ರಿವ್ಯೂ ಕೊಡಿ, ಪಾವತಿ ಬಿಡುಗಡೆಯಾಗುತ್ತದೆ.',
    top_title: '⭐ ನಿಮ್ಮ ಬಳಿಯ ಟಾಪ್ ತಜ್ಞರು', top_sub: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ, 4.8+',
    top_view_all: 'ಎಲ್ಲಾ ಸಹಾಯಕರನ್ನು ನೋಡಿ →',
    recent_title: '⚡ ಇತ್ತೀಚೆಗೆ ಮುಗಿದ ಕೆಲಸಗಳು', recent_sub: 'ನಿಮ್ಮ ನಗರದಲ್ಲಿ ನಡೆಯುತ್ತಿದೆ',
    testimonials_title: '❤️ ಮನೆ ಮಾಲೀಕರು ಏನು ಹೇಳುತ್ತಾರೆ', testimonials_sub: 'ನೆರೆಯವರ ನಿಜವಾದ ಕಥೆಗಳು',
    why_title: '🌟 HelperHub ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?', why_sub: 'ನಾವು ಕೇವಲ ಬುಕಿಂಗ್ ಆಪ್ ಅಲ್ಲ.',
    why_1_title: 'ಪರಿಶೀಲಿಸಿದ ತಜ್ಞರು', why_1_desc: 'ಆಧಾರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.',
    why_2_title: 'ಸುರಕ್ಷಿತ ಎಸ್ಕ್ರೋ', why_2_desc: 'ಕೆಲಸ ಮುಗಿದ ನಂತರ ಮಾತ್ರ ಪಾವತಿ.',
    why_3_title: 'AI ಬೆಲೆ ಅಂದಾಜು', why_3_desc: 'ಬುಕ್ ಮಾಡುವ ಮುನ್ನ ಬೆಲೆ ತಿಳಿಯಿರಿ.',
    why_4_title: 'ತುರ್ತು ಬುಕಿಂಗ್', why_4_desc: '24/7 ಲಭ್ಯ ಹೀರೋಗಳು.',
    why_calc_title: '🤖 AI ಬೆಲೆ ಕ್ಯಾಲ್ಕ್ಯುಲೇಟರ್', why_calc_sub: 'ತಕ್ಷಣ ಅಂದಾಜು',
    why_calc_category: 'ಸೇವೆ', why_calc_hours: 'ಗಂಟೆಗಳು', why_calc_estimate: 'ಅಂದಾಜು ವೆಚ್ಚ',
    why_calc_note: 'ಚೆಕ್‌ಔಟ್‌ನಲ್ಲಿ ₹50 ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ',
    app_badge: '📱 ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ', app_title: 'HelperHub ನಿಮ್ಮ ಜೇಬಿನಲ್ಲಿ',
    app_sub: 'ಫೋನ್‌ನಿಂದ ಸಹಾಯಕರನ್ನು ಬುಕ್ ಮಾಡಿ.', app_ios: '🍎 App Store', app_android: '🤖 Google Play',
    cta_hire_title: 'ನಿಮ್ಮ ಹೀರೋ ಹುಡುಕಲು ಸಿದ್ಧರಾಗಿದ್ದೀರಾ?',
    cta_hire_sub: '50,000+ ಮನೆ ಮಾಲೀಕರು HelperHub ನಂಬುತ್ತಾರೆ.',
    cta_hire_btn: 'ಈಗ ಹೀರೋ ಬುಕ್ ಮಾಡಿ 🚀',
    cta_work_title: 'ನೀವು ನುರಿತ ತಜ್ಞರಾ?', cta_work_sub: 'ಸಹಾಯಕರಾಗಿ ಸೇರಿ!',
    cta_work_btn: 'ಸಹಾಯಕರಾಗಿ ಸೇರಿ ⚡',
    auth_welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ! 👋', auth_join: 'HelperHub ಗೆ ಸೇರಿ! 🎉',
    auth_create_free: 'ಉಚಿತ ಖಾತೆ ರಚಿಸಿ', auth_sign_in_to: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ',
    auth_tab_signin: 'ಸೈನ್ ಇನ್', auth_tab_create: 'ಖಾತೆ ರಚಿಸಿ',
    auth_joining_as: 'ನಾನು ಸೇರುತ್ತಿದ್ದೇನೆ...', auth_role_hire: 'ನನಗೆ ಸಹಾಯ ಬೇಕು 🏠',
    auth_role_hire_desc: 'ಮನೆ ರಿಪೇರಿಗೆ ಸಹಾಯಕರನ್ನು ಬುಕ್ ಮಾಡಿ',
    auth_role_work: 'ನಾನು ಕೆಲಸ ಮಾಡುತ್ತೇನೆ 🛠️', auth_role_work_desc: 'ನಿಮ್ಮ ಕೌಶಲ್ಯದಿಂದ ಸಹಾಯ ಮಾಡಿ',
    auth_full_name: 'ಪೂರ್ಣ ಹೆಸರು', auth_email: 'ಇಮೇಲ್', auth_password: 'ಪಾಸ್‌ವರ್ಡ್',
    auth_create_btn: 'ಖಾತೆ ರಚಿಸಿ 🎉', auth_signin_btn: 'ಸೈನ್ ಇನ್ 🚀',
    auth_loading: 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...', auth_demo: 'ಡೆಮೋ ಖಾತೆಗಳು:',
    otp_title: 'ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ', otp_sent: '6 ಅಂಕಿ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ',
    otp_verify_btn: 'ಪರಿಶೀಲಿಸಿ! 🎉', otp_verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...', otp_back: 'ಹಿಂದೆ',
    browse_location: '📍 ದೆಹಲಿ', browse_search: 'ಪ್ಲಂಬರ್, ಎಲೆಕ್ಟ್ರೀಷಿಯನ್...',
    browse_filters: 'ಫಿಲ್ಟರ್‌ಗಳು', browse_results: 'ಸಹಾಯಕರು ಕಂಡುಬಂದರು',
    browse_no_results: 'ಸಹಾಯಕರು ಕಂಡುಬಂದಿಲ್ಲ.', browse_filter_price: 'ಗರಿಷ್ಠ ಬೆಲೆ',
    browse_filter_distance: 'ದೂರ', browse_filter_rating: 'ಕನಿಷ್ಠ ರೇಟಿಂಗ್',
    browse_filter_experience: 'ಕನಿಷ್ಠ ಅನುಭವ', browse_filter_language: 'ಭಾಷೆ',
    browse_filter_verified: 'ಪರಿಶೀಲಿಸಿದವರು ಮಾತ್ರ', browse_filter_today: 'ಇಂದು ಲಭ್ಯ',
    browse_filter_emergency: 'ತುರ್ತು SOS', browse_filter_reset: 'ರೀಸೆಟ್',
    browse_book: 'ಈಗ ಬುಕ್ ⚡', browse_cat_all: 'ಎಲ್ಲಾ',
    book_step_date: 'ದಿನಾಂಕ', book_step_time: 'ಸಮಯ', book_step_details: 'ವಿವರಗಳು',
    book_step_review: 'ಪರಿಶೀಲನೆ', book_step_payment: 'ಪಾವತಿ',
    book_choose_date: 'ದಿನಾಂಕ ಆಯ್ಕೆ ಮಾಡಿ', book_choose_time: 'ಸಮಯ ಸ್ಲಾಟ್ ಆಯ್ಕೆ ಮಾಡಿ',
    book_slots_for: 'ಸ್ಲಾಟ್‌ಗಳು ತೋರಿಸಲಾಗುತ್ತಿದೆ', book_booked: 'ಬುಕ್ ಆಗಿದೆ',
    book_job_title: 'ಕೆಲಸದ ಹೆಸರು', book_job_desc: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    book_address: 'ಪೂರ್ಣ ವಿಳಾಸ', book_upload: 'ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (ಐಚ್ಛಿಕ)',
    book_upload_hint: 'ಎಳೆಯಿರಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ',
    book_review_heading: 'ಬುಕಿಂಗ್ ಪರಿಶೀಲಿಸಿ',
    book_hero: 'ಹೀರೋ', book_service: 'ಸೇವೆ', book_date: 'ದಿನಾಂಕ', book_time: 'ಸಮಯ',
    book_job: 'ಕೆಲಸ', book_address_label: 'ವಿಳಾಸ', book_service_fee: 'ಸೇವಾ ಶುಲ್ಕ',
    book_platform_fee: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ', book_total: 'ಒಟ್ಟು',
    book_escrow: 'ನಿಮ್ಮ ಹಣ ಎಸ್ಕ್ರೋದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    book_pay_secure: 'ಸುರಕ್ಷಿತ ಪಾವತಿ', book_card_number: 'ಕಾರ್ಡ್ ಸಂಖ್ಯೆ',
    book_expiry: 'ಅವಧಿ ಮುಕ್ತಾಯ', book_cvv: 'CVV', book_name_card: 'ಕಾರ್ಡ್‌ನಲ್ಲಿ ಹೆಸರು',
    book_ssl: '256-ಬಿಟ್ SSL · Stripe', book_pay_btn: 'ಪಾವತಿ ಮಾಡಿ', book_securely: '🔒',
    book_continue: 'ಮುಂದುವರಿಯಿರಿ', book_back: 'ಹಿಂದೆ', book_cancel: 'ರದ್ದು ಮಾಡಿ',
    book_processing: 'ಪ್ರಕ್ರಿಯೆ ಆಗುತ್ತಿದೆ...', book_confirmed_title: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ! 🎉',
    book_confirmed_sub: 'ನಿಮ್ಮ ಹೀರೋ ದಾರಿಯಲ್ಲಿ!', book_view_status: 'ಸ್ಥಿತಿ ನೋಡಿ →',
    book_close: 'ಮುಚ್ಚಿ',
    footer_tagline: 'ವಿಶ್ವಾಸಾರ್ಹ ನೆರೆಹೊರೆ ಸೇವಾ ವೇದಿಕೆ.',
    footer_services: 'ಸೇವೆಗಳು', footer_company: 'ಕಂಪನಿ', footer_legal: 'ಕಾನೂನು',
    footer_about: 'ನಮ್ಮ ಬಗ್ಗೆ', footer_careers: 'ಉದ್ಯೋಗ', footer_blog: 'ಬ್ಲಾಗ್',
    footer_press: 'ಪ್ರೆಸ್', footer_privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    footer_terms: 'ಸೇವಾ ನಿಯಮಗಳು', footer_refund: 'ಮರುಪಾವತಿ ನೀತಿ',
    footer_rights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿವೆ.',
    dash_welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ', dash_active_jobs: 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು',
    dash_total_spent: 'ಒಟ್ಟು ಖರ್ಚು', dash_total_earned: 'ಒಟ್ಟು ಆದಾಯ',
    dash_rating: 'ರೇಟಿಂಗ್', dash_completed: 'ಮುಗಿದಿದೆ', dash_pending: 'ಬಾಕಿ ಇದೆ',
    dash_accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    general_loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', general_see_all: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    general_close: 'ಮುಚ್ಚಿ', general_save: 'ಉಳಿಸಿ', general_cancel: 'ರದ್ದು',
    general_confirm: 'ದೃಢೀಕರಿಸಿ', general_hrs: 'ಗಂಟೆ', general_per_hr: '/ಗಂಟೆ',
    general_jobs: 'ಕೆಲಸಗಳು', general_yrs: 'ವರ್ಷಗಳು', general_today: 'ಇಂದು', general_tomorrow: 'ನಾಳೆ',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// CONTEXT + PROVIDER
// ─────────────────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('hh-lang') || 'en';
    return translations[saved] ? saved : 'en';
  });

  const changeLang = (code) => {
    if (translations[code]) {
      setLang(code);
      localStorage.setItem('hh-lang', code);
    }
  };

  // t(key) — returns translated string or falls back to English
  const t = (key) => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// HOOK — use anywhere: const { t, lang, changeLang } = useLanguage();
// ─────────────────────────────────────────────────────────────────────────────
export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export { translations };
