import { createContext, useContext, useState, useEffect } from 'react';

// Translations with 100% key parity across en, hi, mr, ml, te, ta, kn
const translations = {
  "en": {
    "nav_find": "Find Helpers",
    "nav_how": "How It Works",
    "nav_signin": "Sign In",
    "nav_notifications": "Notifications",
    "nav_language": "Language",
    "nav_dark": "Dark",
    "nav_light": "Light",
    "nav_dashboard": "My Dashboard",
    "nav_signout": "Sign Out",
    "nav_mark_all_read": "Mark all read",
    "nav_view_all": "View all notifications →",
    "notif_1_title": "Booking Accepted! 🎉",
    "notif_1_body": "Rajesh Kumar accepted your plumbing request.",
    "notif_2_title": "Payment Successful ✅",
    "notif_2_body": "₹500 paid securely via escrow for AC repair.",
    "notif_3_title": "Worker Arriving Soon 🚗",
    "notif_3_body": "Sunita Sharma is 10 minutes away. Get ready!",
    "notif_4_title": "Job Completed 🛠️",
    "notif_4_body": "Kitchen sink repair marked as complete.",
    "notif_5_title": "Rate Your Experience ⭐",
    "notif_5_body": "How was Ajay Patel? Leave a review and help others.",
    "hero_badge": "🏠 Trusted by 50,000+ Homeowners",
    "hero_title_1": "Your Neighbourhood",
    "hero_title_2": "Fix-It Heroes",
    "hero_title_3": "Are One Tap Away",
    "hero_sub": "Book verified plumbers, electricians, painters & more in your area. Fair prices. Secure payments. Instant booking.",
    "hero_search_placeholder": "What needs fixing? e.g. AC not cooling, leaking tap...",
    "hero_search_btn": "Find My Hero 🔍",
    "hero_or": "or browse by category",
    "hero_stat_1": "50K+ Homeowners",
    "hero_stat_2": "2,000+ Heroes",
    "hero_stat_3": "4.9★ Rating",
    "landing_cat_badge": "Browse Categories",
    "landing_cat_browse": "Browse",
    "landing_hiw_badge": "How It Works",
    "landing_top_badge": "Top Rated",
    "landing_top_explore": "Explore All",
    "landing_jobs_badge": "Recently Completed Jobs",
    "landing_live_activity": "⚡ Live Activity",
    "landing_test_badge": "Testimonials",
    "landing_why_badge": "Why Choose HelperHub",
    "landing_quick_popular": "Popular:",
    "landing_card_master": "Master Professional",
    "landing_card_reviews": "reviews",
    "landing_card_all_set": "All Set!",
    "landing_card_done": "Booking Completed",
    "landing_card_verified": "Verified Pro",
    "landing_card_jobs": "jobs",
    "landing_card_flexible": "Flexible Hours",
    "landing_card_view": "View Profile",
    "landing_no_helpers": "No helpers registered yet",
    "categories_title": "What do you need fixed today?",
    "categories_sub": "Pick a category and we'll find verified heroes near you.",
    "cat_plumber": "Plumber",
    "cat_electrician": "Electrician",
    "cat_carpenter": "Carpenter",
    "cat_ac": "AC Technician",
    "cat_painter": "Painter",
    "cat_cleaner": "Cleaner",
    "cat_mechanic": "Mechanic",
    "cat_gardener": "Gardener",
    "cat_repair": "General Repair",
    "how_title": "⭐ How HelperHub Works",
    "how_sub": "From search to done in 5 simple steps",
    "how_step1_title": "Search Service 🔍",
    "how_step1_desc": "Type your repair need or browse verified local helpers by category & location.",
    "how_step2_title": "Book Professional 🤝",
    "how_step2_desc": "Select a top-rated hero, pick your date & time, and send an instant hire request.",
    "how_step3_title": "Pay Securely 🔒",
    "how_step3_desc": "Once accepted, funds are held safely in Stripe Escrow until the work is done.",
    "how_step4_title": "Job Completed 🛠️",
    "how_step4_desc": "Hero finishes the work at your doorstep. Both sides confirm job completion.",
    "how_step5_title": "Rate Experience ⭐",
    "how_step5_desc": "Payment is released to the hero, and you leave a star review to help neighbors!",
    "top_title": "⭐ Top Rated Professionals Near You",
    "top_sub": "Verified, background-checked heroes with 4.8+ ratings",
    "top_view_all": "View All Helpers →",
    "recent_title": "⚡ Recently Completed Jobs",
    "recent_sub": "Real work, real results — happening right now in your city",
    "job_kitchen_sink": "Kitchen Sink Leak Fixed",
    "job_split_ac": "Split AC Installed",
    "job_living_room_paint": "Living Room Painting",
    "job_mcb_tripping": "Main MCB Tripping Fixed",
    "job_door_repair": "Wooden Door Frame Repair",
    "testimonials_title": "❤️ What Homeowners Say",
    "testimonials_sub": "Real stories from your neighbors who love HelperHub",
    "test_1_quote": "\"Booked a plumber in 2 minutes for a burst sink pipe, and Rajesh arrived in 15 mins to fix it completely!\"",
    "test_2_quote": "\"The escrow payment protection gave me 100% peace of mind. Best home service app hands down.\"",
    "test_3_quote": "\"Fair, transparent pricing without any surprise charges. The electrician was super polite and clean.\"",
    "why_title": "🌟 Why Choose HelperHub?",
    "why_sub": "We're not just another booking app — we're your neighbours' trusted helper network.",
    "why_1_title": "✔ Verified Professionals",
    "why_1_desc": "100% Aadhaar & police background checked pros.",
    "why_2_title": "✔ Secure Payments",
    "why_2_desc": "Funds held safely in escrow until work is approved.",
    "why_3_title": "✔ AI Cost Estimation",
    "why_3_desc": "Instant fair price ranges based on market rates.",
    "why_4_title": "✔ Emergency Booking",
    "why_4_desc": "15-minute rapid SOS dispatch for urgent leaks & faults.",
    "ai_est_title": "AI Cost Estimator",
    "ai_est_badge": "✨ Powered by Claude AI",
    "ai_est_subtitle": "Describe your job and get an instant AI-powered price estimate based on real Indian market rates.",
    "ai_est_service_type": "Service Type",
    "ai_est_city": "City",
    "ai_est_job_desc": "Job Description",
    "ai_est_job_desc_hint": "(what needs to be done?)",
    "ai_est_placeholder": "e.g. Kitchen sink pipe is leaking under the counter, water dripping onto the cabinet floor...",
    "ai_est_price_range": "AI ESTIMATED PRICE RANGE",
    "ai_est_high_conf": "✓ High Confidence",
    "ai_est_med_conf": "~ Medium Confidence",
    "ai_est_low_conf": "! Low Confidence",
    "ai_est_book_prefix": "Book a",
    "ai_est_get_btn": "✨ Get AI Cost Estimate",
    "ai_est_loading": "Getting AI Estimate...",
    "ai_est_error_min_len": "Please describe the job in at least 10 characters.",
    "app_badge": "📱 Coming Soon",
    "app_title": "HelperHub in Your Pocket",
    "app_sub": "Book helpers, track jobs, and pay securely — all from your phone. iOS & Android apps launching soon!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-Tap Emergency Fix",
    "cta_hire_title": "Ready to Fix Things Up? 🛠️",
    "cta_hire_sub": "Join thousands of happy homeowners and local pros on HelperHub!",
    "cta_hire_btn": "Hire Your Hero Now",
    "cta_work_title": "Are you a skilled professional?",
    "cta_work_sub": "Join as a helper and start earning with your skills today!",
    "cta_work_btn": "Join as a Helper",
    "auth_welcome": "Welcome Back! 👋",
    "auth_join": "Join HelperHub Today! 🎉",
    "auth_create_free": "Create your free account in seconds",
    "auth_sign_in_to": "Sign in to access your dashboard",
    "auth_tab_signin": "Sign In",
    "auth_tab_create": "Create Account",
    "auth_joining_as": "I am joining as...",
    "auth_role_hire": "I Need Help 🏠",
    "auth_role_hire_desc": "Hire friendly local heroes for home repairs",
    "auth_role_work": "I Want to Work 🛠️",
    "auth_role_work_desc": "List your skills and get hired by neighbors",
    "auth_full_name": "Full Name",
    "auth_email": "Email Address",
    "auth_password": "Password",
    "auth_create_btn": "Create Account 🎉",
    "auth_signin_btn": "Sign In 🚀",
    "auth_loading": "Please wait...",
    "auth_demo": "Demo Accounts:",
    "auth_google_continue": "Continue with Google",
    "auth_or_email": "or continue with email",
    "otp_title": "Verify Your Email",
    "otp_sent": "We sent a 6-digit verification code to",
    "otp_verify_btn": "Verify & You're All Set! 🎉",
    "otp_verifying": "Verifying...",
    "otp_back": "Back",
    "browse_location": "📍 Delhi",
    "browse_search": "Search plumber, electrician, painter...",
    "browse_search_placeholder": "Search plumber, electrician, painter...",
    "browse_filters": "Filters",
    "browse_filter_btn": "Filters",
    "browse_results": "helpers found nearby",
    "browse_no_results": "No helpers found. Try adjusting your filters.",
    "browse_filter_price": "Max Price",
    "browse_filter_distance": "Distance",
    "browse_filter_rating": "Min Rating",
    "browse_filter_experience": "Yrs Exp",
    "browse_filter_language": "Language",
    "browse_filter_verified": "Verified Only",
    "browse_filter_today": "Available Today",
    "browse_filter_emergency": "Emergency SOS",
    "browse_filter_reset": "Reset",
    "browse_book": "Hire Now",
    "browse_cat_all": "All",
    "book_step_date": "Date",
    "book_step_time": "Time Slot",
    "book_step_details": "Job Details",
    "book_step_review": "Review",
    "book_step_payment": "Payment",
    "book_choose_date": "Choose a Date",
    "book_choose_time": "Pick a Time Slot",
    "book_slots_for": "Showing slots for",
    "book_booked": "Booked",
    "book_job_title": "Job Title",
    "book_job_desc": "Problem Description",
    "book_address": "Full Address",
    "book_upload": "Upload Photos of the Issue (Optional)",
    "book_upload_hint": "Drag & drop or click to upload",
    "book_review_heading": "Review Your Booking",
    "book_hero": "Hero",
    "book_service": "Service",
    "book_date": "Date",
    "book_time": "Time",
    "book_job": "Job",
    "book_address_label": "Address",
    "book_service_fee": "Service Fee",
    "book_platform_fee": "Platform Fee",
    "book_total": "Total",
    "book_escrow": "Your payment is held safely in escrow and released to the helper only after you confirm the work is done.",
    "book_pay_secure": "Secure Payment",
    "book_card_number": "Card Number",
    "book_expiry": "Expiry",
    "book_cvv": "CVV",
    "book_name_card": "Name on Card",
    "book_ssl": "256-bit SSL encrypted · Powered by Stripe",
    "book_pay_btn": "Pay",
    "book_securely": "🔒",
    "book_continue": "Continue",
    "book_back": "Back",
    "book_cancel": "Cancel",
    "book_processing": "Processing...",
    "book_confirmed_title": "Booking Confirmed! 🎉",
    "book_confirmed_sub": "Your fix-it hero is on the way!",
    "book_view_status": "View Job Status →",
    "book_close": "Close",
    "sos_btn": "SOS Emergency",
    "sos_title": "🚨 Emergency SOS Assistance",
    "sos_subtitle": "Priority 15-minute dispatch for urgent household hazards",
    "sos_banner": "Need immediate help? Pick your emergency below for 1-click priority dispatch.",
    "sos_dispatch_btn": "Dispatch Priority Hero",
    "sos_dispatching": "Dispatching Hero...",
    "sos_unit_active": "24/7 Rapid Response Unit active",
    "sos_electrician_title": "Emergency Electrician",
    "sos_electrician_desc": "Power outage, main MCB trip, sparking switches, or short circuit.",
    "sos_gas_title": "Gas Leak Emergency",
    "sos_gas_desc": "Piped gas leak smell, regulator fault, or LPG valve issue.",
    "sos_pipe_title": "Burst Pipe",
    "sos_pipe_desc": "Uncontrolled water flooding, pipe line break, or main valve failure.",
    "sos_lock_title": "Door Lockout",
    "sos_lock_desc": "Locked outside, key snapped in cylinder, or electronic lock failure.",
    "sos_water_title": "Water Leakage & Overflow",
    "sos_water_desc": "Overhead tank overflow, major ceiling seepage, or drain blockage.",
    "sos_fire_title": "Fire Safety & Electrical Smoke",
    "sos_fire_desc": "Wiring burning smell, appliance overheating, or smoke isolation.",
    "footer_tagline": "Your friendly neighbourhood service platform. Connecting skilled heroes with homeowners who need them — fast, safe, and fair.",
    "footer_services": "Services",
    "footer_company": "Company",
    "footer_contact": "Contact",
    "footer_legal": "Legal",
    "footer_about": "About Us",
    "footer_careers": "Careers",
    "footer_blog": "Blog",
    "footer_press": "Press",
    "footer_privacy": "Privacy Policy",
    "footer_terms": "Terms of Service",
    "footer_refund": "Refund Policy",
    "footer_rights": "All rights reserved.",
    "dash_welcome": "Welcome back",
    "dash_active_jobs": "Active Jobs",
    "dash_total_spent": "Total Spent",
    "dash_total_earned": "Total Earned",
    "dash_rating": "Rating",
    "dash_completed": "Completed",
    "dash_pending": "Pending",
    "dash_accepted": "Accepted",
    "general_loading": "Loading...",
    "general_see_all": "See All",
    "general_close": "Close",
    "general_save": "Save",
    "general_cancel": "Cancel",
    "general_confirm": "Confirm",
    "general_hrs": "hrs",
    "general_per_hr": "/hr",
    "general_jobs": "jobs",
    "general_yrs": "yrs",
    "general_today": "Today",
    "general_tomorrow": "Tomorrow"
  },
  "hi": {
    "nav_find": "हेल्पर खोजें",
    "nav_how": "कैसे काम करता है",
    "nav_signin": "साइन इन",
    "nav_notifications": "सूचनाएं",
    "nav_language": "भाषा",
    "nav_dark": "डार्क",
    "nav_light": "लाइट",
    "nav_dashboard": "मेरा डैशबोर्ड",
    "nav_signout": "साइन आउट",
    "nav_mark_all_read": "सभी पढ़े",
    "nav_view_all": "सभी सूचनाएं देखें →",
    "notif_1_title": "बुकिंग स्वीकार! 🎉",
    "notif_1_body": "राजेश कुमार ने आपकी प्लंबिंग अनुरोध स्वीकार की।",
    "notif_2_title": "भुगतान सफल ✅",
    "notif_2_body": "₹500 एसी मरम्मत के लिए एस्क्रो से भुगतान हुआ।",
    "notif_3_title": "वर्कर आ रहा है 🚗",
    "notif_3_body": "सुनीता शर्मा 10 मिनट दूर है। तैयार रहें!",
    "notif_4_title": "काम पूरा हुआ 🛠️",
    "notif_4_body": "किचन सिंक मरम्मत पूर्ण चिह्नित।",
    "notif_5_title": "अनुभव रेट करें ⭐",
    "notif_5_body": "अजय पटेल कैसे थे? रिव्यू दें।",
    "hero_badge": "🏠 50,000+ घर मालिकों द्वारा भरोसेमंद",
    "hero_title_1": "आपके मोहल्ले के",
    "hero_title_2": "फिक्स-इट हीरो",
    "hero_title_3": "एक टैप दूर हैं",
    "hero_sub": "प्लंबर, इलेक्ट्रीशियन, पेंटर और अधिक को बुक करें। उचित मूल्य। सुरक्षित भुगतान। तत्काल बुकिंग।",
    "hero_search_placeholder": "क्या ठीक करवाना है? जैसे AC ठंडा नहीं, नल टपक रहा...",
    "hero_search_btn": "हीरो खोजें 🔍",
    "hero_or": "या श्रेणी से ब्राउज़ करें",
    "hero_stat_1": "50K+ घर मालिक",
    "hero_stat_2": "2,000+ हीरो",
    "hero_stat_3": "4.9★ रेटिंग",
    "landing_cat_badge": "श्रेणियां ब्राउज़ करें",
    "landing_cat_browse": "ब्राउज़ करें",
    "landing_hiw_badge": "यह कैसे काम करता है",
    "landing_top_badge": "टॉप रेटेड",
    "landing_top_explore": "सभी देखें",
    "landing_jobs_badge": "हाल ही में पूरे किए गए काम",
    "landing_live_activity": "⚡ लाइव गतिविधि",
    "landing_test_badge": "ग्राहकों के अनुभव",
    "landing_why_badge": "HelperHub क्यों चुनें",
    "landing_quick_popular": "लोकप्रिय:",
    "landing_card_master": "मास्टर प्रोफेशनल",
    "landing_card_reviews": "समीक्षाएं",
    "landing_card_all_set": "सब तैयार!",
    "landing_card_done": "बुकिंग पूरी हुई",
    "landing_card_verified": "सत्यापित प्रो",
    "landing_card_jobs": "काम",
    "landing_card_flexible": "लचीले घंटे",
    "landing_card_view": "प्रोफ़ाइल देखें",
    "landing_no_helpers": "अभी कोई हेल्पर पंजीकृत नहीं है",
    "categories_title": "आज क्या ठीक करवाना है?",
    "categories_sub": "श्रेणी चुनें और हम पास के हीरो खोजेंगे।",
    "cat_plumber": "प्लंबर",
    "cat_electrician": "इलेक्ट्रीशियन",
    "cat_carpenter": "बढ़ई",
    "cat_ac": "AC तकनीशियन",
    "cat_painter": "पेंटर",
    "cat_cleaner": "सफाई वाला",
    "cat_mechanic": "मैकेनिक",
    "cat_gardener": "माली",
    "cat_repair": "सामान्य मरम्मत",
    "how_title": "⭐ HelperHub कैसे काम करता है",
    "how_sub": "5 आसान चरणों में सेवा पूरी",
    "how_step1_title": "सेवा खोजें 🔍",
    "how_step1_desc": "अपनी जरूरत टाइप करें या श्रेणी से हेल्पर खोजें।",
    "how_step2_title": "प्रोफेशनल बुक करें 🤝",
    "how_step2_desc": "टॉप-रेटेड हीरो चुनें, तारीख और समय तय करें।",
    "how_step3_title": "सुरक्षित भुगतान 🔒",
    "how_step3_desc": "पैसे एस्क्रो में सुरक्षित रहते हैं जब तक काम पूरा न हो।",
    "how_step4_title": "काम पूरा 🛠️",
    "how_step4_desc": "हीरो घर आकर काम पूरा करता है।",
    "how_step5_title": "अनुभव रेट करें ⭐",
    "how_step5_desc": "काम पूरा होने पर भुगतान जारी और रिव्यू दें।",
    "top_title": "⭐ आपके पास के टॉप प्रोफेशनल",
    "top_sub": "सत्यापित, 4.8+ रेटिंग वाले हीरो",
    "top_view_all": "सभी हेल्पर देखें →",
    "recent_title": "⚡ हाल ही में पूरे काम",
    "recent_sub": "असली काम, असली नतीजे — अभी आपके शहर में",
    "job_kitchen_sink": "किचन सिंक लीकेज ठीक किया गया",
    "job_split_ac": "स्प्लिट एसी इंस्टाल किया गया",
    "job_living_room_paint": "लिविंग रूम पेंटिंग पूरी",
    "job_mcb_tripping": "मेन एमसीबी ट्रिपिंग ठीक की गई",
    "job_door_repair": "लकड़ी के दरवाजे का फ्रेम ठीक किया",
    "testimonials_title": "❤️ घर मालिक क्या कहते हैं",
    "testimonials_sub": "पड़ोसियों की असली कहानियां",
    "test_1_quote": "\"पाइप फटने पर 2 मिनट में प्लंबर बुक किया, और राजेश 15 मिनट में आकर सब ठीक कर गए!\"",
    "test_2_quote": "\"एस्क्रो सुरक्षा के कारण मुझे 100% मानसिक शांति मिली। सर्वश्रेष्ठ होम सर्विस ऐप!\"",
    "test_3_quote": "\"उचित और पारदर्शी मूल्य निर्धारण बिना किसी छिपे शुल्क के। इलेक्ट्रीशियन बहुत विनम्र था।\"",
    "why_title": "🌟 HelperHub क्यों चुनें?",
    "why_sub": "हम सिर्फ बुकिंग ऐप नहीं — आपके पड़ोस का भरोसेमंद नेटवर्क हैं।",
    "why_1_title": "✔ सत्यापित प्रोफेशनल",
    "why_1_desc": "हर हेल्पर आधार-सत्यापित और पुलिस-जांचा हुआ है।",
    "why_2_title": "✔ सुरक्षित भुगतान",
    "why_2_desc": "पैसे सुरक्षित एस्क्रो में, काम पूरा होने पर ही जारी।",
    "why_3_title": "✔ AI मूल्य अनुमान",
    "why_3_desc": "बुकिंग से पहले उचित मूल्य जानें। कोई छिपा शुल्क नहीं।",
    "why_4_title": "✔ आपातकालीन बुकिंग",
    "why_4_desc": "रात को पाइप फटा? हमारे हीरो 24/7 उपलब्ध हैं।",
    "ai_est_title": "AI लागत अनुमानक",
    "ai_est_badge": "✨ Claude AI द्वारा संचालित",
    "ai_est_subtitle": "अपने काम का विवरण दें और वास्तविक भारतीय बाज़ार दरों पर आधारित AI अनुमान पाएं।",
    "ai_est_service_type": "सेवा का प्रकार",
    "ai_est_city": "शहर",
    "ai_est_job_desc": "काम का विवरण",
    "ai_est_job_desc_hint": "(क्या ठीक करवाना है?)",
    "ai_est_placeholder": "उदा. सिंक के नीचे पाइप लीक हो रहा है, पानी कैबिनेट पर टपक रहा है...",
    "ai_est_price_range": "AI अनुमानित मूल्य सीमा",
    "ai_est_high_conf": "✓ उच्च सटीकता",
    "ai_est_med_conf": "~ मध्यम सटीकता",
    "ai_est_low_conf": "! कम सटीकता",
    "ai_est_book_prefix": "बुक करें",
    "ai_est_get_btn": "✨ AI लागत अनुमान प्राप्त करें",
    "ai_est_loading": "AI अनुमान निकाला जा रहा है...",
    "ai_est_error_min_len": "कृपया काम का विवरण कम से कम 10 अक्षरों में दें।",
    "app_badge": "📱 जल्द आ रहा है",
    "app_title": "HelperHub आपकी जेब में",
    "app_sub": "हेल्पर बुक करें, काम ट्रैक करें — फोन से। iOS और Android जल्द!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-टैप इमरजेंसी फिक्स",
    "cta_hire_title": "क्या आप मरम्मत के लिए तैयार हैं? 🛠️",
    "cta_hire_sub": "HelperHub पर हज़ारों खुश घर मालिकों और स्थानीय पेशेवरों से जुड़ें!",
    "cta_hire_btn": "अभी अपना हीरो चुनें",
    "cta_work_title": "क्या आप एक कुशल पेशेवर हैं?",
    "cta_work_sub": "हेल्पर के रूप में जुड़ें और आज ही कमाई शुरू करें!",
    "cta_work_btn": "हेल्पर के रूप में जुड़ें",
    "auth_welcome": "वापस स्वागत है! 👋",
    "auth_join": "आज HelperHub से जुड़ें! 🎉",
    "auth_create_free": "मुफ्त अकाउंट बनाएं",
    "auth_sign_in_to": "डैशबोर्ड एक्सेस करने के लिए साइन इन करें",
    "auth_tab_signin": "साइन इन",
    "auth_tab_create": "अकाउंट बनाएं",
    "auth_joining_as": "मैं किस रूप में जुड़ रहा हूं...",
    "auth_role_hire": "मुझे मदद चाहिए 🏠",
    "auth_role_hire_desc": "घर की मरम्मत के लिए हेल्पर बुक करें",
    "auth_role_work": "मैं काम करना चाहता हूं 🛠️",
    "auth_role_work_desc": "अपने कौशल से पड़ोसियों की मदद करें",
    "auth_full_name": "पूरा नाम",
    "auth_email": "ईमेल पता",
    "auth_password": "पासवर्ड",
    "auth_create_btn": "अकाउंट बनाएं 🎉",
    "auth_signin_btn": "साइन इन 🚀",
    "auth_loading": "कृपया प्रतीक्षा करें...",
    "auth_demo": "डेमो अकाउंट:",
    "auth_google_continue": "Google के साथ जारी रखें",
    "auth_or_email": "या ईमेल से जारी रखें",
    "otp_title": "ईमेल सत्यापित करें",
    "otp_sent": "6-अंकीय कोड भेजा गया",
    "otp_verify_btn": "सत्यापित करें और शुरू करें! 🎉",
    "otp_verifying": "सत्यापित हो रहा है...",
    "otp_back": "वापस",
    "browse_location": "📍 दिल्ली",
    "browse_search": "प्लंबर, इलेक्ट्रीशियन खोजें...",
    "browse_search_placeholder": "प्लंबर, इलेक्ट्रीशियन, पेंटर खोजें...",
    "browse_filters": "फ़िल्टर",
    "browse_filter_btn": "फ़िल्टर",
    "browse_results": "हेल्पर पास में मिले",
    "browse_no_results": "कोई हेल्पर नहीं मिला। फ़िल्टर बदलें।",
    "browse_filter_price": "अधिकतम मूल्य",
    "browse_filter_distance": "दूरी",
    "browse_filter_rating": "न्यूनतम रेटिंग",
    "browse_filter_experience": "साल अनुभव",
    "browse_filter_language": "भाषा",
    "browse_filter_verified": "केवल सत्यापित",
    "browse_filter_today": "आज उपलब्ध",
    "browse_filter_emergency": "आपातकालीन SOS",
    "browse_filter_reset": "रीसेट",
    "browse_book": "अभी बुक करें",
    "browse_cat_all": "सभी",
    "book_step_date": "तारीख",
    "book_step_time": "समय",
    "book_step_details": "विवरण",
    "book_step_review": "समीक्षा",
    "book_step_payment": "भुगतान",
    "book_choose_date": "तारीख चुनें",
    "book_choose_time": "समय स्लॉट चुनें",
    "book_slots_for": "स्लॉट दिखाए जा रहे हैं",
    "book_booked": "बुक्ड",
    "book_job_title": "काम का नाम",
    "book_job_desc": "समस्या का विवरण",
    "book_address": "पूरा पता",
    "book_upload": "समस्या की फ़ोटो अपलोड करें (वैकल्पिक)",
    "book_upload_hint": "खींचें और छोड़ें या क्लिक करें",
    "book_review_heading": "बुकिंग की समीक्षा करें",
    "book_hero": "हीरो",
    "book_service": "सेवा",
    "book_date": "तारीख",
    "book_time": "समय",
    "book_job": "काम",
    "book_address_label": "पता",
    "book_service_fee": "सेवा शुल्क",
    "book_platform_fee": "प्लेटफॉर्म शुल्क",
    "book_total": "कुल",
    "book_escrow": "आपका भुगतान एस्क्रो में सुरक्षित है और काम पूरा होने पर ही जारी होगा।",
    "book_pay_secure": "सुरक्षित भुगतान",
    "book_card_number": "कार्ड नंबर",
    "book_expiry": "वैधता",
    "book_cvv": "CVV",
    "book_name_card": "कार्ड पर नाम",
    "book_ssl": "256-बिट SSL एन्क्रिप्टेड · Stripe द्वारा",
    "book_pay_btn": "भुगतान करें",
    "book_securely": "🔒",
    "book_continue": "जारी रखें",
    "book_back": "वापस",
    "book_cancel": "रद्द करें",
    "book_processing": "प्रोसेसिंग...",
    "book_confirmed_title": "बुकिंग पुष्टि! 🎉",
    "book_confirmed_sub": "आपका हीरो रास्ते में है!",
    "book_view_status": "काम की स्थिति देखें →",
    "book_close": "बंद करें",
    "sos_btn": "SOS आपातकाल",
    "sos_title": "🚨 आपातकालीन SOS सहायता",
    "sos_subtitle": "तत्काल घरेलू खतरों के लिए 15 मिनट में प्राथमिकता सेवा",
    "sos_banner": "तुरंत मदद चाहिए? 1-क्लिक सहायता के लिए नीचे चुनें।",
    "sos_dispatch_btn": "प्राथमिकता हीरो भेजें",
    "sos_dispatching": "हीरो भेजा जा रहा है...",
    "sos_unit_active": "24/7 त्वरित प्रतिक्रिया दल सक्रिय",
    "sos_electrician_title": "आपातकालीन इलेक्ट्रीशियन",
    "sos_electrician_desc": "बिजली गुल, एमसीबी ट्रिप, शॉर्ट सर्किट या स्पार्किंग।",
    "sos_gas_title": "गैस रिसाव आपातकाल",
    "sos_gas_desc": "गैस की गंध, रेगुलेटर खराबी या एलपीजी वाल्व की समस्या।",
    "sos_pipe_title": "पाइप फटना",
    "sos_pipe_desc": "पानी का तेज बहाव, पाइप टूटना या मुख्य वाल्व खराब होना।",
    "sos_lock_title": "दरवाजे का ताला बंद",
    "sos_lock_desc": "बाहर बंद हो जाना, चाबी टूटना या इलेक्ट्रॉनिक लॉक खराब होना।",
    "sos_water_title": "पानी का रिसाव व ओवरफ्लो",
    "sos_water_desc": "टंकी ओवरफ्लो, छत से सीलन या नाली जाम।",
    "sos_fire_title": "अग्नि सुरक्षा व धुआं",
    "sos_fire_desc": "तार जलने की गंध या अत्यधिक गर्म उपकरण।",
    "footer_tagline": "आपका भरोसेमंद पड़ोस सेवा प्लेटफॉर्म।",
    "footer_services": "सेवाएं",
    "footer_company": "कंपनी",
    "footer_contact": "संपर्क",
    "footer_legal": "कानूनी",
    "footer_about": "हमारे बारे में",
    "footer_careers": "करियर",
    "footer_blog": "ब्लॉग",
    "footer_press": "प्रेस",
    "footer_privacy": "गोपनीयता नीति",
    "footer_terms": "सेवा की शर्तें",
    "footer_refund": "धनवापसी नीति",
    "footer_rights": "सर्वाधिकार सुरक्षित।",
    "dash_welcome": "वापस स्वागत",
    "dash_active_jobs": "सक्रिय काम",
    "dash_total_spent": "कुल खर्च",
    "dash_total_earned": "कुल कमाई",
    "dash_rating": "रेटिंग",
    "dash_completed": "पूर्ण",
    "dash_pending": "लंबित",
    "dash_accepted": "स्वीकृत",
    "general_loading": "लोड हो रहा है...",
    "general_see_all": "सभी देखें",
    "general_close": "बंद करें",
    "general_save": "सहेजें",
    "general_cancel": "रद्द करें",
    "general_confirm": "पुष्टि करें",
    "general_hrs": "घंटे",
    "general_per_hr": "/घंटा",
    "general_jobs": "काम",
    "general_yrs": "साल",
    "general_today": "आज",
    "general_tomorrow": "कल"
  },
  "mr": {
    "nav_find": "मदतनीस शोधा",
    "nav_how": "कसे काम करते",
    "nav_signin": "साइन इन",
    "nav_notifications": "सूचना",
    "nav_language": "भाषा",
    "nav_dark": "डार्क",
    "nav_light": "लाइट",
    "nav_dashboard": "माझा डॅशबोर्ड",
    "nav_signout": "साइन आउट",
    "nav_mark_all_read": "सर्व वाचले",
    "nav_view_all": "सर्व सूचना पाहा →",
    "notif_1_title": "बुकिंग स्वीकारली! 🎉",
    "notif_1_body": "राजेश कुमारने तुमची विनंती स्वीकारली.",
    "notif_2_title": "पेमेंट यशस्वी ✅",
    "notif_2_body": "₹500 एस्क्रोद्वारे भरले.",
    "notif_3_title": "कामगार येत आहे 🚗",
    "notif_3_body": "सुनीता शर्मा 10 मिनिटांत येईल.",
    "notif_4_title": "काम पूर्ण 🛠️",
    "notif_4_body": "किचन सिंक दुरुस्ती पूर्ण.",
    "notif_5_title": "अनुभव रेट करा ⭐",
    "notif_5_body": "अजय पटेल कसे होते? रिव्यू द्या.",
    "hero_badge": "🏠 50,000+ घरमालकांचा विश्वास",
    "hero_title_1": "तुमच्या परिसरातील",
    "hero_title_2": "फिक्स-इट हिरो",
    "hero_title_3": "एका टॅपवर आहेत",
    "hero_sub": "प्लंबर, इलेक्ट्रिशियन, पेंटर आणि अधिक बुक करा. योग्य दर, सुरक्षित पेमेंट.",
    "hero_search_placeholder": "काय दुरुस्त करायचे? उदा. AC थंड नाही...",
    "hero_search_btn": "हिरो शोधा 🔍",
    "hero_or": "किंवा श्रेणीनुसार ब्राउझ करा",
    "hero_stat_1": "50K+ घरमालक",
    "hero_stat_2": "2,000+ हिरो",
    "hero_stat_3": "4.9★ रेटिंग",
    "landing_cat_badge": "श्रेणी ब्राउझ करा",
    "landing_cat_browse": "ब्राउझ करा",
    "landing_hiw_badge": "हे कसे कार्य करते",
    "landing_top_badge": "टॉप रेटेड",
    "landing_top_explore": "सर्व एक्सप्लोर करा",
    "landing_jobs_badge": "नुकतेच पूर्ण झालेले काम",
    "landing_live_activity": "⚡ थेट क्रियाकलाप",
    "landing_test_badge": "ग्राहकांचे अनुभव",
    "landing_why_badge": "HelperHub का निवडावे",
    "landing_quick_popular": "लोकप्रिय:",
    "landing_card_master": "मास्टर व्यावसायिक",
    "landing_card_reviews": "पुनरावलोकने",
    "landing_card_all_set": "सर्व तयार!",
    "landing_card_done": "बुकिंग पूर्ण झाली",
    "landing_card_verified": "सत्यापित प्रो",
    "landing_card_jobs": "कामे",
    "landing_card_flexible": "लवचिक तास",
    "landing_card_view": "प्रोफाइल पहा",
    "landing_no_helpers": "अद्याप कोणतेही मदतनीस नोंदणीकृत नाहीत",
    "categories_title": "आज काय दुरुस्त करायचे?",
    "categories_sub": "श्रेणी निवडा आणि आम्ही जवळचे हिरो शोधू.",
    "cat_plumber": "प्लंबर",
    "cat_electrician": "इलेक्ट्रिशियन",
    "cat_carpenter": "सुतार",
    "cat_ac": "AC तंत्रज्ञ",
    "cat_painter": "रंगारी",
    "cat_cleaner": "स्वच्छता",
    "cat_mechanic": "मेकॅनिक",
    "cat_gardener": "माळी",
    "cat_repair": "सामान्य दुरुस्ती",
    "how_title": "⭐ HelperHub कसे काम करते",
    "how_sub": "5 सोप्या टप्प्यात सेवा",
    "how_step1_title": "सेवा शोधा 🔍",
    "how_step1_desc": "तुमची गरज टाइप करा किंवा श्रेणीनुसार मदतनीस शोधा.",
    "how_step2_title": "व्यावसायिक बुक करा 🤝",
    "how_step2_desc": "टॉप-रेटेड हिरो निवडा आणि वेळ निश्चित करा.",
    "how_step3_title": "सुरक्षित पेमेंट 🔒",
    "how_step3_desc": "काम पूर्ण होईपर्यंत पैसे एस्क्रोत सुरक्षित.",
    "how_step4_title": "काम पूर्ण 🛠️",
    "how_step4_desc": "हिरो घरी येऊन काम पूर्ण करतो.",
    "how_step5_title": "अनुभव रेट करा ⭐",
    "how_step5_desc": "रिव्यू द्या आणि पेमेंट मोकळे करा.",
    "top_title": "⭐ तुमच्या जवळचे टॉप प्रोफेशनल",
    "top_sub": "सत्यापित, 4.8+ रेटिंग हिरो",
    "top_view_all": "सर्व मदतनीस पाहा →",
    "recent_title": "⚡ नुकतेच पूर्ण झालेले काम",
    "recent_sub": "तुमच्या शहरात सुरू",
    "job_kitchen_sink": "किचन सिंक गळती दुरुस्त केली",
    "job_split_ac": "स्प्लिट एसी बसवला",
    "job_living_room_paint": "दिवाणखाना रंगकाम पूर्ण",
    "job_mcb_tripping": "मेन एमसीबी ट्रिपिंग दुरुस्त केली",
    "job_door_repair": "लाकडी दरवाजा दुरुस्त केला",
    "testimonials_title": "❤️ घरमालक काय म्हणतात",
    "testimonials_sub": "शेजाऱ्यांच्या खऱ्या कथा",
    "test_1_quote": "\"२ मिनिटांत प्लंबर बुक केला, राजेशने येऊन काम चोख केले!\"",
    "test_2_quote": "\"एस्क्रो पेमेंटमुळे १००% सुरक्षितता मिळाली. सर्वोत्तम होम सर्व्हिस ॲप!\"",
    "test_3_quote": "\"पारदर्शक किंमती आणि उत्तम सेवा. इलेक्ट्रिशियन खूप चांगला होता.\"",
    "why_title": "🌟 HelperHub का निवडा?",
    "why_sub": "आम्ही फक्त बुकिंग ॲप नाही — तुमचा विश्वासू नेटवर्क आहोत.",
    "why_1_title": "✔ सत्यापित व्यावसायिक",
    "why_1_desc": "प्रत्येक मदतनीस आधार-सत्यापित आणि तपासलेला.",
    "why_2_title": "✔ सुरक्षित पेमेंट",
    "why_2_desc": "काम मंजूर झाल्यानंतरच पैसे दिले जातात.",
    "why_3_title": "✔ AI किंमत अंदाज",
    "why_3_desc": "बुकिंगपूर्वी योग्य दर जाणून घ्या.",
    "why_4_title": "✔ आपत्कालीन बुकिंग",
    "why_4_desc": "तातडीच्या कामांसाठी २४/७ तत्पर सेवा.",
    "ai_est_title": "AI किंमत अंदाजक",
    "ai_est_badge": "✨ Claude AI द्वारे समर्थित",
    "ai_est_subtitle": "कामाचे वर्णन करा आणि भारतीय बाजारभावानुसार AI अंदाज मिळवा.",
    "ai_est_service_type": "सेवेचा प्रकार",
    "ai_est_city": "शहर",
    "ai_est_job_desc": "कामाचे वर्णन",
    "ai_est_job_desc_hint": "(काय काम करायचे आहे?)",
    "ai_est_placeholder": "उदा. सिंकचे पाईप गळत आहे...",
    "ai_est_price_range": "AI अंदाजित किंमत श्रेणी",
    "ai_est_high_conf": "✓ उच्च विश्वासार्हता",
    "ai_est_med_conf": "~ मध्यम विश्वासार्हता",
    "ai_est_low_conf": "! कमी विश्वासार्हता",
    "ai_est_book_prefix": "बुक करा",
    "ai_est_get_btn": "✨ AI किंमत अंदाज मिळवा",
    "ai_est_loading": "अंदाज काढत आहे...",
    "ai_est_error_min_len": "कृपया किमान १० अक्षरांचे वर्णन द्या.",
    "app_badge": "📱 लवकरच येणार",
    "app_title": "HelperHub तुमच्या खिशात",
    "app_sub": "फोनवरून मदतनीस बुक करा. iOS आणि Android लवकरच!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "१-टॅप आपत्कालीन दुरुस्ती",
    "cta_hire_title": "घर दुरुस्तीसाठी तयार आहात? 🛠️",
    "cta_hire_sub": "हजारो समाधानी घरमालकांशी आजच जोडा!",
    "cta_hire_btn": "आता हिरो शोधा",
    "cta_work_title": "तुम्ही कुशल व्यावसायिक आहात का?",
    "cta_work_sub": "मदतनीस म्हणून सामील व्हा आणि कमाई सुरू करा!",
    "cta_work_btn": "मदतनीस म्हणून सामील व्हा",
    "auth_welcome": "परत स्वागत! 👋",
    "auth_join": "आज HelperHub मध्ये सामील व्हा! 🎉",
    "auth_create_free": "मोफत खाते तयार करा",
    "auth_sign_in_to": "डॅशबोर्डसाठी साइन इन करा",
    "auth_tab_signin": "साइन इन",
    "auth_tab_create": "खाते तयार करा",
    "auth_joining_as": "मी सामील होत आहे...",
    "auth_role_hire": "मला मदत हवी आहे 🏠",
    "auth_role_hire_desc": "घर दुरुस्तीसाठी मदतनीस बुक करा",
    "auth_role_work": "मला काम करायचे आहे 🛠️",
    "auth_role_work_desc": "तुमच्या कौशल्याने मदत करा",
    "auth_full_name": "पूर्ण नाव",
    "auth_email": "ईमेल पत्ता",
    "auth_password": "पासवर्ड",
    "auth_create_btn": "खाते तयार करा 🎉",
    "auth_signin_btn": "साइन इन 🚀",
    "auth_loading": "कृपया प्रतीक्षा करा...",
    "auth_demo": "डेमो खाती:",
    "auth_google_continue": "Google सह सुरू ठेवा",
    "auth_or_email": "किंवा ईमेलसह सुरू ठेवा",
    "otp_title": "ईमेल सत्यापित करा",
    "otp_sent": "६-अंकी कोड पाठवला",
    "otp_verify_btn": "सत्यापित करा! 🎉",
    "otp_verifying": "सत्यापित होत आहे...",
    "otp_back": "मागे",
    "browse_location": "📍 दिल्ली",
    "browse_search": "प्लंबर, इलेक्ट्रिशियन शोधा...",
    "browse_search_placeholder": "प्लंबर, इलेक्ट्रिशियन, पेंटर शोधा...",
    "browse_filters": "फिल्टर",
    "browse_filter_btn": "फिल्टर",
    "browse_results": "मदतनीस जवळ सापडले",
    "browse_no_results": "मदतनीस सापडले नाहीत.",
    "browse_filter_price": "कमाल किंमत",
    "browse_filter_distance": "अंतर",
    "browse_filter_rating": "किमान रेटिंग",
    "browse_filter_experience": "वर्षे अनुभव",
    "browse_filter_language": "भाषा",
    "browse_filter_verified": "फक्त सत्यापित",
    "browse_filter_today": "आज उपलब्ध",
    "browse_filter_emergency": "आपत्कालीन SOS",
    "browse_filter_reset": "रीसेट",
    "browse_book": "आता बुक करा",
    "browse_cat_all": "सर्व",
    "book_step_date": "तारीख",
    "book_step_time": "वेळ",
    "book_step_details": "तपशील",
    "book_step_review": "आढावा",
    "book_step_payment": "पेमेंट",
    "book_choose_date": "तारीख निवडा",
    "book_choose_time": "वेळ स्लॉट निवडा",
    "book_slots_for": "स्लॉट दाखवत आहे",
    "book_booked": "बुक्ड",
    "book_job_title": "कामाचे नाव",
    "book_job_desc": "समस्येचे वर्णन",
    "book_address": "पूर्ण पत्ता",
    "book_upload": "फोटो अपलोड करा (पर्यायी)",
    "book_upload_hint": "ड्रॅग करा किंवा क्लिक करा",
    "book_review_heading": "बुकिंगचा आढावा",
    "book_hero": "हिरो",
    "book_service": "सेवा",
    "book_date": "तारीख",
    "book_time": "वेळ",
    "book_job": "काम",
    "book_address_label": "पत्ता",
    "book_service_fee": "सेवा शुल्क",
    "book_platform_fee": "प्लॅटफॉर्म शुल्क",
    "book_total": "एकूण",
    "book_escrow": "तुमचे पेमेंट एस्क्रोत सुरक्षित आहे.",
    "book_pay_secure": "सुरक्षित पेमेंट",
    "book_card_number": "कार्ड नंबर",
    "book_expiry": "वैधता",
    "book_cvv": "CVV",
    "book_name_card": "कार्डवरील नाव",
    "book_ssl": "२५६-बिट SSL · Stripe",
    "book_pay_btn": "पेमेंट करा",
    "book_securely": "🔒",
    "book_continue": "पुढे",
    "book_back": "मागे",
    "book_cancel": "रद्द करा",
    "book_processing": "प्रक्रिया सुरू...",
    "book_confirmed_title": "बुकिंग पुष्टी! 🎉",
    "book_confirmed_sub": "तुमचा हिरो रस्त्यावर आहे!",
    "book_view_status": "स्थिती पाहा →",
    "book_close": "बंद करा",
    "sos_btn": "SOS आपत्कालीन",
    "sos_title": "🚨 आपत्कालीन SOS मदत",
    "sos_subtitle": "तातडीच्या कामांसाठी १५ मिनिटांत सेवा",
    "sos_banner": "त्वरित मदत हवी आहे? खालील पर्याय निवडा.",
    "sos_dispatch_btn": "तातडीने मदत मागवा",
    "sos_dispatching": "मदत पाठवत आहे...",
    "sos_unit_active": "२४/७ तत्पर दल सक्रिय",
    "sos_electrician_title": "आपत्कालीन इलेक्ट्रिशियन",
    "sos_electrician_desc": "शॉर्ट सर्किट, वीज जाणे किंवा स्पार्क होणे.",
    "sos_gas_title": "गॅस गळती आपत्कालीन",
    "sos_gas_desc": "गॅस वास किंवा रेग्युलेटर बिघाड.",
    "sos_pipe_title": "पाईप फुटणे",
    "sos_pipe_desc": "पाणी गळती किंवा व्हॉल्व बिघाड.",
    "sos_lock_title": "दरवाजा बंद होणे",
    "sos_lock_desc": "किल्ली तुटणे किंवा लॉक खराब होणे.",
    "sos_water_title": "पाणी ओव्हरफ्लो",
    "sos_water_desc": "टाकी वाहणे किंवा नाली तुंबणे.",
    "sos_fire_title": "धूर किंवा स्पार्किंग",
    "sos_fire_desc": "वायर जळण्याचा वास किंवा गरम होणे.",
    "footer_tagline": "तुमचा विश्वासू परिसर सेवा प्लॅटफॉर्म.",
    "footer_services": "सेवा",
    "footer_company": "कंपनी",
    "footer_contact": "संपर्क",
    "footer_legal": "कायदेशीर",
    "footer_about": "आमच्याबद्दल",
    "footer_careers": "करिअर",
    "footer_blog": "ब्लॉग",
    "footer_press": "प्रेस",
    "footer_privacy": "गोपनीयता धोरण",
    "footer_terms": "सेवा अटी",
    "footer_refund": "परतावा धोरण",
    "footer_rights": "सर्व हक्क राखीव.",
    "dash_welcome": "परत स्वागत",
    "dash_active_jobs": "सक्रिय काम",
    "dash_total_spent": "एकूण खर्च",
    "dash_total_earned": "एकूण कमाई",
    "dash_rating": "रेटिंग",
    "dash_completed": "पूर्ण",
    "dash_pending": "प्रलंबित",
    "dash_accepted": "स्वीकारले",
    "general_loading": "लोड होत आहे...",
    "general_see_all": "सर्व पाहा",
    "general_close": "बंद करा",
    "general_save": "जतन करा",
    "general_cancel": "रद्द करा",
    "general_confirm": "पुष्टी करा",
    "general_hrs": "तास",
    "general_per_hr": "/तास",
    "general_jobs": "कामे",
    "general_yrs": "वर्षे",
    "general_today": "आज",
    "general_tomorrow": "उद्या"
  },
  "ml": {
    "nav_find": "സഹായി കണ്ടെത്തുക",
    "nav_how": "എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    "nav_signin": "സൈൻ ഇൻ",
    "nav_notifications": "അറിയിപ്പുകൾ",
    "nav_language": "ഭാഷ",
    "nav_dark": "ഡാർക്ക്",
    "nav_light": "ലൈറ്റ്",
    "nav_dashboard": "എന്റെ ഡാഷ്‌ബോർഡ്",
    "nav_signout": "സൈൻ ഔട്ട്",
    "nav_mark_all_read": "എല്ലാം വായിച്ചു",
    "nav_view_all": "എല്ലാ അറിയിപ്പുകളും →",
    "notif_1_title": "ബുക്കിംഗ് സ്വീകരിച്ചു! 🎉",
    "notif_1_body": "രാജേഷ് കുമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു.",
    "notif_2_title": "പേയ്‌മെന്റ് വിജയകരം ✅",
    "notif_2_body": "₹500 എസ്‌ക്രോ വഴി നൽകി.",
    "notif_3_title": "തൊഴിലാളി വരുന്നു 🚗",
    "notif_3_body": "സുനിത ശർമ്മ 10 മിനിറ്റ് അകലെ.",
    "notif_4_title": "ജോലി പൂർത്തിയായി 🛠️",
    "notif_4_body": "അടുക്കള സിംക്ക് നന്നാക്കൽ പൂർത്തി.",
    "notif_5_title": "അനുഭവം റേറ്റ് ചെയ്യൂ ⭐",
    "notif_5_body": "അജയ് പട്ടേൽ എങ്ങനെയുണ്ടായിരുന്നു?",
    "hero_badge": "🏠 50,000+ വീടുടമകൾ വിശ്വസിക്കുന്നു",
    "hero_title_1": "നിങ്ങളുടെ നാടിന്റെ",
    "hero_title_2": "ഫിക്സ്-ഇറ്റ് ഹീറോകൾ",
    "hero_title_3": "ഒരു ടാപ്പ് അകലെ",
    "hero_sub": "പ്ലംബർ, ഇലക്ട്രീഷ്യൻ, പെയിന്ററെ ബുക്ക് ചെയ്യൂ. സുരക്ഷിത പേയ്‌മെന്റ്.",
    "hero_search_placeholder": "എന്ത് ശരിയാക്കണം? ഉദാ. AC തണുക്കുന്നില്ല...",
    "hero_search_btn": "ഹീറോ കണ്ടെത്തുക 🔍",
    "hero_or": "അല്ലെങ്കിൽ വിഭാഗം തിരഞ്ഞെടുക്കൂ",
    "hero_stat_1": "50K+ വീടുടമകൾ",
    "hero_stat_2": "2,000+ ഹീറോകൾ",
    "hero_stat_3": "4.9★ റേറ്റിംഗ്",
    "landing_cat_badge": "വിഭാഗങ്ങൾ ബ്രൗസ് ചെയ്യുക",
    "landing_cat_browse": "ബ്രൗസ് ചെയ്യുക",
    "landing_hiw_badge": "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    "landing_top_badge": "ടോപ്പ് റേറ്റഡ്",
    "landing_top_explore": "എല്ലാം കാണുക",
    "landing_jobs_badge": "ഇടയ്ക്കിടെ പൂർത്തിയായ ജോലികൾ",
    "landing_live_activity": "⚡ തത്സമയ പ്രവർത്തനം",
    "landing_test_badge": "ഉപഭോക്തൃ അഭിപ്രായങ്ങൾ",
    "landing_why_badge": "എന്തുകൊണ്ട് HelperHub",
    "landing_quick_popular": "ജനപ്രിയം:",
    "landing_card_master": "മാസ്റ്റർ പ്രൊഫഷണൽ",
    "landing_card_reviews": "റിവ്യൂകൾ",
    "landing_card_all_set": "എല്ലാം തയ്യാറാണ്!",
    "landing_card_done": "ബുക്കിംഗ് പൂർത്തിയായി",
    "landing_card_verified": "സ്ഥിരീകരിച്ച പ്രോ",
    "landing_card_jobs": "ജോലികൾ",
    "landing_card_flexible": "സൗകര്യപ്രദ സമയം",
    "landing_card_view": "പ്രൊഫൈൽ കാണുക",
    "landing_no_helpers": "ഹെൽപ്പർമാർ ലഭ്യമല്ല",
    "categories_title": "ഇന്ന് എന്ത് ശരിയാക്കണം?",
    "categories_sub": "ഒരു വിഭാഗം തിരഞ്ഞെടുക്കൂ.",
    "cat_plumber": "പ്ലംബർ",
    "cat_electrician": "ഇലക്ട്രീഷ്യൻ",
    "cat_carpenter": "ആശാരി",
    "cat_ac": "AC ടെക്നീഷ്യൻ",
    "cat_painter": "പെയിന്റർ",
    "cat_cleaner": "ക്ലീനർ",
    "cat_mechanic": "മെക്കാനിക്",
    "cat_gardener": "ഗാർഡനർ",
    "cat_repair": "ജനറൽ റിപ്പയർ",
    "how_title": "⭐ HelperHub എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    "how_sub": "5 ലളിതമായ ഘട്ടങ്ങൾ",
    "how_step1_title": "സേവനം തിരഞ്ഞെടുക്കൂ 🔍",
    "how_step1_desc": "നിങ്ങളുടെ ആവശ്യം ടൈപ്പ് ചെയ്യൂ അല്ലെങ്കിൽ വിഭാഗം നോക്കൂ.",
    "how_step2_title": "പ്രൊഫഷണലിനെ ബുക്ക് ചെയ്യൂ 🤝",
    "how_step2_desc": "ടോപ്-റേറ്റഡ് ഹീറോ തിരഞ്ഞെടുക്കൂ, സമയം നിശ്ചയിക്കൂ.",
    "how_step3_title": "സുരക്ഷിത പേയ്‌മെന്റ് 🔒",
    "how_step3_desc": "ജോലി തീരുന്നതുവരെ പണം എസ്‌ക്രോയിൽ സുരക്ഷിതം.",
    "how_step4_title": "ജോലി പൂർത്തി 🛠️",
    "how_step4_desc": "ഹീറോ വീട്ടിൽ വന്ന് ജോലി പൂർത്തിയാക്കും.",
    "how_step5_title": "അനുഭവം റേറ്റ് ചെയ്യൂ ⭐",
    "how_step5_desc": "റിവ്യൂ നൽകൂ, പേയ്‌മെന്റ് പൂർത്തിയാക്കൂ.",
    "top_title": "⭐ നിങ്ങൾക്ക് അടുത്ത് ടോപ് പ്രൊഫഷണലുകൾ",
    "top_sub": "സത്യസന്ധർ, 4.8+ റേറ്റിംഗ്",
    "top_view_all": "എല്ലാ ഹെൽപ്പർമാരെയും കാണൂ →",
    "recent_title": "⚡ ഇടയ്ക്കിടെ പൂർത്തിയായ ജോലികൾ",
    "recent_sub": "നിങ്ങളുടെ നഗരത്തിൽ ഇപ്പോൾ നടക്കുന്നത്",
    "job_kitchen_sink": "സിങ്ക് ചോർച്ച പരിഹരിച്ചു",
    "job_split_ac": "സ്പ്ലിറ്റ് എസി ഇൻസ്റ്റാൾ ചെയ്തു",
    "job_living_room_paint": "ലിവിംഗ് റൂം പെയിന്റിംഗ് പൂർത്തിയായി",
    "job_mcb_tripping": "എംസിബി ട്രിപ്പിംഗ് പരിഹരിച്ചു",
    "job_door_repair": "വാതിൽ ഫ്രെയിം നന്നാക്കി",
    "testimonials_title": "❤️ വീടുടമകൾ പറയുന്നത്",
    "testimonials_sub": "അയൽക്കാരുടെ യഥാർത്ഥ കഥകൾ",
    "test_1_quote": "\"രണ്ട് മിനിറ്റിനുള്ളിൽ പ്ലംബറെ കിട്ടി, രാജേഷ് വേഗത്തിൽ എത്തി!\"",
    "test_2_quote": "\"എസ്‌ക്രോ പേയ്‌മെന്റ് പൂർണ്ണ സമാധാനം തരുന്നു. മികച്ച ആപ്പ്!\"",
    "test_3_quote": "\"ന്യായമായ നിരക്ക്, മികച്ച സേവനം.\"",
    "why_title": "🌟 HelperHub എന്തുകൊണ്ട്?",
    "why_sub": "ഞങ്ങൾ വിശ്വസ്തരായ ഹെൽപ്പർമാരുടെ ശൃംഖലയാണ്.",
    "why_1_title": "✔ സത്യസന്ധ പ്രൊഫഷണലുകൾ",
    "why_1_desc": "ആധാർ-പരിശോധിച്ചവർ.",
    "why_2_title": "✔ സുരക്ഷിത പേയ്‌മെന്റ്",
    "why_2_desc": "ജോലി കഴിഞ്ഞതിന് ശേഷം മാത്രം പണം നൽകൂ.",
    "why_3_title": "✔ AI വില കണക്ക്",
    "why_3_desc": "ബുക്ക് ചെയ്യുന്നതിന് മുൻപ് ശരിയായ വില അറിയൂ.",
    "why_4_title": "✔ അടിയന്തര ബുക്കിംഗ്",
    "why_4_desc": "24/7 ഹീറോകൾ ലഭ്യമാണ്.",
    "ai_est_title": "AI ചെലവ് കാൽക്കുലേറ്റർ",
    "ai_est_badge": "✨ Claude AI പവർ ചെയ്തത്",
    "ai_est_subtitle": "ജോലി വിവരിക്കൂ, AI വഴി കൃത്യമായ നിരക്ക് അറിയൂ.",
    "ai_est_service_type": "സേവന വിഭാഗം",
    "ai_est_city": "നഗരം",
    "ai_est_job_desc": "ജോലി വിവരണം",
    "ai_est_job_desc_hint": "(എന്താണ് ചെയ്യേണ്ടത്?)",
    "ai_est_placeholder": "ഉദാ: സിങ്ക് പൈപ്പ് ചോരുന്നു...",
    "ai_est_price_range": "AI കണക്കാക്കിയ നിരക്ക്",
    "ai_est_high_conf": "✓ ഉയർന്ന കൃത്യത",
    "ai_est_med_conf": "~ ഇടത്തരം കൃത്യത",
    "ai_est_low_conf": "! കുറഞ്ഞ കൃത്യത",
    "ai_est_book_prefix": "ബുക്ക് ചെയ്യുക",
    "ai_est_get_btn": "✨ AI നിരക്ക് അറിയൂ",
    "ai_est_loading": "നിരക്ക് കണക്കാക്കുന്നു...",
    "ai_est_error_min_len": "ദയവായി കുറഞ്ഞത് 10 അക്ഷരങ്ങളിൽ വിവരിക്കൂ.",
    "app_badge": "📱 ഉടൻ വരുന്നു",
    "app_title": "HelperHub നിങ്ങളുടെ കൈകളിൽ",
    "app_sub": "ഫോണിൽ നിന്ന് എളുപ്പത്തിൽ ബുക്ക് ചെയ്യൂ.",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-ടാപ്പ് എമർജൻസി ഫിക്സ്",
    "cta_hire_title": "വീട് നന്നാക്കാൻ തയ്യാറാണോ? 🛠️",
    "cta_hire_sub": "HelperHub-ൽ ആയിരക്കണക്കിന് വീടുടമകളോടൊപ്പം ചേരൂ!",
    "cta_hire_btn": "ഇപ്പോൾ ഹീറോ കണ്ടെത്തൂ",
    "cta_work_title": "നിങ്ങൾ ഒരു പ്രൊഫഷണലാണോ?",
    "cta_work_sub": "ഹെൽപ്പർ ആയി ചേർന്ന് വരുമാനം നേടൂ!",
    "cta_work_btn": "ഹെൽപ്പർ ആയി ചേരൂ",
    "auth_welcome": "തിരിച്ചു സ്വാഗതം! 👋",
    "auth_join": "HelperHub-ൽ ചേരൂ! 🎉",
    "auth_create_free": "സൗജന്യ അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    "auth_sign_in_to": "ഡാഷ്‌ബോർഡിലേക്ക് സൈൻ ഇൻ ചെയ്യൂ",
    "auth_tab_signin": "സൈൻ ഇൻ",
    "auth_tab_create": "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    "auth_joining_as": "ഞാൻ ചേരുന്നത്...",
    "auth_role_hire": "എനിക്ക് സഹായം വേണം 🏠",
    "auth_role_hire_desc": "വീട് നന്നാക്കാൻ ഹെൽപ്പർ ബുക്ക് ചെയ്യൂ",
    "auth_role_work": "ഞാൻ ജോലി ചെയ്യും 🛠️",
    "auth_role_work_desc": "കഴിവ് ഉപയോഗിച്ച് വരുമാനം നേടൂ",
    "auth_full_name": "മുഴുവൻ പേര്",
    "auth_email": "ഇ-മെയിൽ",
    "auth_password": "പാസ്‌വേഡ്",
    "auth_create_btn": "അക്കൗണ്ട് ഉണ്ടാക്കൂ 🎉",
    "auth_signin_btn": "സൈൻ ഇൻ 🚀",
    "auth_loading": "കാത്തിരിക്കൂ...",
    "auth_demo": "ഡെമോ അക്കൗണ്ടുകൾ:",
    "auth_google_continue": "Google വഴി തുടരുക",
    "auth_or_email": "അല്ലെങ്കിൽ ഇമെയിൽ വഴി",
    "otp_title": "ഇ-മെയിൽ സ്ഥിരീകരിക്കൂ",
    "otp_sent": "6 അക്ക കോഡ് അയച്ചു",
    "otp_verify_btn": "സ്ഥിരീകരിക്കൂ! 🎉",
    "otp_verifying": "സ്ഥിരീകരിക്കുന്നു...",
    "otp_back": "തിരികെ",
    "browse_location": "📍 ഡൽഹി",
    "browse_search": "പ്ലംബർ, ഇലക്ട്രീഷ്യൻ...",
    "browse_search_placeholder": "പ്ലംബർ, ഇലക്ട്രീഷ്യൻ, പെയിന്റർ തിരയുക...",
    "browse_filters": "ഫിൽട്ടറുകൾ",
    "browse_filter_btn": "ഫിൽട്ടറുകൾ",
    "browse_results": "ഹെൽപ്പർമാർ കണ്ടെത്തി",
    "browse_no_results": "ഹെൽപ്പർമാർ ലഭ്യമായില്ല.",
    "browse_filter_price": "പരമാവധി വില",
    "browse_filter_distance": "ദൂരം",
    "browse_filter_rating": "കുറഞ്ഞ റേറ്റിംഗ്",
    "browse_filter_experience": "വർഷത്തെ പരിചയം",
    "browse_filter_language": "ഭാഷ",
    "browse_filter_verified": "സ്ഥിരീകരിച്ചവർ മാത്രം",
    "browse_filter_today": "ഇന്ന് ലഭ്യം",
    "browse_filter_emergency": "അടിയന്തര SOS",
    "browse_filter_reset": "റീസെറ്റ്",
    "browse_book": "ഇപ്പോൾ ബുക്ക് ചെയ്യൂ",
    "browse_cat_all": "എല്ലാം",
    "book_step_date": "തീയതി",
    "book_step_time": "സമയം",
    "book_step_details": "വിവരം",
    "book_step_review": "അവലോകനം",
    "book_step_payment": "പേയ്‌മെന്റ്",
    "book_choose_date": "തീയതി തിരഞ്ഞെടുക്കൂ",
    "book_choose_time": "സമയം തിരഞ്ഞെടുക്കൂ",
    "book_slots_for": "സ്ലോട്ട് കാണിക്കുന്നു",
    "book_booked": "ബുക്ക്ഡ്",
    "book_job_title": "ജോലി പേര്",
    "book_job_desc": "പ്രശ്നം വിവരിക്കൂ",
    "book_address": "പൂർണ്ണ വിലാസം",
    "book_upload": "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യൂ",
    "book_upload_hint": "ഇവിടെ ക്ലിക്ക് ചെയ്യൂ",
    "book_review_heading": "ബുക്കിംഗ് അവലോകനം",
    "book_hero": "ഹീറോ",
    "book_service": "സേവനം",
    "book_date": "തീയതി",
    "book_time": "സമയം",
    "book_job": "ജോലി",
    "book_address_label": "വിലാസം",
    "book_service_fee": "സേവന ഫീ",
    "book_platform_fee": "പ്ലാറ്റ്ഫോം ഫീ",
    "book_total": "ആകെ",
    "book_escrow": "പണം എസ്‌ക്രോയിൽ സുരക്ഷിതം.",
    "book_pay_secure": "സുരക്ഷിത പേയ്‌മെന്റ്",
    "book_card_number": "കാർഡ് നമ്പർ",
    "book_expiry": "കാലഹരണ തീയതി",
    "book_cvv": "CVV",
    "book_name_card": "കാർഡിലെ പേര്",
    "book_ssl": "256-ബിറ്റ് SSL · Stripe",
    "book_pay_btn": "പണം നൽകൂ",
    "book_securely": "🔒",
    "book_continue": "തുടരൂ",
    "book_back": "തിരികെ",
    "book_cancel": "റദ്ദാക്കുക",
    "book_processing": "പ്രോസസ്സ് ചെയ്യുന്നു...",
    "book_confirmed_title": "ബുക്കിംഗ് സ്ഥിരീകരിച്ചു! 🎉",
    "book_confirmed_sub": "ഹീറോ ഉടൻ എത്തും!",
    "book_view_status": "വിവരങ്ങൾ കാണൂ →",
    "book_close": "അടയ്ക്കൂ",
    "sos_btn": "SOS അടിയന്തരം",
    "sos_title": "🚨 അടിയന്തര SOS സഹായം",
    "sos_subtitle": "അടിയന്തര ആവശ്യങ്ങൾക്ക് 15 മിനിറ്റിൽ സഹായം",
    "sos_banner": "ഉടൻ സഹായം വേണോ? താഴെ തിരഞ്ഞെടുക്കൂ.",
    "sos_dispatch_btn": "ഹീറോയെ അയക്കൂ",
    "sos_dispatching": "ഹീറോയെ അയക്കുന്നു...",
    "sos_unit_active": "24/7 ദ്രുത പ്രതികരണ വിഭാഗം സജീവം",
    "sos_electrician_title": "എമർജൻസി ഇലക്ട്രീഷ്യൻ",
    "sos_electrician_desc": "വൈദ്യുതി തടസ്സം, സ്പാർക്കിംഗ് അല്ലെങ്കിൽ ഷോർട്ട് സർക്യൂട്ട്.",
    "sos_gas_title": "ഗ്യാസ് ചോർച്ച",
    "sos_gas_desc": "ഗ്യാസ് മണം അല്ലെങ്കിൽ റെഗുലേറ്റർ തകരാർ.",
    "sos_pipe_title": "പൈപ്പ് പൊട്ടൽ",
    "sos_pipe_desc": "വെള്ളപ്പൊക്കം അല്ലെങ്കിൽ പൈപ്പ് തകരാർ.",
    "sos_lock_title": "ഡോർ ലോക്കൗട്ട്",
    "sos_lock_desc": "താക്കോൽ നഷ്ടപ്പെടൽ അല്ലെങ്കിൽ പൂട്ട് തകരാർ.",
    "sos_water_title": "വെള്ളം ചോർച്ച",
    "sos_water_desc": "ടാങ്ക് ഓവർഫ്ലോ അല്ലെങ്കിൽ ചോർച്ച.",
    "sos_fire_title": "തീപിടുത്ത അപായം",
    "sos_fire_desc": "വയർ കരിയുന്ന മണം അല്ലെങ്കിൽ പുക.",
    "footer_tagline": "വിശ്വസ്ത അയൽ സേവന പ്ലാറ്റ്ഫോം.",
    "footer_services": "സേവനങ്ങൾ",
    "footer_company": "കമ്പനി",
    "footer_contact": "ബന്ധപ്പെടുക",
    "footer_legal": "നിയമപരം",
    "footer_about": "ഞങ്ങളെ കുറിച്ച്",
    "footer_careers": "കരിയർ",
    "footer_blog": "ബ്ലോഗ്",
    "footer_press": "പ്രസ്",
    "footer_privacy": "സ്വകാര്യത നയം",
    "footer_terms": "നിബന്ധനകൾ",
    "footer_refund": "റീഫണ്ട് നയം",
    "footer_rights": "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
    "dash_welcome": "തിരിച്ചു സ്വാഗതം",
    "dash_active_jobs": "സജീവ ജോലികൾ",
    "dash_total_spent": "ആകെ ചെലവ്",
    "dash_total_earned": "ആകെ സമ്പാദ്യം",
    "dash_rating": "റേറ്റിംഗ്",
    "dash_completed": "പൂർത്തിയായി",
    "dash_pending": "തീരുമാനമാകാത്തവ",
    "dash_accepted": "സ്വീകരിച്ചു",
    "general_loading": "ലോഡ് ചെയ്യുന്നു...",
    "general_see_all": "എല്ലാം കാണൂ",
    "general_close": "അടയ്ക്കൂ",
    "general_save": "സേവ്",
    "general_cancel": "റദ്ദാക്കൂ",
    "general_confirm": "സ്ഥിരീകരിക്കൂ",
    "general_hrs": "മണിക്കൂർ",
    "general_per_hr": "/മണിക്കൂർ",
    "general_jobs": "ജോലികൾ",
    "general_yrs": "വർഷം",
    "general_today": "ഇന്ന്",
    "general_tomorrow": "നാളെ"
  },
  "te": {
    "nav_find": "సహాయకుడిని కనుగొనండి",
    "nav_how": "ఎలా పని చేస్తుంది",
    "nav_signin": "సైన్ ఇన్",
    "nav_notifications": "నోటిఫికేషన్లు",
    "nav_language": "భాష",
    "nav_dark": "డార్క్",
    "nav_light": "లైట్",
    "nav_dashboard": "నా డాష్‌బోర్డ్",
    "nav_signout": "సైన్ అవుట్",
    "nav_mark_all_read": "అన్నీ చదివాను",
    "nav_view_all": "అన్ని నోటిఫికేషన్లు →",
    "notif_1_title": "బుకింగ్ అంగీకరించారు! 🎉",
    "notif_1_body": "రాజేశ్ కుమార్ మీ అభ్యర్థనను అంగీకరించారు.",
    "notif_2_title": "పేమెంట్ విజయవంతమైంది ✅",
    "notif_2_body": "₹500 ఎస్క్రో ద్వారా చెల్లించారు.",
    "notif_3_title": "కార్మికుడు వస్తున్నారు 🚗",
    "notif_3_body": "సునీత శర్మ 10 నిమిషాల్లో వస్తారు.",
    "notif_4_title": "పని పూర్తయింది 🛠️",
    "notif_4_body": "కిచెన్ సింక్ రిపేర్ పూర్తి.",
    "notif_5_title": "అనుభవాన్ని రేట్ చేయండి ⭐",
    "notif_5_body": "అజయ్ పటేల్ ఎలా ఉన్నారు?",
    "hero_badge": "🏠 50,000+ ఇల్లు యజమానులు నమ్ముతున్నారు",
    "hero_title_1": "మీ పరిసరాల",
    "hero_title_2": "ఫిక్స్-ఇట్ హీరోలు",
    "hero_title_3": "ఒక్క టాప్‌లో",
    "hero_sub": "ప్లంబర్, ఎలక్ట్రీషియన్, పెయింటర్ మరియు మరిన్నింటిని బుక్ చేయండి. సురక్షిత చెల్లింపులు.",
    "hero_search_placeholder": "ఏమి రిపేర్ చేయాలి? ఉదా. AC పని చేయట్లేదు...",
    "hero_search_btn": "హీరోను కనుగొనండి 🔍",
    "hero_or": "లేదా వర్గం ద్వారా బ్రౌజ్ చేయండి",
    "hero_stat_1": "50K+ ఇల్లు యజమానులు",
    "hero_stat_2": "2,000+ హీరోలు",
    "hero_stat_3": "4.9★ రేటింగ్",
    "landing_cat_badge": "కేటగిరీలు బ్రౌజ్ చేయండి",
    "landing_cat_browse": "బ్రౌజ్ చేయండి",
    "landing_hiw_badge": "ఇది ఎలా పనిచేస్తుంది",
    "landing_top_badge": "టాప్ రేటెడ్",
    "landing_top_explore": "అన్నీ చూడండి",
    "landing_jobs_badge": "ఇటీవల పూర్తయిన పనులు",
    "landing_live_activity": "⚡ ప్రత్యక్ష కార్యాచరణ",
    "landing_test_badge": "కస్టమర్ అనుభవాలు",
    "landing_why_badge": "HelperHub ఎందుకు ఎంచుకోవాలి",
    "landing_quick_popular": "ప్రసిద్ధమైనవి:",
    "landing_card_master": "మాస్టర్ ప్రొఫెషనల్",
    "landing_card_reviews": "సమీక్షలు",
    "landing_card_all_set": "అంతా సిద్ధం!",
    "landing_card_done": "బుకింగ్ పూర్తయింది",
    "landing_card_verified": "ధృవీకరించిన ప్రొఫెషనల్",
    "landing_card_jobs": "పనులు",
    "landing_card_flexible": "సౌకర్యవంతమైన గంటలు",
    "landing_card_view": "ప్రొఫైల్ చూడండి",
    "landing_no_helpers": "హెల్పర్లు ఇంకా నమోదు కాలేదు",
    "categories_title": "ఈ రోజు ఏమి రిపేర్ చేయాలి?",
    "categories_sub": "వర్గం ఎంచుకోండి, మేము హీరోలను కనుగొంటాము.",
    "cat_plumber": "ప్లంబర్",
    "cat_electrician": "ఎలక్ట్రీషియన్",
    "cat_carpenter": "వడ్రంగి",
    "cat_ac": "AC టెక్నీషియన్",
    "cat_painter": "పెయింటర్",
    "cat_cleaner": "క్లీనర్",
    "cat_mechanic": "మెకానిక్",
    "cat_gardener": "తోటమాలి",
    "cat_repair": "సాధారణ మరమ్మతు",
    "how_title": "⭐ HelperHub ఎలా పని చేస్తుంది",
    "how_sub": "5 సులభమైన దశలు",
    "how_step1_title": "సేవ వెతకండి 🔍",
    "how_step1_desc": "మీ అవసరాన్ని టైప్ చేయండి లేదా వర్గం ద్వారా వెతకండి.",
    "how_step2_title": "నిపుణుడిని బుక్ చేయండి 🤝",
    "how_step2_desc": "టాప్-రేటెడ్ హీరోని ఎంచుకోండి, సమయం నిర్ణయించండి.",
    "how_step3_title": "సురక్షిత పేమెంట్ 🔒",
    "how_step3_desc": "పని పూర్తయ్యే వరకు నగదు ఎస్క్రోలో భద్రంగా ఉంటుంది.",
    "how_step4_title": "పని పూర్తి 🛠️",
    "how_step4_desc": "హీరో మీ ఇంటికి వచ్చి పని చేస్తారు.",
    "how_step5_title": "అనుభవాన్ని రేట్ చేయండి ⭐",
    "how_step5_desc": "రివ్యూ ఇవ్వండి, పేమెంట్ పంపండి.",
    "top_title": "⭐ మీ దగ్గరి టాప్ నిపుణులు",
    "top_sub": "ధృవీకరించబడిన, 4.8+ రేటింగ్",
    "top_view_all": "అందరు సహాయకులను చూడండి →",
    "recent_title": "⚡ ఇటీవల పూర్తయిన పనులు",
    "recent_sub": "మీ నగరంలో జరిగే తాజా పనులు",
    "job_kitchen_sink": "సింక్ లీకేజ్ పరిష్కరించబడింది",
    "job_split_ac": "స్ప్లిట్ ఏసీ అమర్చబడింది",
    "job_living_room_paint": "లివింగ్ రూమ్ పెయింటింగ్ పూర్తి",
    "job_mcb_tripping": "మెయిన్ ఎంసీబీ సమస్య పరిష్కారం",
    "job_door_repair": "చెక్క తలుపు రిపేర్ పూర్తి",
    "testimonials_title": "❤️ ఇల్లు యజమానులు ఏమి చెప్తున్నారు",
    "testimonials_sub": "పొరుగువారి నిజమైన కథలు",
    "test_1_quote": "\"2 నిమిషాల్లో ప్లంబర్‌ను బుక్ చేశాను, రాజేష్ త్వరగా వచ్చి పని పూర్తి చేశాడు!\"",
    "test_2_quote": "\"ఎస్క్రో రక్షణ నాకు పూర్తి మనశ్శాంతిని ఇచ్చింది. ఉత్తమ యాప్!\"",
    "test_3_quote": "\"స్పష్టమైన ధరలు మరియు మంచి సేవ. చాలా సంతోషంగా ఉంది.\"",
    "why_title": "🌟 HelperHub ఎందుకు ఎంచుకోవాలి?",
    "why_sub": "మేము మీ పరిసరాల నమ్మకమైన సేవా వేదిక.",
    "why_1_title": "✔ ధృవీకరించబడిన నిపుణులు",
    "why_1_desc": "ఆధార్ ధృవీకరించబడింది.",
    "why_2_title": "✔ సురక్షిత చెల్లింపులు",
    "why_2_desc": "పని తర్వాత మాత్రమే పేమెంట్ విడుదల.",
    "why_3_title": "✔ AI ధర అంచనా",
    "why_3_desc": "ముందుగానే సరసమైన ధర తెలుసుకోండి.",
    "why_4_title": "✔ అత్యవసర బుకింగ్",
    "why_4_desc": "24/7 అత్యవసర సేవలు అందుబాటులో ఉన్నాయి.",
    "ai_est_title": "AI ధర అంచనా వేదిక",
    "ai_est_badge": "✨ Claude AI ద్వారా ఆధారితం",
    "ai_est_subtitle": "మీ పనిని వివరించండి మరియు ఖచ్చితమైన AI మార్కెట్ రేట్లను పొందండి.",
    "ai_est_service_type": "సేవ రకం",
    "ai_est_city": "నగరం",
    "ai_est_job_desc": "పని వివరణ",
    "ai_est_job_desc_hint": "(ఏమి చేయాలి?)",
    "ai_est_placeholder": "ఉదా: సింక్ పైపు లీక్ అవుతోంది...",
    "ai_est_price_range": "AI అంచనా వేసిన ధర",
    "ai_est_high_conf": "✓ అధిక ఖచ్చితత్వం",
    "ai_est_med_conf": "~ మధ్యస్థ ఖచ్చితత్వం",
    "ai_est_low_conf": "! తక్కువ ఖచ్చితత్వం",
    "ai_est_book_prefix": "బుక్ చేయండి",
    "ai_est_get_btn": "✨ AI ధర అంచనా పొందండి",
    "ai_est_loading": "ధర అంచనా వేస్తోంది...",
    "ai_est_error_min_len": "దయచేసి కనీసం 10 అక్షరాల వివరణ ఇవ్వండి.",
    "app_badge": "📱 త్వరలో రానుంది",
    "app_title": "HelperHub మీ జేబులో",
    "app_sub": "ఫోన్ నుండి హెల్పర్ బుక్ చేయండి. iOS మరియు Android త్వరలో!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-టాప్ అత్యవసర రిపేర్",
    "cta_hire_title": "మరమ్మతులకు సిద్ధంగా ఉన్నారా? 🛠️",
    "cta_hire_sub": "వేలాది మంది ఇంటి యజమానులతో చేరండి!",
    "cta_hire_btn": "ఇప్పుడే మీ హీరోని ఎంచుకోండి",
    "cta_work_title": "మీరు నైపుణ్యం గల నిపుణుడా?",
    "cta_work_sub": "హెల్పర్‌గా చేరండి మరియు సంపాదించండి!",
    "cta_work_btn": "హెల్పర్‌గా చేరండి",
    "auth_welcome": "తిరిగి స్వాగతం! 👋",
    "auth_join": "HelperHub లో చేరండి! 🎉",
    "auth_create_free": "ఉచిత ఖాతా సృష్టించండి",
    "auth_sign_in_to": "డాష్‌బోర్డ్ యాక్సెస్ చేయండి",
    "auth_tab_signin": "సైన్ ఇన్",
    "auth_tab_create": "ఖాతా సృష్టించండి",
    "auth_joining_as": "నేను చేరుతున్నాను...",
    "auth_role_hire": "నాకు సహాయం కావాలి 🏠",
    "auth_role_hire_desc": "ఇంటి మరమ్మతులకు హెల్పర్ బుక్ చేయండి",
    "auth_role_work": "నేను పని చేస్తాను 🛠️",
    "auth_role_work_desc": "మీ నైపుణ్యంతో సంపాదించండి",
    "auth_full_name": "పూర్తి పేరు",
    "auth_email": "ఇమెయిల్",
    "auth_password": "పాస్‌వర్డ్",
    "auth_create_btn": "ఖాతా సృష్టించండి 🎉",
    "auth_signin_btn": "సైన్ ఇన్ 🚀",
    "auth_loading": "దయచేసి వేచి ఉండండి...",
    "auth_demo": "డెమో ఖాతాలు:",
    "auth_google_continue": "Google తో కొనసాగించండి",
    "auth_or_email": "లేదా ఇమెయిల్‌తో",
    "otp_title": "ఇమెయిల్ ధృవీకరించండి",
    "otp_sent": "6 అంకెల కోడ్ పంపబడింది",
    "otp_verify_btn": "ధృవీకరించండి! 🎉",
    "otp_verifying": "ధృవీకరిస్తున్నారు...",
    "otp_back": "వెనుకకు",
    "browse_location": "📍 ఢిల్లీ",
    "browse_search": "ప్లంబర్, ఎలక్ట్రీషియన్...",
    "browse_search_placeholder": "ప్లంబర్, ఎలక్ట్రీషియన్, పెయింటర్ వెతకండి...",
    "browse_filters": "ఫిల్టర్లు",
    "browse_filter_btn": "ఫిల్టర్లు",
    "browse_results": "హెల్పర్లు దొరికారు",
    "browse_no_results": "హెల్పర్లు కనుగొనబడలేదు.",
    "browse_filter_price": "గరిష్ఠ ధర",
    "browse_filter_distance": "దూరం",
    "browse_filter_rating": "కనీస రేటింగ్",
    "browse_filter_experience": "సంవత్సరాల అనుభవం",
    "browse_filter_language": "భాష",
    "browse_filter_verified": "ధృవీకరించిన మాత్రమే",
    "browse_filter_today": "ఇవాళ అందుబాటులో",
    "browse_filter_emergency": "అత్యవసర SOS",
    "browse_filter_reset": "రీసెట్",
    "browse_book": "ఇప్పుడే బుక్ చేయండి",
    "browse_cat_all": "అన్నీ",
    "book_step_date": "తేదీ",
    "book_step_time": "సమయం",
    "book_step_details": "వివరాలు",
    "book_step_review": "సమీక్ష",
    "book_step_payment": "పేమెంట్",
    "book_choose_date": "తేదీ ఎంచుకోండి",
    "book_choose_time": "సమయం ఎంచుకోండి",
    "book_slots_for": "స్లాట్లు చూపిస్తోంది",
    "book_booked": "బుక్డ్",
    "book_job_title": "పని పేరు",
    "book_job_desc": "సమస్య వివరణ",
    "book_address": "పూర్తి చిరునామా",
    "book_upload": "ఫోటోలు అప్‌లోడ్ చేయండి",
    "book_upload_hint": "ఇక్కడ క్లిక్ చేయండి",
    "book_review_heading": "బుకింగ్ సమీక్ష",
    "book_hero": "హీరో",
    "book_service": "సేవ",
    "book_date": "తేదీ",
    "book_time": "సమయం",
    "book_job": "పని",
    "book_address_label": "చిరునామా",
    "book_service_fee": "సేవ రుసుము",
    "book_platform_fee": "ప్లాట్‌ఫారం రుసుము",
    "book_total": "మొత్తం",
    "book_escrow": "మీ పేమెంట్ ఎస్క్రోలో సురక్షితంగా ఉంది.",
    "book_pay_secure": "సురక్షిత పేమెంట్",
    "book_card_number": "కార్డ్ నంబర్",
    "book_expiry": "గడువు తేదీ",
    "book_cvv": "CVV",
    "book_name_card": "కార్డ్‌పై పేరు",
    "book_ssl": "256-బిట్ SSL · Stripe",
    "book_pay_btn": "చెల్లించండి",
    "book_securely": "🔒",
    "book_continue": "కొనసాగించండి",
    "book_back": "వెనుకకు",
    "book_cancel": "రద్దు చేయండి",
    "book_processing": "ప్రాసెస్ అవుతోంది...",
    "book_confirmed_title": "బుకింగ్ నిర్ధారించబడింది! 🎉",
    "book_confirmed_sub": "మీ హీరో దారిలో ఉన్నారు!",
    "book_view_status": "స్థితి చూడండి →",
    "book_close": "మూయండి",
    "sos_btn": "SOS అత్యవసరం",
    "sos_title": "🚨 అత్యవసర SOS సహాయం",
    "sos_subtitle": "అత్యవసర సమస్యలకు 15 నిమిషాల్లో సహాయం",
    "sos_banner": "వెంటనే సహాయం కావాలా? కింద ఎంచుకోండి.",
    "sos_dispatch_btn": "హీరోను పంపండి",
    "sos_dispatching": "హీరోను పంపుతోంది...",
    "sos_unit_active": "24/7 స్పందన విభాగం సిద్ధంగా ఉంది",
    "sos_electrician_title": "ఎమర్జెన్సీ ఎలక్ట్రీషియన్",
    "sos_electrician_desc": "విద్యుత్ నిలిచిపోవడం, షార్ట్ సర్క్యూట్ లేదా స్పార్క్.",
    "sos_gas_title": "గ్యాస్ లీక్ సమస్య",
    "sos_gas_desc": "గ్యాస్ వాసన లేదా రెగ్యులేటర్ లోపం.",
    "sos_pipe_title": "పైపు పగలడం",
    "sos_pipe_desc": "నీరు లీక్ కావడం లేదా పైపు దెబ్బతినడం.",
    "sos_lock_title": "తాళం ఇరుక్కోవడం",
    "sos_lock_desc": "తాళం చెవి విరగడం లేదా లాక్ పనిచేయకపోవడం.",
    "sos_water_title": "నీటి లీకేజ్ సమస్య",
    "sos_water_desc": "ఓవర్‌ఫ్లో లేదా సీలింగ్ లీకేజ్.",
    "sos_fire_title": "వైర్ మంటలు లేదా పొగ",
    "sos_fire_desc": "వైరింగ్ కాలే వాసన లేదా వేడెక్కడం.",
    "footer_tagline": "విశ్వసనీయ పరిసర సేవా వేదిక.",
    "footer_services": "సేవలు",
    "footer_company": "కంపెనీ",
    "footer_contact": "సంప్రదించండి",
    "footer_legal": "చట్టపరమైన",
    "footer_about": "మా గురించి",
    "footer_careers": "ఉద్యోగాలు",
    "footer_blog": "బ్లాగ్",
    "footer_press": "ప్రెస్",
    "footer_privacy": "గోప్యతా విధానం",
    "footer_terms": "నిబంధనలు",
    "footer_refund": "రీఫండ్ విధానం",
    "footer_rights": "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
    "dash_welcome": "తిరిగి స్వాగతం",
    "dash_active_jobs": "యాక్టివ్ పనులు",
    "dash_total_spent": "మొత్తం ఖర్చు",
    "dash_total_earned": "మొత్తం ఆదాయం",
    "dash_rating": "రేటింగ్",
    "dash_completed": "పూర్తియినవి",
    "dash_pending": "పెండింగ్",
    "dash_accepted": "అంగీకరించబడినవి",
    "general_loading": "లోడ్ అవుతోంది...",
    "general_see_all": "అన్నీ చూడండి",
    "general_close": "మూయండి",
    "general_save": "సేవ్",
    "general_cancel": "రద్దు",
    "general_confirm": "ధృవీకరించండి",
    "general_hrs": "గంటలు",
    "general_per_hr": "/గంట",
    "general_jobs": "పనులు",
    "general_yrs": "సంవత్సరాలు",
    "general_today": "ఈ రోజు",
    "general_tomorrow": "రేపు"
  },
  "ta": {
    "nav_find": "உதவியாளரை கண்டுபிடி",
    "nav_how": "எப்படி செயல்படுகிறது",
    "nav_signin": "உள்நுழை",
    "nav_notifications": "அறிவிப்புகள்",
    "nav_language": "மொழி",
    "nav_dark": "இருண்டது",
    "nav_light": "வெளிச்சம்",
    "nav_dashboard": "என் டாஷ்போர்டு",
    "nav_signout": "வெளியேறு",
    "nav_mark_all_read": "அனைத்தும் படித்தது",
    "nav_view_all": "அனைத்து அறிவிப்புகளும் →",
    "notif_1_title": "முன்பதிவு ஏற்கப்பட்டது! 🎉",
    "notif_1_body": "ராஜேஷ் குமார் உங்கள் கோரிக்கையை ஏற்றுக்கொண்டார்.",
    "notif_2_title": "பணம் செலுத்தப்பட்டது ✅",
    "notif_2_body": "₹500 எஸ்க்ரோ மூலம் செலுத்தப்பட்டது.",
    "notif_3_title": "தொழிலாளர் வருகிறார் 🚗",
    "notif_3_body": "சுனீதா சர்மா 10 நிமிடங்களில் வருவார்.",
    "notif_4_title": "வேலை முடிந்தது 🛠️",
    "notif_4_body": "சமையலறை தொட்டி பழுதுபார்ப்பு முடிந்தது.",
    "notif_5_title": "அனுபவத்தை மதிப்பீடு செய்யுங்கள் ⭐",
    "notif_5_body": "அஜய் பட்டேல் எப்படி இருந்தார்?",
    "hero_badge": "🏠 50,000+ வீட்டு உரிமையாளர்கள் நம்புகிறார்கள்",
    "hero_title_1": "உங்கள் அக்கம்பக்கத்தின்",
    "hero_title_2": "ஃபிக்ஸ்-இட் ஹீரோக்கள்",
    "hero_title_3": "ஒரே தட்டில்",
    "hero_sub": "பிளம்பர், எலக்ட்ரீஷியன், பெயிண்டர் முன்பதிவு செய்யுங்கள். பாதுகாப்பான பணம்.",
    "hero_search_placeholder": "என்ன சரிசெய்ய வேண்டும்? எ.கா. AC வேலை செய்யவில்லை...",
    "hero_search_btn": "ஹீரோவை கண்டுபிடி 🔍",
    "hero_or": "அல்லது வகையைத் தேர்ந்தெடுங்கள்",
    "hero_stat_1": "50K+ வீட்டு உரிமையாளர்கள்",
    "hero_stat_2": "2,000+ ஹீரோக்கள்",
    "hero_stat_3": "4.9★ மதிப்பீடு",
    "landing_cat_badge": "வகைகளை உலாவுங்கள்",
    "landing_cat_browse": "உலாவு",
    "landing_hiw_badge": "இது எவ்வாறு செயல்படுகிறது",
    "landing_top_badge": "சிறந்த மதிப்பீடு பெற்றவர்கள்",
    "landing_top_explore": "அனைத்தையும் காண்க",
    "landing_jobs_badge": "சமீபத்தில் முடிந்த வேலைகள்",
    "landing_live_activity": "⚡ நேரலை செயல்பாடு",
    "landing_test_badge": "வாடிக்கையாளர் கருத்துகள்",
    "landing_why_badge": "HelperHub ஏன் தேர்வு செய்ய வேண்டும்",
    "landing_quick_popular": "பிரபலமானவை:",
    "landing_card_master": "முக்கிய நிபுணர்",
    "landing_card_reviews": "மதிப்பாய்வுகள்",
    "landing_card_all_set": "எல்லாம் தயார்!",
    "landing_card_done": "முன்பதிவு முடிந்தது",
    "landing_card_verified": "சரிபார்க்கப்பட்ட புரோ",
    "landing_card_jobs": "வேலைகள்",
    "landing_card_flexible": "நெகிழ்வான நேரம்",
    "landing_card_view": "சுயவிவரத்தைக் காண்க",
    "landing_no_helpers": "உதவியாளர்கள் இன்னும் பதிவு செய்யவில்லை",
    "categories_title": "இன்று என்ன சரிசெய்ய வேண்டும்?",
    "categories_sub": "ஒரு வகையைத் தேர்ந்தெடுங்கள், ஹீரோக்களைக் கண்டுபிடிப்போம்.",
    "cat_plumber": "பிளம்பர்",
    "cat_electrician": "எலக்ட்ரீஷியன்",
    "cat_carpenter": "தச்சர்",
    "cat_ac": "AC தொழில்நுட்பவியலாளர்",
    "cat_painter": "பெயிண்டர்",
    "cat_cleaner": "சுத்தம் செய்பவர்",
    "cat_mechanic": "மெக்கானிக்",
    "cat_gardener": "தோட்டக்காரர்",
    "cat_repair": "பொது பழுதுபார்ப்பு",
    "how_title": "⭐ HelperHub எப்படி செயல்படுகிறது",
    "how_sub": "5 எளிய படிகளில்",
    "how_step1_title": "சேவையை தேடு 🔍",
    "how_step1_desc": "உங்கள் தேவையை தட்டச்சு செய்யுங்கள் அல்லது வகையைத் தேர்ந்தெடுக்கவும்.",
    "how_step2_title": "நிபுணரை முன்பதிவு செய்யுங்கள் 🤝",
    "how_step2_desc": "சிறந்த ஹீரோவை தேர்ந்தெடுத்து நேரம் ஒதுக்குங்கள்.",
    "how_step3_title": "பாதுகாப்பான பணம் 🔒",
    "how_step3_desc": "வேலை முடியும் வரை பணம் எஸ்க்ரோவில் பாதுகாப்பாக இருக்கும்.",
    "how_step4_title": "வேலை முடிந்தது 🛠️",
    "how_step4_desc": "ஹீரோ உங்கள் வீட்டில் வேலை செய்வார்.",
    "how_step5_title": "அனுபவத்தை மதிப்பீடு செய்யுங்கள் ⭐",
    "how_step5_desc": "மதிப்பாய்வு கொடுங்கள், பணம் செலுத்தவும்.",
    "top_title": "⭐ உங்களுக்கு அருகில் சிறந்த நிபுணர்கள்",
    "top_sub": "சரிபார்க்கப்பட்டவர்கள், 4.8+ மதிப்பீடு",
    "top_view_all": "அனைத்து உதவியாளர்களையும் காண →",
    "recent_title": "⚡ சமீபத்தில் முடிந்த வேலைகள்",
    "recent_sub": "உங்கள் நகரில் நடக்கும் வேலைகள்",
    "job_kitchen_sink": "சமையலறை தொட்டி கசிவு சரிசெய்யப்பட்டது",
    "job_split_ac": "ஸ்பிளிட் ஏசி பொருத்தப்பட்டது",
    "job_living_room_paint": "வரவேற்பறை வர்ணம் பூசுதல் முடிந்தது",
    "job_mcb_tripping": "மின்சார எம்சிபி பிரச்சனை சரிசெய்யப்பட்டது",
    "job_door_repair": "மரக் கதவு பழுதுபார்ப்பு முடிந்தது",
    "testimonials_title": "❤️ வீட்டு உரிமையாளர்கள் என்ன சொல்கிறார்கள்",
    "testimonials_sub": "உண்மையான கதைகள்",
    "test_1_quote": "\"2 நிமிடங்களில் பிளம்பரை முன்பதிவு செய்தேன், ராஜேஷ் விரைந்து வந்தார்!\"",
    "test_2_quote": "\"எஸ்க்ரோ பாதுகாப்பு முழு மன அமைதியை அளித்தது. சிறந்த செயலி!\"",
    "test_3_quote": "\"நியாயமான விலை, சிறந்த சேவை.\"",
    "why_title": "🌟 HelperHub ஏன் தேர்வு செய்யலாம்?",
    "why_sub": "நாங்கள் உங்கள் அக்கம்பக்கத்தின் நம்பகமான நெட்வொர்க்.",
    "why_1_title": "✔ சரிபார்க்கப்பட்ட நிபுணர்கள்",
    "why_1_desc": "ஆதார் சரிபார்க்கப்பட்டவர்கள்.",
    "why_2_title": "✔ பாதுகாப்பான பணம்",
    "why_2_desc": "வேலை முடிந்த பிறகு மட்டுமே பணம் வழங்கப்படும்.",
    "why_3_title": "✔ AI விலை கணிப்பு",
    "why_3_desc": "முன்பதிவுக்கு முன்பே நியாயமான விலை தெரியும்.",
    "why_4_title": "✔ அவசர முன்பதிவு",
    "why_4_desc": "24/7 அவசர சேவைகள் கிடைக்கும்.",
    "ai_est_title": "AI விலை மதிப்பீட்டாளர்",
    "ai_est_badge": "✨ Claude AI மூலம் இயக்கப்படுகிறது",
    "ai_est_subtitle": "வேலையை விவரியுங்கள், சந்தை விலையின்படி AI கணிப்பைப் பெறுங்கள்.",
    "ai_est_service_type": "சேவை வகை",
    "ai_est_city": "நகரம்",
    "ai_est_job_desc": "வேலை விவரம்",
    "ai_est_job_desc_hint": "(என்ன செய்ய வேண்டும்?)",
    "ai_est_placeholder": "எ.கா: சமையலறை பைப் கசிகிறது...",
    "ai_est_price_range": "AI கணக்கிட்ட விலை வரம்பு",
    "ai_est_high_conf": "✓ அதிக நம்பகத்தன்மை",
    "ai_est_med_conf": "~ நடுத்தர நம்பகத்தன்மை",
    "ai_est_low_conf": "! குறைந்த நம்பகத்தன்மை",
    "ai_est_book_prefix": "முன்பதிவு செய்",
    "ai_est_get_btn": "✨ AI விலை கணிப்பைப் பெறுங்கள்",
    "ai_est_loading": "விலை கணக்கிடப்படுகிறது...",
    "ai_est_error_min_len": "தயவுசெய்து குறைந்தபட்சம் 10 எழுத்துகளில் விவரிக்கவும்.",
    "app_badge": "📱 விரைவில் வருகிறது",
    "app_title": "HelperHub உங்கள் பாக்கெட்டில்",
    "app_sub": "மொபைலில் எளிதாக முன்பதிவு செய்யுங்கள். iOS மற்றும் Android விரைவில்!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-தட்டு அவசர தீர்வு",
    "cta_hire_title": "பழுதுபார்க்க தயாரா? 🛠️",
    "cta_hire_sub": "ஆயிரக்கணக்கான வீட்டு உரிமையாளர்களுடன் இணையுங்கள்!",
    "cta_hire_btn": "இப்போதே ஹீரோவை தேர்வு செய்",
    "cta_work_title": "நீங்கள் திறமையான நிபுணரா?",
    "cta_work_sub": "உதவியாளராக இணைந்து சம்பாதிக்கத் தொடங்குங்கள்!",
    "cta_work_btn": "உதவியாளராக சேரு",
    "auth_welcome": "மீண்டும் வரவேற்கிறோம்! 👋",
    "auth_join": "HelperHub-ல் சேருங்கள்! 🎉",
    "auth_create_free": "இலவச கணக்கை உருவாக்குங்கள்",
    "auth_sign_in_to": "டாஷ்போர்டில் நுழையுங்கள்",
    "auth_tab_signin": "உள்நுழை",
    "auth_tab_create": "கணக்கை உருவாக்கு",
    "auth_joining_as": "நான் சேருகிறேன்...",
    "auth_role_hire": "எனக்கு உதவி வேண்டும் 🏠",
    "auth_role_hire_desc": "வீட்டு பழுதுபார்ப்புக்கு உதவியாளரை முன்பதிவு செய்யுங்கள்",
    "auth_role_work": "நான் வேலை செய்வேன் 🛠️",
    "auth_role_work_desc": "உங்கள் திறமையால் சம்பாதிக்கவும்",
    "auth_full_name": "முழு பெயர்",
    "auth_email": "மின்னஞ்சல்",
    "auth_password": "கடவுச்சொல்",
    "auth_create_btn": "கணக்கை உருவாக்கு 🎉",
    "auth_signin_btn": "உள்நுழை 🚀",
    "auth_loading": "காத்திருங்கள்...",
    "auth_demo": "டெமோ கணக்குகள்:",
    "auth_google_continue": "Google மூலம் தொடரவும்",
    "auth_or_email": "அல்லது மின்னஞ்சல் மூலம்",
    "otp_title": "மின்னஞ்சலை சரிபார்க்கவும்",
    "otp_sent": "6 இலக்க குறியீடு அனுப்பப்பட்டது",
    "otp_verify_btn": "சரிபார்க்கவும்! 🎉",
    "otp_verifying": "சரிபார்க்கிறது...",
    "otp_back": "பின்செல்",
    "browse_location": "📍 டெல்லி",
    "browse_search": "பிளம்பர், எலக்ட்ரீஷியன்...",
    "browse_search_placeholder": "பிளம்பர், எலக்ட்ரீஷியன், பெயிண்டர் தேடுங்கள்...",
    "browse_filters": "வடிப்பான்கள்",
    "browse_filter_btn": "வடிப்பான்கள்",
    "browse_results": "உதவியாளர்கள் கண்டுபிடிக்கப்பட்டனர்",
    "browse_no_results": "உதவியாளர்கள் கிடைக்கவில்லை.",
    "browse_filter_price": "அதிகபட்ச விலை",
    "browse_filter_distance": "தூரம்",
    "browse_filter_rating": "குறைந்த மதிப்பீடு",
    "browse_filter_experience": "ஆண்டுகள் அனுபவம்",
    "browse_filter_language": "மொழி",
    "browse_filter_verified": "சரிபார்க்கப்பட்டவர்கள் மட்டும்",
    "browse_filter_today": "இன்று கிடைக்கும்",
    "browse_filter_emergency": "அவசர SOS",
    "browse_filter_reset": "மீட்டமை",
    "browse_book": "இப்போதே முன்பதிவு",
    "browse_cat_all": "அனைத்தும்",
    "book_step_date": "தேதி",
    "book_step_time": "நேரம்",
    "book_step_details": "விவரங்கள்",
    "book_step_review": "மதிப்பாய்வு",
    "book_step_payment": "பணம்",
    "book_choose_date": "தேதியை தேர்ந்தெடுக்கவும்",
    "book_choose_time": "நேரம் தேர்ந்தெடுக்கவும்",
    "book_slots_for": "ஸ்லாட்கள் காட்டுகிறது",
    "book_booked": "முன்பதிவு செய்யப்பட்டது",
    "book_job_title": "வேலை பெயர்",
    "book_job_desc": "பிரச்சனையை விவரிக்கவும்",
    "book_address": "முழு முகவரி",
    "book_upload": "புகைப்படங்களை பதிவேற்றவும்",
    "book_upload_hint": "இங்கு கிளிக் செய்யவும்",
    "book_review_heading": "முன்பதிவை மதிப்பாய்வு செய்யுங்கள்",
    "book_hero": "ஹீரோ",
    "book_service": "சேவை",
    "book_date": "தேதி",
    "book_time": "நேரம்",
    "book_job": "வேலை",
    "book_address_label": "முகவரி",
    "book_service_fee": "சேவை கட்டணம்",
    "book_platform_fee": "தள கட்டணம்",
    "book_total": "மொத்தம்",
    "book_escrow": "உங்கள் பணம் எஸ்க்ரோவில் பாதுகாப்பாக உள்ளது.",
    "book_pay_secure": "பாதுகாப்பான பணம்",
    "book_card_number": "அட்டை எண்",
    "book_expiry": "காலாவதி தேதி",
    "book_cvv": "CVV",
    "book_name_card": "அட்டையில் பெயர்",
    "book_ssl": "256-bit SSL · Stripe",
    "book_pay_btn": "பணம் செலுத்துங்கள்",
    "book_securely": "🔒",
    "book_continue": "தொடரவும்",
    "book_back": "பின்செல்",
    "book_cancel": "ரத்துசெய்",
    "book_processing": "செயலாக்கப்படுகிறது...",
    "book_confirmed_title": "முன்பதிவு உறுதியானது! 🎉",
    "book_confirmed_sub": "உங்கள் ஹீரோ வழியில்!",
    "book_view_status": "நிலையை பார் →",
    "book_close": "மூடு",
    "sos_btn": "SOS அவசரம்",
    "sos_title": "🚨 அவசர SOS உதவி",
    "sos_subtitle": "அவசர ஆபத்துகளுக்கு 15 நிமிடங்களில் உதவி",
    "sos_banner": "உடனடி உதவி வேண்டுமா? கீழே தேர்ந்தெடுக்கவும்.",
    "sos_dispatch_btn": "ஹீரோவை அனுப்புங்கள்",
    "sos_dispatching": "ஹீரோ அனுப்பப்படுகிறார்...",
    "sos_unit_active": "24/7 விரைவு மீட்புக் குழு தயார்",
    "sos_electrician_title": "அவசர எலக்ட்ரீஷியன்",
    "sos_electrician_desc": "மின் தடை, ஷார்ட் சர்க்யூட் அல்லது ஸ்பார்க்.",
    "sos_gas_title": "எரிவாயு கசிவு அவசரம்",
    "sos_gas_desc": "எரிவாயு வாசனை அல்லது ரெகுலேட்டர் கோளாறு.",
    "sos_pipe_title": "பைப் உடைப்பு",
    "sos_pipe_desc": "நீர் கசிவு அல்லது மெயின் வால்வு கோளாறு.",
    "sos_lock_title": "பூட்டு பிரச்சனை",
    "sos_lock_desc": "சாவி முறிந்தது அல்லது பூட்டு சிக்கியது.",
    "sos_water_title": "நீர் கசிவு & நிரம்பி வழிதல்",
    "sos_water_desc": "தொட்டி நிரம்பி வழிதல் அல்லது கூரை கசிவு.",
    "sos_fire_title": "மின்சார தீ & புகை",
    "sos_fire_desc": "வயர் எரியும் வாசனை அல்லது அதிக வெப்பம்.",
    "footer_tagline": "நம்பகமான அக்கம்பக்க சேவை தளம்.",
    "footer_services": "சேவைகள்",
    "footer_company": "நிறுவனம்",
    "footer_contact": "தொடர்பு கொள்ள",
    "footer_legal": "சட்டம்",
    "footer_about": "எங்களைப் பற்றி",
    "footer_careers": "வேலைகள்",
    "footer_blog": "வலைப்பதிவு",
    "footer_press": "பிரெஸ்",
    "footer_privacy": "தனியுரிமை கொள்கை",
    "footer_terms": "சேவை விதிமுறைகள்",
    "footer_refund": "திரும்பப்பெறும் கொள்கை",
    "footer_rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    "dash_welcome": "மீண்டும் வரவேற்கிறோம்",
    "dash_active_jobs": "செயலில் வேலைகள்",
    "dash_total_spent": "மொத்த செலவு",
    "dash_total_earned": "மொத்த வருமானம்",
    "dash_rating": "மதிப்பீடு",
    "dash_completed": "முடிந்தது",
    "dash_pending": "நிலுவையில் உள்ளவை",
    "dash_accepted": "ஏற்றுக்கொள்ளப்பட்டது",
    "general_loading": "ஏற்றுகிறது...",
    "general_see_all": "அனைத்தும் பார்",
    "general_close": "மூடு",
    "general_save": "சேமி",
    "general_cancel": "ரத்துசெய்",
    "general_confirm": "உறுதிப்படுத்து",
    "general_hrs": "மணி",
    "general_per_hr": "/மணி",
    "general_jobs": "வேலைகள்",
    "general_yrs": "ஆண்டுகள்",
    "general_today": "இன்று",
    "general_tomorrow": "நாளை"
  },
  "kn": {
    "nav_find": "ಸಹಾಯಕನನ್ನು ಹುಡುಕಿ",
    "nav_how": "ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    "nav_signin": "ಸೈನ್ ಇನ್",
    "nav_notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "nav_language": "ಭಾಷೆ",
    "nav_dark": "ಡಾರ್ಕ್",
    "nav_light": "ಲೈಟ್",
    "nav_dashboard": "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "nav_signout": "ಸೈನ್ ಔಟ್",
    "nav_mark_all_read": "ಎಲ್ಲವನ್ನೂ ಓದಿದೆ",
    "nav_view_all": "ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳು →",
    "notif_1_title": "ಬುಕಿಂಗ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ! 🎉",
    "notif_1_body": "ರಾಜೇಶ್ ಕುಮಾರ್ ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದ್ದಾರೆ.",
    "notif_2_title": "ಪಾವತಿ ಯಶಸ್ವಿ ✅",
    "notif_2_body": "₹500 ಎಸ್ಕ್ರೋ ಮೂಲಕ ಪಾವತಿಸಲಾಗಿದೆ.",
    "notif_3_title": "ಕಾರ್ಮಿಕ ಬರುತ್ತಿದ್ದಾರೆ 🚗",
    "notif_3_body": "ಸುನೀತಾ ಶರ್ಮಾ 10 ನಿಮಿಷಗಳಲ್ಲಿ ಬರುತ್ತಾರೆ.",
    "notif_4_title": "ಕೆಲಸ ಪೂರ್ಣವಾಯಿತು 🛠️",
    "notif_4_body": "ಅಡಿಗೆ ಸಿಂಕ್ ರಿಪೇರಿ ಪೂರ್ಣ.",
    "notif_5_title": "ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ ⭐",
    "notif_5_body": "ಅಜಯ್ ಪಟೇಲ್ ಹೇಗಿದ್ದರು?",
    "hero_badge": "🏠 50,000+ ಮನೆ ಮಾಲೀಕರು ನಂಬುತ್ತಾರೆ",
    "hero_title_1": "ನಿಮ್ಮ ನೆರೆಹೊರೆಯ",
    "hero_title_2": "ಫಿಕ್ಸ್-ಇಟ್ ಹೀರೋಗಳು",
    "hero_title_3": "ಒಂದು ಟ್ಯಾಪ್ ದೂರದಲ್ಲಿ",
    "hero_sub": "ಪ್ಲಂಬರ್, ಎಲೆಕ್ಟ್ರೀಷಿಯನ್, ಪೇಂಟರ್ ಬುಕ್ ಮಾಡಿ. ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು.",
    "hero_search_placeholder": "ಏನು ಸರಿಪಡಿಸಬೇಕು? ಉದಾ. AC ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿಲ್ಲ...",
    "hero_search_btn": "ಹೀರೋ ಹುಡುಕಿ 🔍",
    "hero_or": "ಅಥವಾ ವರ್ಗದ ಮೂಲಕ ಬ್ರೌಸ್ ಮಾಡಿ",
    "hero_stat_1": "50K+ ಮನೆ ಮಾಲೀಕರು",
    "hero_stat_2": "2,000+ ಹೀರೋಗಳು",
    "hero_stat_3": "4.9★ ರೇಟಿಂಗ್",
    "landing_cat_badge": "ವರ್ಗಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    "landing_cat_browse": "ಬ್ರೌಸ್ ಮಾಡಿ",
    "landing_hiw_badge": "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    "landing_top_badge": "ಟಾಪ್ ರೇಟೆಡ್",
    "landing_top_explore": "ಎಲ್ಲವನ್ನೂ ಅನ್ವೇಷಿಸಿ",
    "landing_jobs_badge": "ಇತ್ತೀಚೆಗೆ ಮುಗಿದ ಕೆಲಸಗಳು",
    "landing_live_activity": "⚡ ನೇರ ಚಟುವಟಿಕೆ",
    "landing_test_badge": "ಗ್ರಾಹಕರ ಅನುಭವಗಳು",
    "landing_why_badge": "HelperHub ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು",
    "landing_quick_popular": "ಜನಪ್ರಿಯ:",
    "landing_card_master": "ಮಾಸ್ಟರ್ ವೃತ್ತಿಪರ",
    "landing_card_reviews": "ವಿಮರ್ಶೆಗಳು",
    "landing_card_all_set": "ಎಲ್ಲವೂ ಸಿದ್ಧ!",
    "landing_card_done": "ಬುಕಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "landing_card_verified": "ಪರಿಶೀಲಿಸಿದ ಪ್ರೊ",
    "landing_card_jobs": "ಕೆಲಸಗಳು",
    "landing_card_flexible": "ಹೊಂದಿಕೊಳ್ಳುವ ಸಮಯ",
    "landing_card_view": "ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    "landing_no_helpers": "ಯಾವುದೇ ಸಹಾಯಕರು ನೋಂದಣಿಯಾಗಿಲ್ಲ",
    "categories_title": "ಇಂದು ಏನು ಸರಿಪಡಿಸಬೇಕು?",
    "categories_sub": "ಒಂದು ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ, ನಾವು ಹೀರೋಗಳನ್ನು ಹುಡುಕುತ್ತೇವೆ.",
    "cat_plumber": "ಪ್ಲಂಬರ್",
    "cat_electrician": "ಎಲೆಕ್ಟ್ರೀಷಿಯನ್",
    "cat_carpenter": "ಮರಗೆಲಸದವರು",
    "cat_ac": "AC ತಂತ್ರಜ್ಞ",
    "cat_painter": "ಪೇಂಟರ್",
    "cat_cleaner": "ಕ್ಲೀನರ್",
    "cat_mechanic": "ಮೆಕ್ಯಾನಿಕ್",
    "cat_gardener": "ತೋಟಗಾರ",
    "cat_repair": "ಸಾಮಾನ್ಯ ರಿಪೇರಿ",
    "how_title": "⭐ HelperHub ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    "how_sub": "5 ಸರಳ ಹಂತಗಳಲ್ಲಿ",
    "how_step1_title": "ಸೇವೆ ಹುಡುಕಿ 🔍",
    "how_step1_desc": "ನಿಮ್ಮ ಅಗತ್ಯ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ವರ್ಗದ ಮೂಲಕ ನೋಡಿ.",
    "how_step2_title": "ತಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಿ 🤝",
    "how_step2_desc": "ಟಾಪ್-ರೇಟೆಡ್ ಹೀರೋ ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಸಮಯ ನಿಗದಿಪಡಿಸಿ.",
    "how_step3_title": "ಸುರಕ್ಷಿತ ಪಾವತಿ 🔒",
    "how_step3_desc": "ಕೆಲಸ ಮುಗಿಯುವ ತನಕ ಹಣ ಎಸ್ಕ್ರೋದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ.",
    "how_step4_title": "ಕೆಲಸ ಮುಗಿಯಿತು 🛠️",
    "how_step4_desc": "ಹೀರೋ ನಿಮ್ಮ ಮನೆಗೆ ಬಂದು ಕೆಲಸ ಮಾಡುತ್ತಾರೆ.",
    "how_step5_title": "ಅನುಭವ ರೇಟ್ ಮಾಡಿ ⭐",
    "how_step5_desc": "ರಿವ್ಯೂ ಕೊಡಿ, ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ.",
    "top_title": "⭐ ನಿಮ್ಮ ಬಳಿಯ ಟಾಪ್ ತಜ್ಞರು",
    "top_sub": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ, 4.8+ ರೇಟಿಂಗ್",
    "top_view_all": "ಎಲ್ಲಾ ಸಹಾಯಕರನ್ನು ನೋಡಿ →",
    "recent_title": "⚡ ಇತ್ತೀಚೆಗೆ ಮುಗಿದ ಕೆಲಸಗಳು",
    "recent_sub": "ನಿಮ್ಮ ನಗರದಲ್ಲಿ ನಡೆಯುತ್ತಿರುವ ತಾಜಾ ಕೆಲಸಗಳು",
    "job_kitchen_sink": "ಅಡುಗೆಮನೆ ಸಿಂಕ್ ಸೋರಿಕೆ ಸರಿಪಡಿಸಲಾಗಿದೆ",
    "job_split_ac": "ಸ್ಪ್ಲಿಟ್ ಎಸಿ ಅಳವಡಿಸಲಾಗಿದೆ",
    "job_living_room_paint": "ಲಿವಿಂಗ್ ರೂಮ್ ಪೇಂಟಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "job_mcb_tripping": "ಮುಖ್ಯ ಎಂಸಿಬಿ ಸಮಸ್ಯೆ ಸರಿಪಡಿಸಲಾಗಿದೆ",
    "job_door_repair": "ಮರದ ಬಾಗಿಲಿನ ಚೌಕಟ್ಟು ರಿಪೇರಿ ಮಾಡಲಾಗಿದೆ",
    "testimonials_title": "❤️ ಮನೆ ಮಾಲೀಕರು ಏನು ಹೇಳುತ್ತಾರೆ",
    "testimonials_sub": "ನೆರೆಯವರ ನಿಜವಾದ ಕಥೆಗಳು",
    "test_1_quote": "\"2 ನಿಮಿಷಗಳಲ್ಲಿ ಪ್ಲಂಬರ್ ಬುಕ್ ಮಾಡಿದೆ, ರಾಜೇಶ್ ಬೇಗನೆ ಬಂದು ಕೆಲಸ ಮುಗಿಸಿದರು!\"",
    "test_2_quote": "\"ಎಸ್ಕ್ರೋ ರಕ್ಷಣೆಯಿಂದ ಸಂಪೂರ್ಣ ಮನಸ್ಸಿನ ಶಾಂತಿ ಸಿಕ್ಕಿತು. ಅತ್ಯುತ್ತಮ ಆಪ್!\"",
    "test_3_quote": "\"ಪಾರದರ್ಶಕ ಬೆಲೆ ಮತ್ತು ಉತ್ತಮ ಸೇವೆ. ತುಂಬಾ ಸಂತೋಷವಾಗಿದೆ.\"",
    "why_title": "🌟 HelperHub ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
    "why_sub": "ನಾವು ಕೇವಲ ಬುಕಿಂಗ್ ಆಪ್ ಅಲ್ಲ — ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ನೆಟ್‌ವರ್ಕ್.",
    "why_1_title": "✔ ಪರಿಶೀಲಿಸಿದ ತಜ್ಞರು",
    "why_1_desc": "ಆಧಾರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    "why_2_title": "✔ ಸುರಕ್ಷಿತ ಪಾವತಿ",
    "why_2_desc": "ಕೆಲಸ ಮುಗಿದ ನಂತರ ಮಾತ್ರ ಪಾವತಿ ಬಿಡುಗಡೆ.",
    "why_3_title": "✔ AI ಬೆಲೆ ಅಂದಾಜು",
    "why_3_desc": "ಬುಕ್ ಮಾಡುವ ಮುನ್ನವೇ ಸರಿಯಾದ ಬೆಲೆ ತಿಳಿಯಿರಿ.",
    "why_4_title": "✔ ತುರ್ತು ಬುಕಿಂಗ್",
    "why_4_desc": "24/7 ತುರ್ತು ಸೇವೆಗಳು ಲಭ್ಯವಿದೆ.",
    "ai_est_title": "AI ಬೆಲೆ ಅಂದಾಜು ಸಾಧನ",
    "ai_est_badge": "✨ Claude AI ನಿಂದ ಚಾಲಿತ",
    "ai_est_subtitle": "ಕೆಲಸವನ್ನು ವಿವರಿಸಿ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ದರಗಳ ಪ್ರಕಾರ AI ಅಂದಾಜು ಪಡೆಯಿರಿ.",
    "ai_est_service_type": "ಸೇವಾ ಪ್ರಕಾರ",
    "ai_est_city": "ನಗರ",
    "ai_est_job_desc": "ಕೆಲಸದ ವಿವರಣೆ",
    "ai_est_job_desc_hint": "(ಏನು ಮಾಡಬೇಕು?)",
    "ai_est_placeholder": "ಉದಾ: ಸಿಂಕ್ ಪೈಪ್ ಸೋರುತ್ತಿದೆ...",
    "ai_est_price_range": "AI ಅಂದಾಜು ಮಾಡಿದ ಬೆಲೆ ಶ್ರೇಣಿ",
    "ai_est_high_conf": "✓ ಹೆಚ್ಚಿನ ನಿಖರತೆ",
    "ai_est_med_conf": "~ ಮಧ್ಯಮ ನಿಖರತೆ",
    "ai_est_low_conf": "! ಕಡಿಮೆ ನಿಖರತೆ",
    "ai_est_book_prefix": "ಬುಕ್ ಮಾಡಿ",
    "ai_est_get_btn": "✨ AI ಬೆಲೆ ಅಂದಾಜು ಪಡೆಯಿರಿ",
    "ai_est_loading": "ಬೆಲೆ ಅಂದಾಜಿಸಲಾಗುತ್ತಿದೆ...",
    "ai_est_error_min_len": "ದಯವಿಟ್ಟು ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳಲ್ಲಿ ವಿವರಿಸಿ.",
    "app_badge": "📱 ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ",
    "app_title": "HelperHub ನಿಮ್ಮ ಜೇಬಿನಲ್ಲಿ",
    "app_sub": "ಫೋನ್‌ನಿಂದ ಸುಲಭವಾಗಿ ಬುಕ್ ಮಾಡಿ. iOS ಮತ್ತು Android ಶೀಘ್ರದಲ್ಲೇ!",
    "app_ios": "🍎 App Store",
    "app_android": "🤖 Google Play",
    "app_mockup_title": "HelperHub SOS",
    "app_mockup_desc": "1-ಟ್ಯಾಪ್ ತುರ್ತು ರಿಪೇರಿ",
    "cta_hire_title": "ಮನೆ ರಿಪೇರಿಗೆ ಸಿದ್ಧರಿದ್ದೀರಾ? 🛠️",
    "cta_hire_sub": "ಸಾವಿರಾರು ಸಂತೋಷದ ಮನೆ ಮಾಲೀಕರೊಂದಿಗೆ ಸೇರಿ!",
    "cta_hire_btn": "ಈಗಲೇ ನಿಮ್ಮ ಹೀರೋ ಆಯ್ಕೆಮಾಡಿ",
    "cta_work_title": "ನೀವು ನುರಿತ ತಜ್ಞರಾ?",
    "cta_work_sub": "ಸಹಾಯಕರಾಗಿ ಸೇರಿ ಮತ್ತು ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ!",
    "cta_work_btn": "ಸಹಾಯಕರಾಗಿ ಸೇರಿ",
    "auth_welcome": "ಮತ್ತೆ ಸ್ವಾಗತ! 👋",
    "auth_join": "HelperHub ಗೆ ಸೇರಿ! 🎉",
    "auth_create_free": "ಉಚಿತ ಖಾತೆ ರಚಿಸಿ",
    "auth_sign_in_to": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ",
    "auth_tab_signin": "ಸೈನ್ ಇನ್",
    "auth_tab_create": "ಖಾತೆ ರಚಿಸಿ",
    "auth_joining_as": "ನಾನು ಸೇರುತ್ತಿದ್ದೇನೆ...",
    "auth_role_hire": "ನನಗೆ ಸಹಾಯ ಬೇಕು 🏠",
    "auth_role_hire_desc": "ಮನೆ ರಿಪೇರಿಗೆ ಸಹಾಯಕರನ್ನು ಬುಕ್ ಮಾಡಿ",
    "auth_role_work": "ನಾನು ಕೆಲಸ ಮಾಡುತ್ತೇನೆ 🛠️",
    "auth_role_work_desc": "ನಿಮ್ಮ ಕೌಶಲ್ಯದಿಂದ ಸಂಪಾದಿಸಿ",
    "auth_full_name": "ಪೂರ್ಣ ಹೆಸರು",
    "auth_email": "ಇಮೇಲ್",
    "auth_password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth_create_btn": "ಖಾತೆ ರಚಿಸಿ 🎉",
    "auth_signin_btn": "ಸೈನ್ ಇನ್ 🚀",
    "auth_loading": "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
    "auth_demo": "ಡೆಮೋ ಖಾತೆಗಳು:",
    "auth_google_continue": "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    "auth_or_email": "ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ",
    "otp_title": "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
    "otp_sent": "6 ಅಂಕಿ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ",
    "otp_verify_btn": "ಪರಿಶೀಲಿಸಿ! 🎉",
    "otp_verifying": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "otp_back": "ಹಿಂದೆ",
    "browse_location": "📍 ದೆಹಲಿ",
    "browse_search": "ಪ್ಲಂಬರ್, ಎಲೆಕ್ಟ್ರೀಷಿಯನ್...",
    "browse_search_placeholder": "ಪ್ಲಂಬರ್, ಎಲೆಕ್ಟ್ರೀಷಿಯನ್, ಪೇಂಟರ್ ಹುಡುಕಿ...",
    "browse_filters": "ಫಿಲ್ಟರ್‌ಗಳು",
    "browse_filter_btn": "ಫಿಲ್ಟರ್‌ಗಳು",
    "browse_results": "ಸಹಾಯಕರು ಕಂಡುಬಂದರು",
    "browse_no_results": "ಸಹಾಯಕರು ಕಂಡುಬಂದಿಲ್ಲ.",
    "browse_filter_price": "ಗರಿಷ್ಠ ಬೆಲೆ",
    "browse_filter_distance": "ದೂರ",
    "browse_filter_rating": "ಕನಿಷ್ಠ ರೇಟಿಂಗ್",
    "browse_filter_experience": "ವರ್ಷಗಳ ಅನುಭವ",
    "browse_filter_language": "ಭಾಷೆ",
    "browse_filter_verified": "ಪರಿಶೀಲಿಸಿದವರು ಮಾತ್ರ",
    "browse_filter_today": "ಇಂದು ಲಭ್ಯ",
    "browse_filter_emergency": "ತುರ್ತು SOS",
    "browse_filter_reset": "ರೀಸೆಟ್",
    "browse_book": "ಈಗ ಬುಕ್ ಮಾಡಿ",
    "browse_cat_all": "ಎಲ್ಲಾ",
    "book_step_date": "ದಿನಾಂಕ",
    "book_step_time": "ಸಮಯ",
    "book_step_details": "ವಿವರಗಳು",
    "book_step_review": "ಪರಿಶೀಲನೆ",
    "book_step_payment": "ಪಾವತಿ",
    "book_choose_date": "ದಿನಾಂಕ ಆಯ್ಕೆ ಮಾಡಿ",
    "book_choose_time": "ಸಮಯ ಆಯ್ಕೆ ಮಾಡಿ",
    "book_slots_for": "ಸ್ಲಾಟ್‌ಗಳು ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    "book_booked": "ಬುಕ್ ಆಗಿದೆ",
    "book_job_title": "ಕೆಲಸದ ಹೆಸರು",
    "book_job_desc": "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    "book_address": "ಪೂರ್ಣ ವಿಳಾಸ",
    "book_upload": "ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "book_upload_hint": "ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "book_review_heading": "ಬುಕಿಂಗ್ ಪರಿಶೀಲಿಸಿ",
    "book_hero": "ಹೀರೋ",
    "book_service": "ಸೇವೆ",
    "book_date": "ದಿನಾಂಕ",
    "book_time": "ಸಮಯ",
    "book_job": "ಕೆಲಸ",
    "book_address_label": "ವಿಳಾಸ",
    "book_service_fee": "ಸೇವಾ ಶುಲ್ಕ",
    "book_platform_fee": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ",
    "book_total": "ಒಟ್ಟು",
    "book_escrow": "ನಿಮ್ಮ ಹಣ ಎಸ್ಕ್ರೋದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
    "book_pay_secure": "ಸುರಕ್ಷಿತ ಪಾವತಿ",
    "book_card_number": "ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
    "book_expiry": "ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ",
    "book_cvv": "CVV",
    "book_name_card": "ಕಾರ್ಡ್‌ನಲ್ಲಿ ಹೆಸರು",
    "book_ssl": "256-ಬಿಟ್ SSL · Stripe",
    "book_pay_btn": "ಪಾವತಿ ಮಾಡಿ",
    "book_securely": "🔒",
    "book_continue": "ಮುಂದುವರಿಯಿರಿ",
    "book_back": "ಹಿಂದೆ",
    "book_cancel": "ರದ್ದು ಮಾಡಿ",
    "book_processing": "ಪ್ರಕ್ರಿಯೆ ಆಗುತ್ತಿದೆ...",
    "book_confirmed_title": "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ! 🎉",
    "book_confirmed_sub": "ನಿಮ್ಮ ಹೀರೋ ದಾರಿಯಲ್ಲಿ!",
    "book_view_status": "ಸ್ಥಿತಿ ನೋಡಿ →",
    "book_close": "ಮುಚ್ಚಿ",
    "sos_btn": "SOS ತುರ್ತು",
    "sos_title": "🚨 ತುರ್ತು SOS ನೆರವು",
    "sos_subtitle": "ತುರ್ತು ಅಪಾಯಗಳಿಗೆ 15 ನಿಮಿಷಗಳಲ್ಲಿ ನೆರವು",
    "sos_banner": "ತಕ್ಷಣ ಸಹಾಯ ಬೇಕೇ? ಕೆಳಗೆ ಆಯ್ಕೆಮಾಡಿ.",
    "sos_dispatch_btn": "ಹೀರೋ ಕಳುಹಿಸಿ",
    "sos_dispatching": "ಹೀರೋ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    "sos_unit_active": "24/7 ಕ್ಷಿಪ್ರ ಪ್ರತಿಕ್ರಿಯೆ ಪಡೆ ಸಕ್ರಿಯ",
    "sos_electrician_title": "ತುರ್ತು ಎಲೆಕ್ಟ್ರೀಷಿಯನ್",
    "sos_electrician_desc": "ವಿದ್ಯುತ್ ವ್ಯತ್ಯಯ, ಶಾರ್ಟ್ ಸರ್ಕ್ಯೂಟ್ ಅಥವಾ ಸ್ಪಾರ್ಕಿಂಗ್.",
    "sos_gas_title": "ಗ್ಯಾಸ್ ಸೋರಿಕೆ ತುರ್ತು",
    "sos_gas_desc": "ಅನಿಲ ವಾಸನೆ ಅಥವಾ ರೆಗ್ಯುಲೇಟರ್ ದೋಷ.",
    "sos_pipe_title": "ಪೈಪ್ ಒಡೆಯುವಿಕೆ",
    "sos_pipe_desc": "ನೀರು ಸೋರಿಕೆ ಅಥವಾ ಮುಖ್ಯ ವಾಲ್ವ್ ದೋಷ.",
    "sos_lock_title": "ಬಾಗಿಲು ಲಾಕ್ ಆಗಿರುವುದು",
    "sos_lock_desc": "ಕೀ ಕಳೆದುಹೋಗಿರುವುದು ಅಥವಾ ಲಾಕ್ ಸಮಸ್ಯೆ.",
    "sos_water_title": "ನೀರು ಸೋರಿಕೆ ಸಮಸ್ಯೆ",
    "sos_water_desc": "ಟ್ಯಾಂಕ್ ಓವರ್‌ಫ್ಲೋ ಅಥವಾ ಸೋರಿಕೆ.",
    "sos_fire_title": "ವೈರ್ ಬೆಂಕಿ ಅಥವಾ ಹೊಗೆ",
    "sos_fire_desc": "ವೈರಿಂಗ್ ಸುಡುವ ವಾಸನೆ ಅಥವಾ ಬಿಸಿಯಾಗುವುದು.",
    "footer_tagline": "ವಿಶ್ವಾಸಾರ್ಹ ನೆರೆಹೊರೆ ಸೇವಾ ವೇದಿಕೆ.",
    "footer_services": "ಸೇವೆಗಳು",
    "footer_company": "ಕಂಪನಿ",
    "footer_contact": "ಸಂಪರ್ಕ",
    "footer_legal": "ಕಾನೂನು",
    "footer_about": "ನಮ್ಮ ಬಗ್ಗೆ",
    "footer_careers": "ಉದ್ಯೋಗ",
    "footer_blog": "ಬ್ಲಾಗ್",
    "footer_press": "ಪ್ರೆಸ್",
    "footer_privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
    "footer_terms": "ಸೇವಾ ನಿಯಮಗಳು",
    "footer_refund": "ಮರುಪಾವತಿ ನೀತಿ",
    "footer_rights": "ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿವೆ.",
    "dash_welcome": "ಮತ್ತೆ ಸ್ವಾಗತ",
    "dash_active_jobs": "ಸಕ್ರಿಯ ಕೆಲಸಗಳು",
    "dash_total_spent": "ಒಟ್ಟು ಖರ್ಚು",
    "dash_total_earned": "ಒಟ್ಟು ಆದಾಯ",
    "dash_rating": "ರೇಟಿಂಗ್",
    "dash_completed": "ಮುಗಿದಿದೆ",
    "dash_pending": "ಬಾಕಿ ಇದೆ",
    "dash_accepted": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    "general_loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "general_see_all": "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    "general_close": "ಮುಚ್ಚಿ",
    "general_save": "ಉಳಿಸಿ",
    "general_cancel": "ರದ್ದು",
    "general_confirm": "ದೃಢೀಕರಿಸಿ",
    "general_hrs": "ಗಂಟೆ",
    "general_per_hr": "/ಗಂಟೆ",
    "general_jobs": "ಕೆಲಸಗಳು",
    "general_yrs": "ವರ್ಷಗಳು",
    "general_today": "ಇಂದು",
    "general_tomorrow": "ನಾಳೆ"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('hh-lang') || 'en';
    return translations[saved] ? saved : 'en';
  });

  const changeLang = (code) => {
    if (translations[code]) {
      setLang(code);
      localStorage.setItem('hh-lang', code);
    }
  };

  // t(key, fallback) — returns translated string or fallback/English
  const t = (key, fallback) => {
    return translations[lang]?.[key] ?? translations.en[key] ?? fallback ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export { translations };
